[test] 유저와 인증의 테스트 픽스처를 만든다.
woowacourse-teams/2022-dallog pull request #107
Opened 2022-07-20 08:01 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
유저와 인증의 테스트 픽스처를 만든다.

## 주의사항

Closes #104

2022-07-20 11:20 UTC, summerlunaa approved these changes
코멘트 하나 남겼습니다. 리버 수고하셨습니당~~

2022-07-21 05:53 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/acceptance/fixtures/CategoryAcceptanceFixtures.java
> +    public static ExtractableResponse<Response> 새로운_카테고리를_등록한다(final String token, final String name) {
파랑에 동의합니다! 나중에 리프레시 토큰을 사용하게 된다면, `token` 으로 네이밍된 변수를 모두 변경해야할 것 같아요!

2022-07-21 05:55 UTC, devHudi requested changes
파랑이 남겨준 부분만 수정해주면 좋을 것 같아요! 고생하셔습니다 리버~!

2022-07-21 05:55 UTC, devHudi commented
+ 컨플릭트를 해결해야할 것 같아요 😵‍💫

2022-07-21 06:02 UTC, hyeonic approved these changes
굳굳 Fixtures 덕분에 더 잘 읽히는 것 같네요! 고생하셨습니다 😀

2022-07-21 06:02 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/fixtures/AuthAcceptanceFixtures.java
> +        return tokenResponse.getAccessToken();
단독적인 String 타입의 token을 반환하기 보다 이후 추가될 다른 정보들을 조회할 우려가 있어서 TokenResponse를 반영하는 것이 좋을 것 같아요!

2022-07-21 06:42 UTC, summerlunaa approved these changes

2022-07-21 06:43 UTC, devHudi approved these changes
LGTM 입니다 😊👍

2022-07-21 06:48 UTC, merged