[feat] 자신이 생성한 카테고리를 수정 및 삭제하는 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #124
Opened 2022-07-21 07:51 UTC by summerlunaa

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

자신이 생성한 카테고리를 수정 및 삭제하는 기능을 구현한다.

Closes #97

2022-07-21 08:11 UTC, gudonghee2000 reviewed
안녕하세요 파랑! 작성해주신 카테고리 수정 및 삭제기능 잘보았어요!👍😊
꼼꼼한 테스트 코드가 인상깊었어요!
몇가지 제안해보고싶은 의견이있어서 남겨보았습니다!

2022-07-21 08:11 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
> +        CategoryResponse savedCategory = 새로운_카테고리를_등록한다(tokenResponse, CATEGORY_NAME)
이 부분의 `자체_토큰을_생성한다()` 메서드를 `자체_토큰을_생성하고_토큰을_반환한다()`로 변경하면 `tokenResponse.getAccessToken()`을 제거할수 있을것 같아요!

2022-07-21 08:11 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/category/domain/CategoryRepositoryTest.java
> +                    .isTrue();
꼼꼼한 테스트 검증👍👍

2022-07-21 08:11 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +    }
카테고리가 수정 되는 경우에는 반환값을 `상태코드 200 OK` 를 주는건 어떨까 해요!
저는 200 이나 204 둘다 맞다고 생각이 들어요.

DB 데이터 수정 `update`를 `상태코드 200 OK`로 보면 데이터가 변경이 잘되었다는 걸 클라이언트에게 알려주는 느낌이라고 생각이들어요.
 
반대로
DB 데이터 수정 `update`를 `상태코드 204 NO CONTENT` 로 보면 반환 데이터로 으로 줄게 없다는걸 클라이언트에게 알려주는 느낌이라고 생각이 들어요.

논의를 해보거나 파랑이 정해주신 상태코드로 다른 `@PatchMapping`을 구현할때 적용하겠습니다!

그리고 update 파라미터에 `loginMember.getId()` 말고 `loginMember`를 주는건 어떨까 하기도해요. 
컨트롤러를 좀 더 깔끔하게 관리할수 있을 것같아요.
반대로 service 레이어에서 `getter`가 하나더 사용될수도 있긴하겟네요!

2022-07-21 22:40 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/CategoryAcceptanceTest.java
> +        CategoryResponse savedCategory = 새로운_카테고리를_등록한다(tokenResponse, CATEGORY_NAME)
머지하면서 잘못 수정되었네요 ㅠㅠ 반영했습니다!

2022-07-21 22:41 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +    }
같이 논의해볼 사항인 것 같네요!

2022-07-25 05:47 UTC, hyeonic requested changes
안녕하세요 파랑! 매트입니다. 간단히 코멘트 남겼어요! 아래 프론트 관련 수정 사항도 확인했는데 fetch, rebase가 진행됬는데 왜 추가되었는지 모르겠네요 ㅜㅠ 확인 한 번 부탁드립니다!

2022-07-25 05:47 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +    }
저는 `204`를 선호하는 편입니다!

2022-07-25 05:47 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
해당 애노테이션이 필요한 이유가 있을까요??

2022-07-25 07:01 UTC, devHudi requested changes
파랑 기능 구현하느라 고생 많으셨어요! 수정해야할 부분 몇가지를 찾아서 코멘트 남겨두었습니다! 감사해요.

2022-07-25 07:45 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +    }
오 저는 후디의 얘기를 들어보니 204가 맞는 것 같네요!
`LoginMember` 객체를 전달하는 부분은 id 말고 객체를 넘겨주는 게 더 깔끔해보일 것 같긴 하네요! 다른 분들은 어떠세요?

2022-07-25 07:48 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
엇 그렇네요 잘못 들어간 것 같아요. 삭제했습니다!

2022-07-25 07:51 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +    }
오 그렇네요! 예리하십니다ㅎㅎㅎ 굳굳

2022-07-25 07:55 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
> +        }
좋은 아이디어네요ㅎㅎ 반영했습니다.

2022-07-25 08:05 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +    }
그럼 `LoginMember` 객체를 전달하는 부분은 나중에 필요할 때 수정하는 것으로 할게요ㅎㅎ

2022-07-25 08:10 UTC, hyeonic approved these changes

2022-07-25 08:15 UTC, gudonghee2000 approved these changes

2022-07-25 08:15 UTC, devHudi approved these changes

2022-07-25 08:18 UTC, merged