[feat] Category의 예외 케이스 핸들링 로직을 추가한다.
woowacourse-teams/2022-dallog pull request #159
Opened 2022-07-26 11:34 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- 카테고리 삭제 및 수정 할 때 대상 카테고리가 존재하지 않으면 예외가 정상적으로 발생하는지 확인하는 테스트 코드 추가
- 존재하지 않는 ID로 카테고리를 단건 조회할 때 정상적으로 예외가 발생하는지에 대한 테스트 코드 추가
- Pageable의 최대 페이지 사이즈를 100으로 제한
- 누락된 final 키워드 추가

## 스크린샷

## 주의사항

Closes #144

2022-07-26 15:04 UTC, hyeonic requested changes
안녕하세여 후디! 매트입니다 😀

간단히 코멘트 남겼습니다. 확인해주시면 감사하겠습니다!

2022-07-26 15:04 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        validateCategoryExisting(categoryId);
`getMember`는 이미 검증되었기 때문에 제거 해도 괜찮을 것 같아요!

2022-07-26 15:04 UTC, hyeonic commented on backend/src/main/resources/application.yml
> +        max-page-size: 100
사이즈 제한 👍 해당 사이즈를 넘어 요청되면 어떤 예외가 발생하나요??

2022-07-26 15:06 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        validateCategoryExisting(categoryId);
카테고리 존재 여부를 검증할 필요가 없을까요??

2022-07-27 00:50 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        validateCategoryExisting(categoryId);
카테고리 존재 여부가 아니라 getMember 말하는 거 아닌가유???

2022-07-27 00:58 UTC, summerlunaa approved these changes
후디 빠르시네요,,,👍👍 잘 구현해주셔서 approve 날리고 갑니당~~

2022-07-27 00:58 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        Member creator = memberRepository.save(관리자());
hoxy creator > 관리자 ???

2022-07-27 02:51 UTC, devHudi commented on backend/src/main/resources/application.yml
> +        max-page-size: 100
별다른 예외가 발생하지 않다고 하네요! `max-page-size` 를 `100` 으로 지정한 상황에서 `1000` 을 집어넣어도 최대 100개의 row 만 조회하는 것 같습니다.

2022-07-27 02:54 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        validateCategoryExisting(categoryId);
아아 제가 잘못 이해했습니다. `update` 와 `delete` 에서 유저의 존재여부를 검사하기 위한 `getMember` 호출을 제거했습니다 (커밋: [6540601](https://github.com/woowacourse-teams/2022-dallog/pull/159/commits/65406019b1d20a1114e6221d667871ec73aa431b))

2022-07-27 02:55 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        Member creator = memberRepository.save(관리자());
이를 포함해서 given 절에서 픽스처를 사용하는 모든 지역 변수를 한글로 네이밍하였습니다 (커밋: 8eb235c)

2022-07-27 03:00 UTC, gudonghee2000 approved these changes
안녕하세요 후디! member의 존재여부를 검사하는 로직과 테스트 코드에 `creator`를 `관리자`로 변경하셨군요!
작성해주신 코드 잘보았어요!👍👍
또한, pageable의 사이즈를 설정파일로 제한할수도있군요! 
새로운걸 배우게되었네요😊😊

매트가 남겨주었던 리뷰와 같이 
pageable 사이즈를 설정파일로 제한했을때,
사이즈를 넘는 요청이 오게되면 예외가 발생하는것일까요??

변경해주신 코드도 모두 확인해서
바로 Approve하였습니다!

2022-07-27 03:01 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        Member creator = memberRepository.save(관리자());
변경되었습니다!

2022-07-27 04:57 UTC, hyeonic submitted a review, later dismissed

2022-07-27 04:59 UTC, hyeonic approved these changes

2022-07-27 05:09 UTC, merged