Feature/148 subscription rest docs
woowacourse-teams/2022-dallog pull request #173
Opened 2022-07-28 10:31 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

Subscription에 대한 컨트롤러 테스트를 추가하여 API 문서를 생성한다.

Closes #148

2022-07-28 10:50 UTC, devHudi approved these changes
매트, 잘 작성해주신 것 같아요! 고칠부분 없는 것 같아 Approve 드립니다!

2022-07-28 10:50 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(errorResponse);
감사합니다 ㅎㅎ ;;

2022-07-28 10:50 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +
굳굳 저도 이런식으로 작업해야겠어요~! 인사이트 감사합니다!

2022-07-28 10:50 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
> +
저도 이 상수 네이밍으로 통일하겠습니다~!

2022-07-29 00:22 UTC, summerlunaa requested changes
오타만 고치면 될 것 같아요!! 👍👍

2022-07-29 00:22 UTC, summerlunaa commented on backend/src/docs/asciidoc/subscription.adoc
> +=== 구독 등록
파일 분리 👍

2022-07-29 00:22 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/global/presentation/ControllerAdvice.java
> +        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(errorResponse);
감사합니다22..

2022-07-29 00:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
> +                                fieldWithPath("color").type(JsonFieldType.STRING).description("구독 색 장보")
`장보` 오타있습니다. 밑에서도 계속 중복되니 확인 부탁드립니다~

2022-07-29 02:47 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 작성해주신 코드 잘보았어요👍👍
깔끔한 코드!!😊
바로 approve 하겠습니다!

2022-07-29 03:10 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
> +                                fieldWithPath("color").type(JsonFieldType.STRING).description("구독 색 장보")
매의 눈 ㄷㄷ

2022-07-29 03:10 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/subscription/presentation/SubscriptionControllerTest.java
> +                                fieldWithPath("color").type(JsonFieldType.STRING).description("구독 색 장보")
변경 했습니다 ~ 확인 부탁 드려요 😃

2022-07-29 09:19 UTC, summerlunaa approved these changes

2022-07-29 11:43 UTC, merged