[feat] 일정 단건 조회 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #221
Opened 2022-08-02 09:27 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- 일정 단건 조회 기능 생성
- 일정 단건 조회 문서 테스트 생성
- 일정 단건 조회 서비스, 인수테스트 생성

Closes #207

2022-08-03 02:15 UTC, summerlunaa approved these changes
간단히 리뷰 남겼으니 확인부탁드립니다!

2022-08-03 02:15 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/ScheduleResponse.java
> +        this.categoryId = categoryId;
보통 id의 위치가 어디일까요?(진짜 몰라서 물어보는 것임) categoryId가 id 밑으로 가도 좋을 것 같아요!

2022-08-03 02:15 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
> +        상태코드_200이_반환된다(response);
실제로 응답 바디에 일정이 잘 담겨 오는지는 확인하지 않아도 될까용?

2022-08-03 04:10 UTC, devHudi approved these changes
파랑 코멘트 하나만 반영해주시면 될 것 같아요. Approve 드리겠습니다 감사해요 리버!

2022-08-03 04:10 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/ScheduleResponse.java
> +        this.categoryId = categoryId;
저도 id 밑에 categoryId 가 오면 적절할 것 같아요.

2022-08-03 04:10 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
> +        상태코드_200이_반환된다(response);
@summerlunaa 지금 ScheduleService save 메소드가 ScheduleResponse 대신 생성된 엔티티의 id 만을 반환하고 있어요. https://github.com/woowacourse-teams/2022-dallog/issues/227 요기 이슈를 확인해주세요!

2022-08-03 04:18 UTC, hyeonic requested changes
안녕하세요 리버! 매트입니다. 😀

간단히 코멘트 남겼으니 확인해주세요! 고생하셨습니다.

2022-08-03 04:18 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
> +    }
schedoule 조회의 경우 추가적인 권한 확인은 진행하지 않는 건가요??

2022-08-03 04:18 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/ScheduleResponse.java
> +    }
`Schedule` 입장에서 category에 대한 로직이 필요하지 않는 경우 id를 필드로 가지도록 개선하는 방법도 고려해 보면 좋을 것 같아요! 무의미하게 객체를 가지며 의존성에 대해 신경 쓰는 것 보다 단순히 id만 가지는 방향으로요!

2022-08-03 04:18 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
> +        Long 잘못된_아이디 = 999L;
물론 테스트를 진행할 때 `999L`를 가질 가능성은 희미하지만 `0L`과 같이 절대 존재할 수 없는 아이디로 확인하는 방법은 어떤가요??

2022-08-03 04:40 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/ScheduleAcceptanceTest.java
> +        상태코드_200이_반환된다(response);
아! 감사합니다!

2022-08-03 13:53 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
> +    }
일정에 대한 단건 조회는 일단 권한을 확인하지 않도록 결정했습니다!

2022-08-04 01:17 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
> +    }
숨기고 싶은 개인 일정과 같은 상황을 고려하지 않는 건가요??

2022-08-04 03:09 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/presentation/ScheduleController.java
> +    }
아직 고려되고 있지는 않습니다! 만약 다른 사람과 달력을 공유하는 기능이 만들어진다면 그때 고려할 수 있지 않을까라는 생각이드네요

2022-08-04 04:56 UTC, gudonghee2000 commented
말씀해주신 피드백중
`Schedule`과 `ScheduleResponse`가  
`Category` `Title` ... 순서로 필드를 가지도록 수정해보습니다!

Schedule 단건 조회에 경우 개인의 권한을 확인하는 로직은 아직 구현하지 않았습니다!

2022-08-04 05:50 UTC, hyeonic approved these changes

2022-08-04 05:52 UTC, summerlunaa commented
수정 확인했습니다 굳굳!

2022-08-04 05:59 UTC, merged