[feat] 일정 삭제 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #222
Opened 2022-08-02 10:00 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

일정 삭제 기능을 구현하였습니다.

## 스크린샷

## 주의사항

Closes #209

2022-08-02 10:28 UTC, devHudi commented
아직 리뷰 하시며 안됩니다!!

2022-08-04 07:42 UTC, hyeonic requested changes
안녕하세요 후디! 간단히 코멘트 남겼습니다. 고생하셨습니다 ~

2022-08-04 07:42 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +                .getCategory();
해당 로직은 CategoryService로 위임한 뒤 CategoryService에 대한 의존성을 가지도록 하는 것은 어떨까요??

2022-08-04 07:42 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +    }
Category와 관련된 로직들이 Schedule 내부에 있는 것이 어색하네요!

2022-08-04 08:11 UTC, hyeonic approved these changes

2022-08-04 08:11 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +                .orElseThrow(NoSuchScheduleException::new);
중복된 코드네요! 메서드로 분리해도 좋을 것 같아요!

2022-08-04 08:11 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        categoryService.validateCreatorBy(memberId, category);
해당 로직도 내부로 합칠 수 있을 것 같아요!

2022-08-04 08:11 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
> +        e.printStackTrace();
제거해야 할 것 같아요!

2022-08-04 08:12 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        categoryService.validateCreatorBy(memberId, category);
아니네요 제가 잘못 봤네요 유지해도 좋을 것 같네요!

2022-08-04 08:17 UTC, summerlunaa requested changes
중복을 제거할 수 있을법한 부분에 코멘트 남겼습니다! 확인부탁드려요!!

2022-08-04 08:17 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +                .orElseThrow(NoSuchScheduleException::new);
getById 메서드를 만들어서 중복되는 `findById().orElseThrow()` 구문을 없앨 수 있지 않을까요?

2022-08-04 08:17 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        schedule.changeMemo(request.getMemo());
change 메서드 하나로 바꿀 수 있지 않을까요?

2022-08-04 08:24 UTC, gudonghee2000 approved these changes

2022-08-04 08:24 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        schedule.changeMemo(request.getMemo());
이 부분은 일정 수정 기능에서 반영하도록하겠습니다!

2022-08-04 08:27 UTC, summerlunaa approved these changes
수정사항 확인했습니다!

2022-08-04 08:27 UTC, merged