[refactor] scheduleService.getSchedulesFrom()의 성능을 개선한다.
woowacourse-teams/2022-dallog pull request #313
Opened 2022-08-09 12:12 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- [x] `scheduleRepository.findByCategoryIdAndBetween()` 을 통해서 특정 범위의 일정만 가져오도록 성능 개선
- [x] DateRangeRequest 객체가 LocalDate가 아닌 LocalDateTime을 가지도록 변경
- [x] 월별 일정 조회 관련 테스트 코드 수정  

## 주의사항

Closes #312

2022-08-10 07:52 UTC, summerlunaa requested changes
깔끔하게 해주셨네요! 몇 부분 코멘트 남긴 것만 확인해주세요!

2022-08-10 07:52 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +    }
`findCheckedCategoriedBy` 이런 네이밍이 더 어울리지 않을까요?

2022-08-10 07:52 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
> +                                              final LocalDateTime endDate);
👍

2022-08-10 07:52 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
>          // TODO: 리팩토링 및 성능개선
이제 이 주석은 제거해도 되지 않을까요?

2022-08-10 09:59 UTC, hyeonic requested changes
고생하셨습니다! 간단히 리뷰 남숩니다. 확인해주세요! 🙇‍♂️🌈👍

2022-08-10 09:59 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/common/fixtures/ScheduleFixtures.java
> +    public static final String 매고라_메모 = "매고라가 예정되어 있습니다.";
매고라 굳 👍

2022-08-10 09:59 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +    }
구독 리스트를 받아 처리하는게 `CategoryService`에서 처리하는 것이 조금 어색하네요!

2022-08-10 09:59 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +                        scheduleRepository.findByCategoryIdAndBetween(category, startDate, endDate).stream())
👍

2022-08-10 09:59 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
> +            + "AND s.period.startDateTime <= :endDate "
ON절이 생략되어도 괜찮나요?!

2022-08-10 10:33 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/ScheduleRepository.java
> +            + "AND s.period.startDateTime <= :endDate "
비교하는 값이 있을때 ON절을 사용하는것 같아요 보통 JOIN만 사용하는것 같아요!
EX) 
``` 
MEMBER M INNER JOIN TEAM T ON M.TEAM_ID=T.ID
```

2022-08-10 10:54 UTC, devHudi requested changes
안녕하세요, 리버! JPQL로 일정 조회 API가 최적화 된 것 같네요! 몇가지 코멘트 남겼으니 확인 부탁드려요!

2022-08-10 10:54 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +    }
`findCategoriesBy` 이름에 체크된 구독만 가져온다는 뉘앙스가 있다면 더 좋을 것 같긴한데, 사실 저도 좋은 아이디어가 떠오르지는 않네요..! 그냥 의견입니다!

2022-08-10 10:54 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/DateRangeRequest.java
>      }
현재 일정 조회 API URL은 `/api/members/me/schedules?startDate=2022-07-31&endDate=2022-09-03` 인데, `DATE_FORMAT`이 `yyyy-MM-dd'T'HH:mm` 으로 변경되었네요! API 명세가 변경되는 것 일까요?

2022-08-11 03:39 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/request/DateRangeRequest.java
>      }
`yyyy-MM-dd'T'HH:mm` 형식으로 값을 보내주는게 프론트 코드에서 간단하게 해결된다고 해주셔서 `yyyy-MM-dd'T'HH:mm` 형식의 값을 받도록 변경하였습니다!
API명세도 변경하였습니다!

2022-08-11 04:14 UTC, hyeonic approved these changes

2022-08-11 04:16 UTC, summerlunaa approved these changes

2022-08-11 04:23 UTC, devHudi approved these changes

2022-08-11 04:23 UTC, merged