[feat] 시작 페이지 콘텐츠를 작성한다.
woowacourse-teams/2022-dallog pull request #332
Opened 2022-08-10 10:58 UTC by jhy979

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- [x]  콘텐츠 작성
- [x] 로그인 페이지 삭제
## 스크린샷
![image](https://user-images.githubusercontent.com/32920566/183884904-2b29f0c4-0459-441e-9855-8ba77a2fb596.png)
![image](https://user-images.githubusercontent.com/32920566/183885022-77e56b3e-942e-4ea4-acec-7bf9e1325d05.png)

## 주의사항
useIntersect를 사용하여 secondSection의 애니메이션을 구현했습니다.
Closes #260

2022-08-10 10:59 UTC, hyeonic commented
너무 이뿌네여.. 9️⃣ 👍

2022-08-10 10:59 UTC, devHudi commented
넘모 이뻐요

2022-08-11 03:28 UTC, daaaayeah requested changes
농협은행~ 나인 고생하셨어요 ✨
코멘트 확인 부탁드립니다!

2022-08-11 03:28 UTC, daaaayeah commented on frontend/src/pages/StartPage/StartPage.tsx
> +                <p css={loginText}>Google 계정으로 계속하기</p>
```suggestion
                <p css={loginText}>Google 계정으로 로그인하기</p>
```
로그인 페이지에선` 계속하기`가 적절하다고 생각했었는데 여기서는 `로그인`이라는 걸 명시해도 좋을 것 같아요~!

2022-08-11 03:28 UTC, daaaayeah commented on frontend/src/pages/StartPage/StartPage.tsx
> +  console.log(firstMethod, secondMethod);
```suggestion
```
👀🔫

2022-08-11 03:28 UTC, daaaayeah commented on frontend/src/pages/StartPage/StartPage.styles.ts
> +  position:relative;
```suggestion
  position: relative;
```

2022-08-11 03:28 UTC, jhy979 commented on frontend/src/pages/StartPage/StartPage.tsx
> +  whiteTextStyle,
엄청많죠 ㅎㅎ

2022-08-11 03:28 UTC, jhy979 commented on frontend/src/pages/StartPage/StartPage.tsx
> +                <p css={loginText}>Google 계정으로 계속하기</p>
아 그렇네요 그게 더 명확할 것 같아요.

2022-08-11 03:46 UTC, daaaayeah approved these changes
9️⃣ 좋습니다 반복 로직에 대해서는 고민해 보고 같이 리팩토링해봐요~!

2022-08-11 03:48 UTC, merged