[feat] 회원 탈퇴 API를 구현한다.
woowacourse-teams/2022-dallog pull request #335
Opened 2022-08-10 12:07 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

회원 탈퇴 기능을 구현하였습니다.

## 스크린샷

## 주의사항

Closes #334

2022-08-10 12:09 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +    }
매트의 이야기대로 양방향 참조 사용을 줄이는 것이 좋은 것 같아서, 위와 같이 순차적으로 연관된 엔티티를 제거해주었습니다. 다만, 이 메서드를 위해 `SubscriptionRepository`와 `CategoryRepository`에 대한 의존성이 추가로 생겼습니다.

이후 유저 회원가입에 관한 서비스를 따로 분리한다면, 이 친구도 그 서비스에 포함시켜도 자연스러울 것 같네요! 의견 부탁드립니다.

2022-08-11 04:21 UTC, gudonghee2000 reviewed
안녕하세요 후디! 작성해주신 회원탈퇴 기능 잘보았어요!!👍👍
몇가지 코멘트 남겼습니다 확인부탁드려요~

2022-08-11 04:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +        this.subscriptionRepository = subscriptionRepository;
`CategoryService`를 의존하게 되는것에 대해서는 추후 고민을 해봐야겟네요!

2022-08-11 04:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +    }
저도 유저 회원가입과 관련된 `Service`에 포함시켜도 좋을것 같다는 생각이 들어요!

2022-08-11 04:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/presentation/MemberController.java
> +        memberService.delete(loginMember.getId());
파라미터에 final 키워드가 추가되면 좋을것 같아요!

2022-08-11 04:21 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
> +
이부분을 인수관련 fixture로 빼도 좋을것 같아요!

2022-08-11 04:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
> +
이부분은 삭제하면 좋을것 같아요!

2022-08-11 05:36 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +    }
RegisterService에 포함시키면 Repository로 해결할 수 있는 문제를 서비스를 의존해서 해결해야한다는 단점이 있을 것 같긴 하네요! 같이 고민해보면 좋을 것 같습니다.

2022-08-11 05:38 UTC, summerlunaa approved these changes
리버가 리뷰 꼼꼼하게 잘 해주셔서 저는 크게 남길 코멘트가 없네요!
approve 하겠습니다. RegisterService로 로직을 이동하는 부분은 같이 한 번 얘기해보면 좋을 것 같습니다!

2022-08-11 05:56 UTC, hyeonic requested changes
대부분 리뷰 리버가 잘 남겨주셔서 개선하면 좋겠는 부분 남겼습니다! 확인해주시고 반영해주세요! 고생하셨습니다 😃

2022-08-11 05:56 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
> +    void deleteAllByMemberId(Long memberId);
`deleteAll`이라는 표현은 모든 데이터를 지우는 것 같은 느낌이 드네요! `deleteByMemberId`는 어떤가요??

Spring 공식 문서에서도 아래와 같은 표현을 사용하고 있네요!

<img width="528" alt="image" src="https://user-images.githubusercontent.com/59357153/184071784-f2b4a23c-803f-4770-9b07-d7d48ddaf8cb.png">

[Spring 공식 문서](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#reference)

2022-08-11 05:56 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
> +    void deleteAllByMemberId(Long memberId);
`JpaRepository`의 실제 구현체인 SimpleJpaRepository에 작성된 `deleteAllById()` 메서드의 경우 매개 변수로 Collection으로 ids가 전달되고 있습니다! 

```java
@Repository
@Transactional(readOnly = true)
public class SimpleJpaRepository<T, ID> implements JpaRepositoryImplementation<T, ID> {
        ...
	@Override
	@Transactional
	public void deleteAllById(Iterable<? extends ID> ids) {

		Assert.notNull(ids, "Ids must not be null!");

		for (ID id : ids) {
			deleteById(id);
		}
	}
        ...
}
```

2022-08-11 06:08 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +    }
@summerlunaa 아예 이 메소드 자체를 MemberService에서 RegisterService 로 옮겨도 괜찮을 것 같아요.

2022-08-11 06:08 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +        this.subscriptionRepository = subscriptionRepository;
아마 이 로직이 RegisterService로 이동하면 자연스럽게 해소되지 않을까 생각합니다!

2022-08-11 06:09 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/presentation/MemberController.java
> +        memberService.delete(loginMember.getId());
앗 놓쳤네요 감사합니다!

2022-08-11 06:11 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
> +
감사합니다 ㅎㅎ

2022-08-11 06:20 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
> +    void deleteAllByMemberId(Long memberId);
맞는 것 같네요! `All` 을 제거하였습니다!

2022-08-11 06:23 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
> +
분리했습니다!

2022-08-11 07:32 UTC, gudonghee2000 approved these changes
후디 수정해주신 부분 모두 보았습니다!
바로 approve 하겠습니다!

고생하셨습니다~

2022-08-11 10:43 UTC, hyeonic approved these changes
고생하셨습니다 후리~ 👍

2022-08-11 10:43 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/presentation/MemberController.java
> +    @DeleteMapping
`me` 키워드만 추가하면 될 것 같아요!

2022-08-12 04:09 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/presentation/MemberController.java
> +    @DeleteMapping
추가 했슴다~!

2022-08-12 04:17 UTC, merged