[feat] 일정 등록 기능의 예외를 추가한다.
woowacourse-teams/2022-dallog pull request #44
Opened 2022-07-11 12:15 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

-[x] 도메인 규칙 추가
    - [x] Title, Memo
- [x] 월별 일정 조회 기능 엣지 케이스 테스트 코드 추가

## 주의사항

Closes #15

2022-07-11 16:57 UTC, hyeonic reviewed
안녕하세요 리버! 매트입니다 😀

값 타입 및 DB 컨벤션 관련해서 간단히 코멘트 남겼습니다! 확인 해주시고 논의할 내용 나눈 뒤 적절히 반영하면 좋을 것 같아요! 고생 하셨습니다 👍

2022-07-11 16:57 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/schedule/domain/Memo.java
> +public class Memo {
값 객체의 경우 불변을 보장하도록 작성하는 것이 좋다고 하네요! 관련해서 수정과 관련된 로직이 추가될 경우 `setter`와 같은 수정 메서드의 사용을 제한하고 해당 값 객체를 사용하는 외부의 엔티티에서 변경을 진행할 때 new 키워드를 활용하여 새롭게 생성한 뒤 변경하는 방식을 고려해야 할 것 같아요!

2022-07-11 16:57 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/schedule/domain/Memo.java
> +    private String value;
DB의 제약 조건을 위해 `@Column`에 `length = 255`를 추가하면 더욱 좋을 것 같아요!

2022-07-11 16:57 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/schedule/domain/Memo.java
> +public class Memo {
당장에 사용할 예시가 떠오르지 않지만 값 타입 사이의 비교를 진행할 때는 식별자가 존재하지 않기 때문에 존재하는 필드가 모두 같으면 같은 것으로 봐야 할 것 같아요! 즉 `equals & hashCode`가 적절히 오버라이딩 되야 한다고 판단합니다!

2022-07-11 16:57 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/schedule/domain/Title.java
> +    @Column(name = "title", length = 20, nullable = false)
DB 테이블명의 경우 대문자를 활용하고 있는데 컬럼명은 소문자로 명시해두었네요! 관련해서 어떤식으로 통일할지 이야기 나눠보면 좋을 것 같습니다!

2022-07-12 00:22 UTC, summerlunaa requested changes
리버~ 빠르게 구현 완료해주셨네요ㅎㅎ 테스트까지 꼼꼼하게👍👍

코드를 보다가 든 생각인데요, 앞으로 계속 새로운 객체가 추가될텐데 검증 로직이 없는 필드는 거의 존재하지 않을 것 같아요. 그럼 필드가 생길때마다 모든 필드를 별도의 객체로 분리해서 관리하는 게 맞나?하는 의문이 들었습니다. 오늘 백엔드 크루들끼리 이 부분에 대해서 한번 얘기 나눠보면 좋을 것 같아요. 일단 request change 날립니다.

2022-07-12 00:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/schedule/domain/ScheduleRepositoryTest.java
> +    @DisplayName("시작일시와 종료일시를 전달할 때 일정의 시작날짜가 시작일시와 같으면 조회된다.")
와우 꼼꼼한 테스트 좋습니다👍

2022-07-13 00:45 UTC, summerlunaa commented
아 그리고 예외케이스에 대한 인수테스트가 추가되지 않았네요🥲 exception handler도 구현해야할 것 같습니다!!

2022-07-13 03:43 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/schedule/domain/Title.java
> +    @Column(name = "title", length = 20, nullable = false)
헷갈리지 않게 모두 소문자 및 snake_case로 통일하는 것 제안드립니다 🤚

2022-07-13 03:50 UTC, devHudi approved these changes
안녕하세요 리버! 리뷰에 달린 논의사항은 어제 회의 때 대부분 확정된 것 같아 이에 대한 코멘트는 생략할게요! 기간에 대한 일정 필터링에 대한 테스트 케이스가 꼼꼼하게 되어있어서 좋은 것 같아요 👍 수정이 필요한 부분은 파랑과 매트가 Request Changes로 잘 남겨두었으니, 저는 여기서 Approve 드릴게요!

2022-07-13 14:56 UTC, hyeonic commented
아직 fetch & rebase가 안되서 프론트와 백엔드 코드가 뒤섞여 있네요🥲 관련해서 이야기 좀 더 나눠보고 PR 마감하면 좋을 것 같아요! 조금만 더 힘냅시다 화이팅! 🌈

2022-07-14 01:51 UTC, hyeonic approved these changes

2022-07-14 01:51 UTC, devHudi approved these changes
LGTM 👍

2022-07-14 01:52 UTC, merged