[feat] 카테고리 생성 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #48
Opened 2022-07-13 08:04 UTC by summerlunaa

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
카테고리 생성 기능을 구현한다.

Closes #34

2022-07-13 13:36 UTC, devHudi requested changes
파랑! 코드가 깔끔해서 술술 잘 읽혔어요! 저희끼리 정했던 컨벤션에도 잘 맞는 코드인 것 같아요 👍👍 사소하게 수정하면 좋아보이는 것들을 몇가지 코멘트 달았어요. 고생 많으셨습니다 😎

2022-07-13 13:36 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +        return ResponseEntity.created(URI.create("/api/categories" + id)).build();
```suggestion
        Long id = categoryService.save(request);
        return ResponseEntity.created(URI.create("/api/categories/" + id)).build();
```

Location에서 `/` 가 빠진 것 같아요!

2022-07-13 13:36 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +public class Category {
```suggestion
@Table(name = "categories")
@Entity
public class Category {
```

제 생각에는 Category 클래스를 가장 잘 나타내는 어노테이션은 `@Entity` 인 것 같은데, 위와 같이 변경하는 것은 어떨까요?

2022-07-13 13:36 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
> +    }
이제 재사용성이 증가했네요! 너무 좋습니다 👍👍

2022-07-13 13:36 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/category/service/CategoryServiceTest.java
> +        assertThat(id).isNotNull();
```suggestion
        // given
        String name = "BE 공식일정";
        CategoryCreateRequest request = new CategoryCreateRequest(name);

        // when
        Long id = categoryService.save(request);

        // then
        assertThat(id).isNotNull();
```

(많이 사소하지만 😅) 공백을 하나 추가할까요?

2022-07-13 14:49 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +public class Category {
저도 그게 맞는 것 같아서 고민하다가 일단 `Schedule`에 달려있는 순서로 적었네요. 수정하겠습니다~ 내일 리버한테도 알려주세요.

2022-07-13 14:49 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +public class Category {
아하 그렇군요! 감사합니다!

2022-07-13 14:51 UTC, hyeonic requested changes
안녕하세요 파랑! 매트입니다 😃

대부분 잘 구현해주셔서 크게 리뷰 남길 곳은 없네요! 컨벤션 부분만 수정되면 될 것 같아요! 고생하셨습니다 😃

2022-07-13 14:51 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +        return ResponseEntity.created(URI.create("/api/categories" + id)).build();
매의 눈 후디... 👍

2022-07-13 14:51 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +    private Long id;
id도 `@Column`이 누락된 것 같아요!

2022-07-13 14:51 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +    private LocalDateTime createdAt;
추후 `Auditing`을 통한 개선 예정인가요?! 기대가 됩니다 ㅎㅎ

2022-07-13 14:51 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +    }
꼼꼼한 검증 👍

2022-07-13 14:51 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
> +    }
트랜잭션 처리 👍 

`save`의 리턴 값에 대해서도 논의를 통해 통일하면 좋을 것 같아요! e.g. 도메인 반환 vs dto 반환 vs id 반환

2022-07-13 14:51 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
> +    }
너무 깔끔하네요 ㅎㅎ

2022-07-13 14:53 UTC, jhy979 commented on backend/src/main/java/com/allog/dallog/category/controller/CategoryController.java
> +        return ResponseEntity.created(URI.create("/api/categories" + id)).build();
와 진짜 꼼꼼 👍

2022-07-13 15:19 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/domain/Category.java
> +    private LocalDateTime createdAt;
후우 기대 plz

2022-07-13 15:19 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
> +    }
good 논의해 보시죠

2022-07-13 15:20 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/category/service/CategoryService.java
> +    }
좋은 논의거리네요 굳굳

2022-07-13 15:28 UTC, devHudi submitted a review, later dismissed
변경해주신 것 확인했습니다!! Approve 할게요 👍👍

2022-07-13 15:45 UTC, hyeonic approved these changes

2022-07-14 03:12 UTC, hyeonic approved these changes

2022-07-14 03:12 UTC, devHudi approved these changes

2022-07-14 03:12 UTC, merged