[feat] 카테고리 조회 컴포넌트를 구현한다.
woowacourse-teams/2022-dallog pull request #55
Opened 2022-07-14 10:03 UTC by jhy979

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- [x] 검색창 레이아웃
- [x] 카테고리 테이블 생성 
- [x] 무한 스크롤 구현

## 스크린샷
![image](https://user-images.githubusercontent.com/32920566/178957415-00cd40b1-3f02-4f3c-bff1-58e3d35d119a.png)

Closes #42

2022-07-15 06:26 UTC, hyeonic submitted a review, later dismissed
너무 이쁘네여 👍 고생하셨습니다 😀

2022-07-15 22:31 UTC, daaaayeah requested changes
나인~! 좋은 아침이에요 🌈
코드 잘 봤습니다 빠르게 뚝딱뚝딱 구현해 주셨네요 ⚡️

리뷰가 조금 늦었는데 기다려주셔서 감사합니다
잘 구현해 주셔서 간단한 리뷰가 대부분이네요!

확인 부탁드리고 궁금한 게 있으시다면 언제든 연락 주세요 🏃🏻‍♀️

2022-07-15 22:31 UTC, daaaayeah commented on frontend/src/pages/CategoryPage/CategoryPage.tsx
> +    ({ pageParam = 1 }) => categoryApi.get(pageParam, API.CATEGORY_GET_SIZE),
어느 컴포넌트에서 데이터를 받아오면 좋을지 찬찬히 고민해 봅시다
요건 얘기를 나눴던 부분이니까 todo로 넘겨도 좋을 것 같아요 🙃

2022-07-16 01:58 UTC, daaaayeah approved these changes
소소한 코멘트 하나 남겼으니 확인 부탁드립니다
답변 남기시지 않은 코멘트들도 나중에 같이 이야기해 봐요~!
고생하셨어요 9️⃣🚀

2022-07-16 01:58 UTC, daaaayeah commented on frontend/src/components/CategoryItem/CategoryItem.styles.ts
> +  justify-content:space-around;
사소한 부분이지만 아직 리뷰 반영이 안된 것 같아서 확인 한번 부탁드릴게요~!

2022-07-16 02:18 UTC, daaaayeah commented on frontend/src/components/CategoryList/CategoryList.tsx
> +      </div>
오호 그렇군요~! semantic 관점에서 생각했을 때 과연 적절한가 의문이 들어 여쭤봤습니다
semantic을 지켜야 한다고 말하는 개발자가 많은 반면에 실제로는 지키지 않는 서비스를 저도 많이 봤어요 🤔
지금은 div 사용으로 넘어가더라도 인지는 하고 있는 게 좋을 것 같습니다!

2022-07-16 02:28 UTC, daaaayeah commented on frontend/src/mocks/handlers.ts
> +    const size = parseInt(req.url.searchParams.get('size') as string);
> 현재는 categoryApi.endpoint 관련 요청이 get 요청 하나이고 이에 대해서는 page와 size에 대한 number 타입 지정을 해줬기 때문에 당장은 page와 size가 없는 경우는 없을 거라고 생각합니다.

비슷하게 생각해서 이 리뷰를 남길까 말까 고민 많이 했습니다
어디까지 어떻게 커버하는 게 좋을지 🥲 타입스크립트는 여전히 어렵네요...!

> 추가적으로 저는 API mocking하는 단에서는 강력한 ts를 적용하는 것이 전력 낭비라는 생각이 조금 있는데 티거는 어떻게 생각하시나요?

모킹이다 보니 아무래도 프로젝트 자체보다는 타입스크립트를 학습하는 측면에서 좋다고 생각합니다
이것도 찬찬히 이야기 나눠봐요~!

2022-07-16 02:30 UTC, daaaayeah approved these changes

2022-07-16 02:30 UTC, daaaayeah commented on frontend/src/components/CategoryItem/CategoryItem.styles.ts
> +  justify-content:space-around;
```suggestion
  justify-content: space-around;
```

앗 여기는 prettier 적용이 안되는 걸까요?!
이 PR은 여기서 머지하고 이건 다음에 반영해도 좋을 것 같아요~!

2022-07-16 05:36 UTC, daaaayeah approved these changes

2022-07-16 05:40 UTC, merged