[feat]회원 탈퇴 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #556
Opened 2022-09-07 07:35 UTC by jhy979

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- [x] 회원 탈퇴 기능 구현

## 스크린샷
![image](https://user-images.githubusercontent.com/32920566/188787273-aa36617e-c31a-455d-ae1d-ea0aac363306.png)

Closes #537

2022-09-08 05:55 UTC, daaaayeah requested changes
9️⃣✨ 리뷰가 조금 늦었죠 죄송합니다 🥲
코드 확인했습니다 코멘트 읽고 소소하게 수정 부탁드려요~!
덕분에 탈퇴도 가능한 달록이 되었네요 👍🏻
고생하셨습니다 생일 축하해요~! 🎂

2022-09-08 05:55 UTC, daaaayeah commented on frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
> +    location.reload();
오 탈퇴 처리 좋네요 👍🏻

2022-09-08 05:55 UTC, daaaayeah commented on frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
> +        탈퇴를 원하시면{' '}
{' '} 요건 띄어쓰기 때문에 넣어주신 건가요?!

2022-09-08 05:55 UTC, daaaayeah commented on frontend/src/constants/validate.ts
> +  WITHDRAWAL: '달록 탈퇴',
오호 validation string 너무 잘 만들고 활용하고 계시네요~!

2022-09-08 05:55 UTC, daaaayeah commented on frontend/src/validation/index.ts
> +};
```suggestion
const validateWithdrawalCondition = (value: string) => value === VALIDATION_STRING.WITHDRAWAL;
```
요렇게 줄여볼까요~?

2022-09-08 05:55 UTC, daaaayeah commented on frontend/src/validation/index.ts
> +export {
export 위에 개행 하나만 부탁드림다 🫠

2022-09-08 09:04 UTC, jhy979 commented on frontend/src/validation/index.ts
> +};
넵 좋습니다

2022-09-08 09:04 UTC, jhy979 commented on frontend/src/validation/index.ts
> +export {
개행이 안들어가있군요 ㅎ.ㅠ

2022-09-08 09:05 UTC, jhy979 commented on frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
> +    location.reload();
기존에 존재하던 로직 그대로 사용하고 있어요!

2022-09-08 09:17 UTC, daaaayeah commented on frontend/src/components/WithdrawalModal/WithdrawalModal.tsx
> +        탈퇴를 원하시면{' '}
움 무슨 차이가 있을지 생각해보고 찾아봤는데요 🤔
[이 이슈](https://github.com/facebook/react/issues/15432)에서는 `&nbsp;`가 검색하기에 편하다는 장점이 있었다네요!
여기서는 `{' '}`나 `&nbsp;`나 차이가 없을 것 같아요~!

2022-09-10 14:14 UTC, daaaayeah approved these changes
깔-끔 ✨ 추석인데 고생 많으셨습니다
맛있는 거 많이 드셨나요~?
보름달 같은 얼굴로 만나요 🌕

2022-09-10 14:17 UTC, merged