[feat] Flyway를 도입하여 데이터베이스 마이그레이션 환경을 구축한다.
woowacourse-teams/2022-dallog pull request #557
Opened 2022-09-08 07:26 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

데이터베이스 마이그레이션을 위한 Flyway를 적용하였습니다.

Flyway와 관련된 글을 https://dallog.github.io/dallog-flyway/ 에 작성해두었습니다. 세미나때도 이야기 드릴게요!

앞으로 엔티티 구조가 수정된다면, 반드시 `resources/db/migration` 디렉토리에 마이그레이션 스크립트를 새로운 버전으로 추가해주셔야합니다.

## 스크린샷

## 주의사항

Closes #547

2022-09-08 07:40 UTC, hyeonic requested changes
안녕하세요 후디! 매트입니다 😃

블로그에 깔끔하게 정리되어 있어서 쉽게 파악할 수 있었어요! 다만 서브모듈 쪽에 commit이 제대로 반영되지 않은 것 같아서 다시 한번 확인 부탁드립니다! 고생하셨습니다!

2022-09-08 15:39 UTC, devHudi commented on backend/build.gradle
> +    implementation 'org.flywaydb:flyway-mysql'
@hyeonic 맞습니다. 프로덕션 서버 MySQL 버전이 아마 8.0.33 일 거예요.

2022-09-10 06:31 UTC, summerlunaa approved these changes
flyway 도입 good! 네오의 허락만 받으면 될듯합니다.

2022-09-13 06:57 UTC, gudonghee2000 approved these changes
안녕하세요 후디! 적용해주신 flyway 잘보았습니다👍
작성해주신 블로그글과 디스코드 글 덕분에 
flyway에 대해 이해할수 있었습니다😊

2022-09-14 05:42 UTC, closed without merging