[feat] 종일 버튼을 개선한다.
woowacourse-teams/2022-dallog pull request #568
Opened 2022-09-10 15:13 UTC by daaaayeah

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- [x] 일정 추가 모달
- [x] 일정 수정 모달

## 스크린샷

### 일정 추가 모달

<img width="1624" alt="일정 추가 모달 종일 체크" src="https://user-images.githubusercontent.com/52729559/189489277-7e51b8bc-279d-4105-85ad-df8fc7f8cbbf.png">
<img width="1624" alt="일정 추가 모달 종일 체크 X" src="https://user-images.githubusercontent.com/52729559/189489290-821c75ae-498b-424f-b64f-0341f39c19d4.png">

### 일정 수정 모달

<img width="1624" alt="일정 수정 모달 종일 체크" src="https://user-images.githubusercontent.com/52729559/189489238-d61953c9-7529-447e-83d8-68fac5517951.png">
<img width="1624" alt="일정 수정 모달 종일 체크 X" src="https://user-images.githubusercontent.com/52729559/189489236-a955f991-3c98-4dbf-87e4-69a972fae894.png">

## 주의사항

1. 미션... 이후로 아이콘을 최대한 사용하지 않는 게 성능에 좋을 거라고 판단하여 아이콘을 사용하지 않았습니다.
2. Fieldset 공통 컴포넌트와 다른 부분이 많아 이를 사용하지 않았습니다.
3. `accent-color` 속성을 사용해서 체크박스를 디자인하니 `YELLOW_500` 색상을 사용하는 경우에 체크가 회색으로 보이더라고요. 그래서 체크가 흰색으로 보이는 `ORANGE_500` 색상을 사용하였습니다. -> 예뻐 보이진 않아요 🥲 체크박스 디자인에 대한 피드백 부탁드립니다!

Closes #542

2022-09-11 00:42 UTC, jhy979 requested changes
코드  상으로는 괜찮은데 UI에 관한 의견이 있어요.

저장버튼은 노란색인데 체크박스가 오렌지색으로 처리되는 부분이 많이 어색하다고 느껴집니다

YELLOW_500으로 처리하고 체크가 회색으로 처리되는것이 현재보다 더 어색한가요?

++ 아 그리고 저는 트리쉐이킹을 통해 리액트 아이콘 라이브러리의 용량 감소를 보고 아이콘을 써도 괜찮겠다는 생각을 했어요

2022-09-11 14:07 UTC, daaaayeah commented
> 저장버튼은 노란색인데 체크박스가 오렌지색으로 처리되는 부분이 많이 어색하다고 느껴집니다

그쵸 저도 똑같이 느끼고 있습니다 의견 감사해요~!

> YELLOW_500으로 처리하고 체크가 회색으로 처리되는것이 현재보다 더 어색한가요?

둘 다 어색하게 느껴집니다 아무래도 체크박스를 커스텀 하는 쪽으로 수정하는 게 좋겠어요 🙃

> ++ 아 그리고 저는 트리쉐이킹을 통해 리액트 아이콘 라이브러리의 용량 감소를 보고 아이콘을 써도 괜찮겠다는 생각을 했어요

오 그쵸 저도 아이콘 써도 괜찮겠네 생각했어요~!
그래도 가장 좋은 방법은 사용하지 않아도 되면 사용하지 않는 거라고 생각했습니다

2022-09-12 12:30 UTC, daaaayeah commented
사랑하는 YELLOW_500 데려왔습니다 🤭
어쩌면 css가 귀찮아서 `accent-color`로 해버리려고 했던 건 아닌지 반성 한번 하고 갑니다
역시 노+흰 체크박스가 가장 보기 좋네요 👍🏻

 ### 일정 추가 모달

<img width="812" alt="달록 일정 추가 모달 체크 X" src="https://user-images.githubusercontent.com/52729559/189652919-3d6e1712-6ca7-4b29-aba1-81361ee8aa29.png">
<img width="790" alt="달록 일정 추가 모달 체크 O" src="https://user-images.githubusercontent.com/52729559/189652897-16bde896-2559-4949-94ff-f50cedb2b7ac.png">

### 일정 수정 모달

<img width="812" alt="달록 일정 수정 모달 체크 X" src="https://user-images.githubusercontent.com/52729559/189653145-39d2056b-b35d-4749-99a8-20ccb1b7ba2e.png">
<img width="812" alt="달록 일정 수정 모달 체크 O" src="https://user-images.githubusercontent.com/52729559/189653062-c2626b58-026a-4f69-83c4-1fec0330861f.png">

2022-09-13 01:23 UTC, jhy979 approved these changes
좋습니다! 체크박스가 훨씬 보기 좋아졌네요.😉😉

2022-09-13 01:35 UTC, merged