[refactor] REST docs의 코드 스타일을 통일한다.
woowacourse-teams/2022-dallog pull request #570
Opened 2022-09-11 07:00 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

### identifier 통일

```java
mockMvc.perform( ... )
// ...
                .andDo(document("subscription/save", // <-- 여기
```

identifier란 위와 같이 MockMvc `andDo(document())` 에 전달하는 REST Docs 문서 조각에 대한 식별자입니다. 이에 대한 통일이 이뤄지지 않았는데, 아래 형식으로 통일하려 합니다.

```
컨트롤러 이름/컨트롤러 메소드 이름/{설명}
```

`컨트롤러 이름`과 `컨트롤러 메소드 이름` 은 필수고 `설명` 은 선택 사항입니다. _'어떠한 이유로 실패했다'_, 혹은 _'어떤 기준으로 필터링 한다'_ 등 API에 대한 부연설명이 필요한 경우 작성해주시면 됩니다.

## 스크린샷

## 주의사항

Closes #560

2022-09-11 11:35 UTC, hyeonic requested changes
안녕하세요 후디! 매트입니다 😃

관련해서 전부 살펴 보시느라 너무 고생하셨습니다. 한 가지 궁금한 점이 PR description을 살펴보면 `Asciidoc 형식 통일`에 대한 내용이 담겨 있는데, commit에는 따로 반영이 안되어 있는 것 같더라구요! 
확인해주시면 감사하겠습니다 🙇‍♂️

2022-09-11 11:35 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
> +                .andDo(document("categories/findAllByName/allByNoName",
`allByNoName`은 어떤 부연 설명인가요?? name 없이 전달한다는 의미 일까요??

2022-09-11 12:22 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/presentation/CategoryControllerTest.java
> +                .andDo(document("categories/findAllByName/allByNoName",
죄송함다 다 완성하지 않은 상태에서 PR을 먼저 생성했어요. 지금 확인해보시면 adoc 파일도 모두 개선됐습니다.

그리고 코멘트 남겨주신 부분에 대해서 말씀드리자면, name 을 전달하지 않고 모든 카테고리를 불러온다는 의미입니다. 저희가 따로 전체 조회 API를 만들지 않고, 이름 필터링을 위한 파라미터에 공백을 전달하여 전체 결과를 받아오고 있기 때문입니다.

2022-09-11 16:33 UTC, summerlunaa approved these changes
우와 후디! 이걸 전부 수정하기 힘들었을 것 같은데 증맬 수고했군요 ㅠ_ㅠ
`컨트롤러 이름/컨트롤러 메소드 이름/{설명}`
요 형식으로 가니 가독성도 올라가고 통일성도 있고 좋네요ㅎㅎ 진짜 수고하셨습니당

2022-09-11 16:33 UTC, summerlunaa commented on backend/src/docs/asciidoc/auth.adoc
> +include::{snippets}/auth/generateToken/failByResourceServerError/http-response.adoc[]
에러 케이스인 경우 응답만 보여주도록 바뀌었네요! 맞나요?

2022-09-12 15:30 UTC, devHudi commented on backend/src/docs/asciidoc/auth.adoc
> +include::{snippets}/auth/generateToken/failByResourceServerError/http-response.adoc[]
넵 맞습니다. 대신 Request Fields 등에 유효한 값의 범위를 명확히 명시하면 더 좋을 것 같아요.

2022-09-13 07:15 UTC, gudonghee2000 reviewed
안녕하세요 후디! 수정해주신 Controller 테스트 코드와 adoc 파일들 잘보았습니다!
변경점이 많았을텐데.. 정말 고생하셨습니다👍😊
한가지 수정하면 좋을 부분과 의견 하나 남겼습니다!

adoc문서에서 예외 발생 경우에 `~때` 또는 `~할 경우`라는 내용이 괄호에 있는데요!
이부분을 `~때` 또는 `~할 경우` 하나로 통일해도 좋을것 같아요~

2022-09-13 07:15 UTC, gudonghee2000 commented on backend/src/docs/asciidoc/external-calendar.adoc
> +==== HTTP Response
`자신의 외부 캘린더 중복 저장 시 예외 발생`을 `자신의 외부 캘린더 저장(중복 저장하는 경우)`로 하고 `response`만 남길수 있을것 같아요!

2022-09-15 05:55 UTC, hyeonic approved these changes
재미 없는 작업 이었을 텐데 고생하셨습니다 👍

2022-09-16 04:04 UTC, merged