[refactor] 회원가입 및 회원 탈퇴 시 발생하는 순환 참조 구조를 개선한다.
woowacourse-teams/2022-dallog pull request #572
Opened 2022-09-11 12:31 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

현재 달록 회원가입을 위해서는 아래와 같은 절차를 따릅니다.
 * 사용자는 인가 코드 + redirect uri를 활용하여 달록 자체 토큰 생성 API를 요청한다.
 * 소셜 로그인을 진행한 뒤 id token에서 회원 정보를 변환한다. (OAuthClient)
 * 존재하는 회원이면 조회, 존재하지 않는 회원이면 회원가입을 진행한다 (AuthService)
 * 회원가입과 동시에 내 일정 카테고리 생성 및 구독을 진행한다. (MemberService, MemberSaveEvent)

회원가입 시 같은 Transaction으로 내 일정 카테고리와 구독이 함께 진행되어야 합니다. 이전에 `RegisterService`라는 상위 서비스 계층에서 이러한 역할을 담당하였습니다. 하지만 저는 이것이 온전한 MemberService의 책임과는 멀다고 느껴졌습니다. 결국 우리가 Member를 생성할 때 바라는 것은 카테고리와 구독이 모두 생성되는 것입니다.

그러한 책임을 member 생성 시점에 `MemberAfterEvent` 인터페이스를 통해 개선 하였습니다. 이러한 인터페이스를 통해 member 생성 이후 행위를 작성한 `MemberSaveAfterEvent` 구현체가 담당하여 주입받는 형태를 고민 하였습니다. 동시에 이전에 `AuthService`가 가지고 있던 `RegisterService`에 대한 의존도 제거되었습니다.

현재는 다른 기능 때문에 여전히 상호 의존에 대한 위험성은 존재 하지만 `회원가입에 대한 기능`만 보았을 때, 확실히 개선된 것을 확인할 수 있습니다. 연습을 통해 축약한 개선 코드는 [circular-reference repository](https://github.com/hyeonic/blog-code/blob/main/circular-reference/src/main/java/io/github/hyeonic/circularreference/member/MemberService.java)에서 확인할 수 있습니다.

무조건 적용하기 위한 용도의 PR이 아닙니다. 충분히 검토 해주시고, 더 좋은 방향이나 개선 사항에 대해 나누기 위한 용도입니다. 편하게 리뷰 남겨주시면 감사하겠습니다 😃

## 스크린샷

## 주의사항

Closes #565 #571

2022-09-11 13:08 UTC, devHudi requested changes
안녕하세요, 매트~
이벤트 리스너를 구현한다는 접근이 굉장히 신선한 것 같아서 재밌게 읽었습니다.

몇 가지 궁금한게 있습니다.
1. MemberEvent와 AuthEvent를 구분하는 이유가 무엇일까요? 현재 구조에서 도메인별로 이벤트 리스너를 나눠놓는 것이 필요한 이유가 궁금합니다!
2. Before와 After로 이벤트 구현체를 구분하셨는데, 이 이유가 궁금합니다. 더 나아가 각각의 이벤트를 모두 독립된 구현체로 설계한 이유가 궁금합니다. 간단하게 한다면, 
```java
public class EventListener {
  
  public onMemberCreated() {
    // 기본 카테고리 생성, 기본 카테고리 구독 생성 ...
  }

  public onMemberDeleted() {
    // 관련된 카테고리, 구독, 일정 제거 ...
  }
}
```
와 같이 의존성을 몰아넣은 하나의 이벤트 리스너를 만들 수 있을 것 같습니다. 
3. 혹은 위와 같은 구조가 `EventListener` 라는 클래스에 너무 많은 의존성을 몰아넣는다면, enum을 사용해볼 수도 있을 것 같습니다.

```java
public enum Event {
  ON_MEMBER_CREATED(new MemberSaveAfterEvent()),
  // ...

  public static void publish(Event event) {
    event.process();
  }
}
```

이벤트를 발행하는 측에서 (e.g. MemberService 의 save() 메소드 등) `Event.publish(ON_MEMBER_CREATED)` 를 사용하면 됩니다. 이런 구조에서는 각 이벤트 발행자가 각각 다른 이벤트 객체에 의존할 필요가 없어져 조금 더 복잡도가 낮아질 것 같은데 어떻게 생각하시나요?

2022-09-11 13:49 UTC, hyeonic commented
@devHudi 

우선 제가 이번 리팩토링을 진행하며 가장 중점을 둔 것은 `MemberService는 오직 Member에 대한 행위에 집중하자` 입니다. 앞서 언급한 것 처럼 `MemberService`는 `MemberRepository`를 제외하고도 여러 의존성이 얽히고 설킨 형태를 가지고 있었습니다.

> 1. MemberEvent와 AuthEvent를 구분하는 이유가 무엇일까요? 현재 구조에서 도메인별로 이벤트 리스너를 나눠놓는 것이 필요한 이유가 궁금합니다! 

각 도메인 패키지에 `인터페이스`를 두어 다른 패키지에 대한 의존성을 최소화 하기위한 목적입니다! 이전에 작성한 `infra`패키지에 위치한 `OAuthClient`나 `OAuthUri`을 `seperated interface`를 통해 분리하신 것을 기억하시나요?? 그렇기 때문에 실제 의존성을 가진 `composition` 패키지에 복잡한 의존성을 몰아 넣은 뒤 `auth`와 `member`에 각각의 `interface`를 두어 약한 의존성을 가질 수 있도록 의도하였습니다. 덕분에 `MemberService`와 `AuthService`는 `compositon` 패키지에 대한 의존성 없이 로직을 수행할 수 있게 되었습니다.

아래는 `AuthService`가 의존하고 있는 import list입니다.

```java
import com.allog.dallog.domain.auth.dto.OAuthMember;
import com.allog.dallog.domain.auth.dto.request.TokenRequest;
import com.allog.dallog.domain.auth.dto.response.TokenResponse;
import com.allog.dallog.domain.member.application.MemberService;
import com.allog.dallog.domain.member.domain.Member;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
```

> 2. Before와 After로 이벤트 구현체를 구분하셨는데, 이 이유가 궁금합니다.

사실 `Before`과 `After`를 나눈 이유는 해당 이벤트를 어느 시점에 실행해야 할지 명시적으로 나타내기 위한 의도를 포함하고 있습니다. 또한 모든 이벤트 관련 행위들을 모아두면 이벤트에 필요한 의존성이 우후죽순으로 늘어갈 것이라 판단했습니다. 다만 이것은 후디가 언급한 것처럼 조금은 과한 것은 아닌가 고민 했어요 🥲

> 3. 혹은 위와 같은 구조가 EventListener 라는 클래스에 너무 많은 의존성을 몰아넣는다면, enum을 사용해볼 수도 있을 것 같습니다.

`enum`을 활용하는 방법도 좋은데요?! 다만 제가 작성한 이벤트 객체의 경우 service 계층의 빈들이 필요하기 때문에 `@Component`를 활용하여 스프링이 관리할 수 있도록 작성했습니다. 그로 인해 `new 키워드`를 통한 객체 생성에 제한이 되고 있어요. 또한 enum을 활용할 경우 어떤 패키지에 두어야 할지도 고민입니다. enum을 활용하게 될 경우 결국 실제 구현부에서 아래와 같이 아주 강한 결합성을 띄지 않을까 판단합니다.

```java
@Transactional(readOnly = true)
@Service
public class MemberService {
    ...
    @Transactional
    public MemberResponse save(final Member member) {
        Member newMember = memberRepository.save(member);
        Event.publish(ON_MEMBER_CREATED); // Event가 담긴 패키지를 무조건 의존하게 됨
        return new MemberResponse(newMember);
    }
    ...
}
```

제 생각 간단히 남겨두었습니다! 다른 분 의견도 들어보고 같이 구조 개선하면 좋을 것 같아요! 이 밖에도 추가적인 의견 있으면 자유롭게 남겨주세요!

2022-09-13 05:43 UTC, summerlunaa requested changes
## 장점
- 하나의 메서드가 온전해진다.
## 단점
- 복잡도가 높아진다.
- 추상화 레벨이 너무 깊어진다.
- 모든 이벤트마다 중복되는 validation이 발생한다.
- 이렇게 구현할 바에 이미 있는 바퀴(eventListener)를 사용하는 게 낫다고 생각한다.
- 테스트가 어렵다.

이런 이유로 이 코드를 반려합니다.

2022-09-13 06:53 UTC, hyeonic commented
회의 내용 기반으로 default 메서드와 하나의 서비스 계층으로 구조 개선하여 다시 PR 요청하겠습니다!

2022-09-13 06:53 UTC, closed without merging