[feat] 사이드 바의 카테고리 목록을 분리하고 각 목록을 아코디언 메뉴로 변경한다.
woowacourse-teams/2022-dallog pull request #573
Opened 2022-09-12 04:57 UTC by jhy979

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- [x] 구독 카테고리 목록 -> 나의 카테고리 목록, 구독 카테고리 목록, 구글 카테고리 목록
- [x] 나의 카테고리 목록 아코디언
- [x] 구글 카테고리 목록 아코디언
- [x] 구글 카테고리 목록 아코디언

## 스크린샷
![image](https://user-images.githubusercontent.com/32920566/189576618-d6c73c14-1d92-4475-aaaf-1166ea397efd.png)

https://user-images.githubusercontent.com/32920566/189576633-04981fbb-8276-4df0-8b54-98195c2cf352.mp4

## 주의사항

Closes #546

2022-09-12 05:12 UTC, jhy979 commented on frontend/src/components/ScheduleModal/ScheduleModal.tsx
> +  const { user } = useUserValue();
user id를 위해서 API 요청을하지 않고 useUserValue 훅을 부릅니다.

2022-09-12 05:15 UTC, daaaayeah commented
오 리뷰 달고 있었는데 정리하셨네요! 이 커밋에 mock에 대한 코드가 같이 올라왔어요 🙃 확인 부탁드릴게요~!

[refactor: 불필요한 코드 정리](https://github.com/woowacourse-teams/2022-dallog/pull/573/commits/8e544c0b105e5ad5c914a1c63c7e5b6f3d099d95)

2022-09-12 06:27 UTC, daaaayeah requested changes
9️⃣🎂 추석 연휴 잘 보내고 계시나요~?
하고 싶어 하셨던 작업인데 어떠셨는지도 궁금하네요 ☺️

코드량이 많지만 전반적으로 기존의 코드를 적절하게 가져다가 써주셔서 이해하기 쉬웠습니다
코드와 아래에 리뷰 몇 개 남겼으니 확인 부탁드려요~!

### 1. 유저 정보를 전역으로 관리하도록 변경했습니다.

이에 대해서 궁금한 것을 코드 레벨에 남겨뒀습니다

### 2. 컴포넌트 네이밍을 다음과 같이 지었습니다.

> 나의 카테고리 : SideMyList
>
> 구독 카테고리 : SideSubscribedList
> 
> 구글 카테고리 : SideGoogleList
> 
> 각 아이템 : SideItem

개인적으로는 `Side` prefix를 없애고 `category`를 명시하는 것도 좋을 것 같아요!
예) MyCategoryList, SubscribedCategoryList, GoogleCategoryList
(지금 MyCategoryItem, MyCategoryList가 사용되지 않는데 살아있어요!)

개인적인 의견이니 참고만 해주세요 😉

### 3. SideItem이 3개의 아코디언 메뉴의 개별 아이템들을 나타내는데 조금 비대해보입니다. 역할을 분리할 필요가 있을까요?

제 기억이 정확하다면, `구독 카테고리`와 `나의 카테고리`로 나뉘었던 시절에도 분리했었어요!
도메인이 다르다고 정의하고 분리하는 게 좋다고 생각합니다 🙂

분리하신다면 분리하시고 나서 리뷰하려고 SideItem은 아직 확인하지 않았습니다

2022-09-12 06:27 UTC, daaaayeah commented on frontend/src/hooks/useModalPosition.ts
> +function useModalPosition() {
분리 좋네요 ☺️ 분리한 김에 calendar에서도 사용하면 좋을 것 같아요~! (이건 추후의 리팩토링으로 넘겨도 좋습니다!)

2022-09-12 06:38 UTC, daaaayeah commented
### + UI에 대한 의견

1. 카테고리 제목에서 '목록'을 떼는 건 어떤가요~! 최대한 간결하게 보이면 좋겠습니다 🙃
2. `나의 카테고리 목록`의 추가 버튼과 `구글 카테고리 목록`의 추가 버튼을 통일하는 건 어떨까요~! 위와 같은 이유에서요!
그리고 `나의 카테고리 목록 추가 버튼`의 카테고리 아이콘이 `내비게이션 바 카테고리 메뉴`의 카테고리 아이콘과 통일되는 게 좋을 것 같은데, 그런 아이콘을 구하기가 쉽지 않을 것 같아요 🥲
3. 카테고리 아코디언을 toggle하려면 toggle 아이콘을 눌러야 하는 것 같아 보이는데요! (맞나요?)
카테고리 제목 어디든 눌러도 toggle할 수 있게 하는 건 어떤가요?!

2022-09-12 06:48 UTC, jhy979 commented on frontend/src/components/SideGoogleList/SideGoogleList.styles.ts
> +  height: ${isListOpen ? `${8 * (listLength + 1)}rem` : 0};
![image](https://user-images.githubusercontent.com/32920566/189590020-c8e97603-c4e6-45e8-a233-8a4bc3fb0faa.png)

listLength가 `내 일정, 나인 카테고리` 같은 리스트의 길이입니다. 여기서는 2가되겠네요!


height가 auto -> 0으로 옮겨가는 (아코디언 메뉴가 열고 닫히는) 애니메이션을 `transition`으로 동작하게 하려했는데

auto일 경우에는 transition css가 안 된다고 하더라구요.

그래서 명시적으로 높이를 주기 위해 리스트의 길이를 가져와서 height로 지정해주었습니다.

2022-09-12 06:51 UTC, jhy979 commented on frontend/src/hooks/useUserValue.ts
> +  );
저번에도 이야기가 나왔었는데 user의 id가 필요한 경우가 존재할 때 매번 profileApi를 호출하는 것이 비효율적이라고

서로 이야기 했었어요.

이를 한 번 호출하고 전역으로 저장해서 사용하자고 했었는데

이번에 했습니다. (이번에 아코디언 메뉴로 분리하면서 user id가 많이 사용되더라구요.)

2022-09-12 06:52 UTC, jhy979 commented on frontend/src/recoil/atoms/index.ts
> +}
타입을 지정하지 않으면 `userState atom`에서 에러가 발생했습니다.

2022-09-12 06:52 UTC, jhy979 commented on frontend/src/components/Profile/Profile.tsx
> +  const { user } = useUserValue();
위에서 설명드린 이유에서 입니다! (한 번만 호출하고 사용하기)

2022-09-12 06:53 UTC, jhy979 commented on frontend/src/components/SideBar/SideBar.tsx
> +  const googleList = data.data.filter((el) => el.category.categoryType === CATEGORY_TYPE.GOOGLE);
음.. 저는 생각이 나지 않는데 어떤 방법이 있을까요?😶😶

2022-09-12 07:10 UTC, jhy979 commented
> ### + UI에 대한 의견
> 1. 카테고리 제목에서 '목록'을 떼는 건 어떤가요~! 최대한 간결하게 보이면 좋겠습니다 🙃

아 동의합니다! 짧게 줄일게요.

> 2. `나의 카테고리 목록`의 추가 버튼과 `구글 카테고리 목록`의 추가 버튼을 통일하는 건 어떨까요~! 위와 같은 이유에서요!
>    그리고 `나의 카테고리 목록 추가 버튼`의 카테고리 아이콘이 `내비게이션 바 카테고리 메뉴`의 카테고리 아이콘과 통일되는 게 좋을 것 같은데, 그런 아이콘을 구하기가 쉽지 않을 것 같아요 🥲

![image](https://user-images.githubusercontent.com/32920566/189593669-a6614912-6982-47fd-94b7-dd070cb48e49.png)
이 아이콘 말씀이신가요? 이 아이콘은 `추가`라는 느낌이 안들지않나요?


> 3. 카테고리 아코디언을 toggle하려면 toggle 아이콘을 눌러야 하는 것 같아 보이는데요! (맞나요?)
>    카테고리 제목 어디든 눌러도 toggle할 수 있게 하는 건 어떤가요?!

현재도 카테고리 제목 눌러도 토글됩니다!

2022-09-12 08:19 UTC, daaaayeah commented on frontend/src/hooks/useUserValue.ts
> +  );
> 이를 한 번 호출하고 전역으로 저장해서 사용하자고 했었는데

아하 이 얘기도 하려고 했는데 이걸 한 거였군요~!
다만 `useUserValue`를 사용할 때마다 해야 되는 일인지는 잘 모르겠어요 🤔
access token을 저장하고 가져다 쓰는 것처럼 다른 user 정보도 비슷한 시점에 관리되면 좋을 것 같은데 어떠세요?!

2022-09-12 08:21 UTC, daaaayeah commented on frontend/src/recoil/atoms/index.ts
> +}
오호 혹시 어떤 에러인가요?!
access token 이외의 user 정보도 전역 상태로 관리하기로 했으니 이에 따라 atom의 수정이 필요할 것 같습니다!

2022-09-12 08:33 UTC, jhy979 commented
> 3. SideItem이 3개의 아코디언 메뉴의 개별 아이템들을 나타내는데 조금 비대해보입니다. 역할을 분리할 필요가 있을까요?
제 기억이 정확하다면, 구독 카테고리와 나의 카테고리로 나뉘었던 시절에도 분리했었어요!
도메인이 다르다고 정의하고 분리하는 게 좋다고 생각합니다 🙂

분리하신다면 분리하시고 나서 리뷰하려고 SideItem은 아직 확인하지 않았습니다

---
음 그런 부분에서 생각하셨군요!

하지만 지금은 조금 다르다고 생각하는데요,

카테고리 페이지에서 `구독 카테고리 기능은 그대로 유지`하고 `나의 카테고리`를 없애고 사이드바로 이동한 것이기 때문에 

사이드 바에서 구독 카테고리 목록은 
`필터링 체크 + 팔레트 색상 변경` 의 일만 하고 있어요.

이는 `나의 카테고리` 와 `구글 카테고리` 에서도 공통으로 가지고 있는 로직이기 때문에 나눌 필요는 없다고 생각이 들거든요

---

간단하게 정리하자면 티거가 말씀하신 `구독 카테고리와 나의 카테고리`는 도메인이 완전 달랐기에 `A와 B의 관계`인데

지금은 `구독 카테고리, 나의 카테고리, 구글 카테고리`는 서로 A의 공통 기능(체크박스 해제, 팔레트)을 가지고 있고 `나의 카테고리, 구글 카테고리` 만 추가적인 B의 기능(수정,삭제 권한(을 가지고 있는 상태이기 때문에 

이런 관점에서는 컴포넌트를 나눌 필요가 있을까 라는 생각이 듭니다. 티거 생각은 어떠신지요!😀😀

2022-09-12 08:35 UTC, jhy979 commented on frontend/src/components/SideGoogleList/SideGoogleList.styles.ts
> +  height: ${isListOpen ? `${8 * (listLength + 1)}rem` : 0};
참고로 +1은 한 이유는 텅 비어있는 경우에도 토글을 하면 

`카테고리를 추가하세요` 같은 메세지를 보여주기 위한 공간 창출입니다!

2022-09-12 08:37 UTC, jhy979 commented on frontend/src/recoil/atoms/index.ts
> +}
꼭 default값을 넣어주어야 하나요?
```js
id: 0,
name: '',
```
그렇다면 이렇게 빈 값이 들어가게 될 것 같은데 큰 의미가 있을까요..?

2022-09-12 08:40 UTC, daaaayeah commented on frontend/src/components/SideBar/SideBar.tsx
> +  const googleList = data.data.filter((el) => el.category.categoryType === CATEGORY_TYPE.GOOGLE);
처음엔 집합 개념으로 생각해서 좀 더 간단하게 작성하는 게 좋지 않을까 생각했는데요!
다시 찬찬히 생각해 보니 그렇게 하면 확장성에 좋지 않겠다는 생각이 듭니다
그래서 제가 생각한 것보단 나인이 생각하신 방식이 좋아 보여요 🙂

`subscribedList` 로직만 아래처럼 줄일 수 있을까요~!

```suggestion
  const subscribedList = data.data.filter(
    (el) => el.category.creator.id !== user.id
  );

  const myList = data.data.filter(
    (el) => el.category.categoryType !== CATEGORY_TYPE.GOOGLE && el.category.creator.id === user.id
  );

  const googleList = data.data.filter((el) => el.category.categoryType === CATEGORY_TYPE.GOOGLE);
```

2022-09-12 08:42 UTC, jhy979 commented on frontend/src/hooks/useUserValue.ts
> +  );
아 그러겠네요! 사실 이렇게 만들 때에는 `프로필 편집` 이후에도 제대로 가져오기 위함이였는데

다시 생각해봐야겠네요. 

1. 티거 말대로 access token 저장 시에 한 번 호출하는 것으로 처리
2. react-query의 캐싱을 제대로 이용

2022-09-12 08:44 UTC, daaaayeah commented on frontend/src/components/SideGoogleList/SideGoogleList.styles.ts
> +  height: ${isListOpen ? `${8 * (listLength + 1)}rem` : 0};
> auto일 경우에는 transition css가 안 된다고 하더라구요.

오호 덕분에 하나 알아갑니다 👍🏻

> 명시적으로 높이를 주기 위해 리스트의 길이를 가져와서 height로 지정해주었습니다.

그렇군요! 친절 설명 감사합니다
`8`은 아이템의 높이군요!

2022-09-12 08:49 UTC, daaaayeah commented
> 2. 이 아이콘 말씀이신가요? 이 아이콘은 추가라는 느낌이 안 들지않나요?
> 
> 😯 아 저런 아이콘에 +가 들어있는 아이콘 말씀이신거죠? 일단 react icons에는 없는걸 보니 찾기는 힘들거 같네요ㅜㅜ

오 정확합니다! 네네 찾기 힘들 것 같아서 + 버튼으로 통일하는 게 사용자 입장에서 덜 헷갈리지 않을까 생각했어요~!

> 현재도 카테고리 제목 눌러도 토글됩니다!

오호 확인 감사합니다 😛 최고!

2022-09-12 08:57 UTC, daaaayeah commented
> 지금은 구독 카테고리, 나의 카테고리, 구글 카테고리는 서로 A의 공통 기능(체크박스 해제, 팔레트)을 가지고 있고 나의 카테고리, 구글 카테고리 만 추가적인 B의 기능(수정,삭제 권한(을 가지고 있는 상태이기 때문에
> 
> 이런 관점에서는 컴포넌트를 나눌 필요가 있을까 라는 생각이 듭니다. 티거 생각은 어떠신지요!😀😀

그쵸 그렇게도 볼 수 있겠네요 😀
근데 그 기능이 바뀔 가능성이 있어 보여서 분리하는 게 좋지 않을까 생각했어요!
요건 내일 같이 얘기해봐요~!

2022-09-12 09:08 UTC, daaaayeah commented on frontend/src/recoil/atoms/index.ts
> +}
> 꼭 default값을 넣어주어야 하나요?

다른 atom을 정의할 때에 전부 default를 명시했기 때문에 말씀드렸습니다
해주신 질문에 대해서는 'undefined보다 default가 낫다 vs undefined나 default나 별 차이 없다' 정도로 생각이 좁혀지네요..!

2022-09-13 06:01 UTC, jhy979 commented
추가적으로 구현한 부분들을 커밋 단위로 말씀드릴게요!
### 1.  아이콘 통일
b24934a6274d5b67b1fba343ce5ce54381f5a317 : 아이콘 통일, hover시 설명보여주는 효과 적용, 구독 카테고리에도 + 버튼 부여(카테고리 페이지로 이동)

-> 구독 카테고리에 + 부여한 것이 좀 어색할까요?
![image](https://user-images.githubusercontent.com/32920566/189821413-ea2d3de6-9292-4e62-bcf2-c4356dacdfba.png)

### 2. useUserValue 커스텀훅 수정 및 적용 안되었던 부분들까지 처리
ea0654df4ae2efe0be7d5fc8e625185dac908253 : 적용되지 않았던 부분 useUserValue 사용
aa36932f9263a80515c6a95c40246455275fd63b : staleTime 설정하여 반복적으로 쿼리를 부르지 않도록 변경

### 3. filter 로직 수정
c8eddbbebd7d79a6992e31d6f5c072774a98f3a5 : 티거가 말씀해주신대로 짧게 줄였어요.

### 4. 구독 카테고리 수정 모달 분리
c8eddbbebd7d79a6992e31d6f5c072774a98f3a5 : SideItem 컴포넌트에서 수정,삭제,팔레트 선택을 위한 `SubscriptionModifyModal`을 따로 구현했어요.

맘에 걸리는 부분이 `SubscriptionModifyModal`가 props로 부모 컴포넌트의 mutate 함수를 받는 부분인데요.. 로딩 처리를 위해서 하나의 mutation을 공유해야하더라구요. 어떻게 생각하시나요?
![image](https://user-images.githubusercontent.com/32920566/189821747-6612d41d-5bec-4fb9-92f7-71695faa645f.png)

2022-09-13 07:01 UTC, daaaayeah approved these changes
역대 제일 코드 변경 많고 생각할 거 많은 PR인 것 같은데 👍🏻
너무너무 고생 많으셨습니다 나인~!~!~!
실시간 코드 리뷰 완료 🎉

2022-09-13 07:01 UTC, merged