[feat] 회원 가입 및 회원 삭제 발생하는 순환 참조 구조를 개선한다.
woowacourse-teams/2022-dallog pull request #577
Opened 2022-09-13 07:59 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

앞서 나눈 회의에서 나눈 이야기를 기반으로 개선하여 다시 작성 하였습니다! 

Member에 대한 생성은 이제 `AuthService`의 `generateToken()`로만 이루어 집니다. 기존의 `MemberService`의 `save()`는 이제 운영 코드에서 사용되지 않지만 테스트 코드에서 사용되고 있기 때문에 제거는 안했습니다. 점차 개선할 예정이니 참고 부탁드립니다!

## 스크린샷

## 주의사항

Closes #565, #571

2022-09-13 12:10 UTC, summerlunaa approved these changes
매트 서비스 구조 개선한다고 증맬 수고했습니다🥲. 저도 예전에 서비스 리팩토링 하다가 머리 깨질뻔했어서 참 공감되네요.
중복 코드가 생긴다는 점에서 100프로 마음에 들지는 않지만 장단점이 있는 것 같아요.
repository에서의 default 메서드 사용으로 null 검증 로직이 줄었다는 점, 하위 서비스와 상위 서비스를 중복으로 테스트하지 않아도 된다는 점, 로직을 한 눈에 볼 수 있다는 점 등은 장점이네요!
우선 이 방향으로 리팩토링 해보시조😎

2022-09-13 12:10 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
>      }
메서드 위치가 `saveCategory` 위로 올라가야겠네요!

2022-09-13 12:10 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/OAuthTokenRepository.java
> +    }
default method 사용 good.

2022-09-13 12:10 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +        memberRepository.deleteById(id);
오우 메서드 개수도 많이 줄고 어떤 순서대로 delete 로직이 처리되는지 알 수 있어서 좋네요!

2022-09-13 12:10 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/member/application/MemberServiceTest.java
> -    @DisplayName("이메일로 회원을 찾는다.")
깔-끔
상위 서비스와 하위 서비스를 중복으로 테스트하지 않아도 된다는 점은 좋네요.

2022-09-13 13:37 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 작성해주신 Service 개선 로직 잘보았어요👍👍
한가지 의견만 한번 남겨보았습니다😊
바로 Approve하였습니다!
고생하셧습니다😊

2022-09-13 13:37 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/member/application/MemberService.java
> +        categoryRepository.deleteByMemberId(id);
로직이 한눈에 들어오는군요!

2022-09-13 13:37 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/member/domain/MemberRepository.java
> +    }
이 부분에대해서 PR에 메서드 규칙을 적어보았는데요 
DB에서 데이터를 조회하는 메서드이니까 find로 시작하는 네이밍이 어떨까해요!
내일 같이 얘기해보는것도 좋을것 같아요~

2022-09-13 15:53 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
>      }
반영했습니다!

2022-09-13 15:53 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +            .nextInt(Color.values().length);
옮기면서 머쓱 하더라구요... 🥲

2022-09-13 15:53 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/member/domain/MemberRepository.java
> +    }
죠습니다! 우선 get으로 통일 해두었습니다!

2022-09-13 15:54 UTC, hyeonic commented
기존 데이터 정합성을 해치는 memberService의 `save()`를 사용하는 테스트 로직 전부 제거 하여 반영했습니다!

2022-09-14 04:03 UTC, devHudi requested changes
안녕하세요, 매트!
코드 잘 읽었습니다! 약간의 중복 코드가 발생할 가능성은 한번 지켜봐야할 것 같아요.
Repository를 도메인으로 바라보는 관점에서 default 메소드를 사용한 김에 Repository에 몇가지 책임을 더 줄 수 있을 것 같아서 이에 대해 코멘트 몇자 남겼어요. 감사합니다.

2022-09-14 04:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/member/domain/MemberRepository.java
> +    }
이부분 약간 고민인게 `JpaRepository interface` 명세상 `getById(Long id)`와 같은 메서드는 `deprecated`된 상태라 해당 메서드를 `default`로 지정하면 `override`로 인식되어 컴파일 시점에 경고 메시지를 남기네요 🥲

```java
public interface JpaRepository<T, ID> extends PagingAndSortingRepository<T, ID>, QueryByExampleExecutor<T> {
	...
        @Deprecated
	T getById(ID id);
        ...
}
```

![image](https://user-images.githubusercontent.com/59357153/190058224-2f3ed18a-f6c8-4eee-853d-0f83f4859095.png)

크리티컬한 문제는 아닌데 좀 더 좋은 네이밍 있으면 그걸로 교체하도록 하겠습니다!

2022-09-14 04:17 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +    }
해당 부분 수정 되었는데 다시 확인 부탁드립니다~

2022-09-14 04:20 UTC, devHudi requested changes

2022-09-14 04:20 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
>      }
임의의 색을 선택하는 로직을 Subscription 도메인에 책임을 위임해도 괜찮을 것 같아요. 정적 팩토리 메소드를 사용하면 그 의미도 충분히 전달이 될 것 같은데 어떻게 생각하시나요?

2022-09-14 06:48 UTC, devHudi approved these changes

2022-09-14 07:54 UTC, merged