[refactor] 카테고리와 관련한 ServiceLayer의 구조를 개선한다
woowacourse-teams/2022-dallog pull request #589
Opened 2022-09-15 08:58 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- Category와 관련한 Controller, Service, Repository, Entity 객체 수정

## 주의사항

Closes #588

2022-09-16 02:58 UTC, summerlunaa requested changes
리버 코드 확인했습니다~ 구조 개선한다고 수고하셨어요🥲
몇가지 코멘트와 질문들 남겼으니 확인부탁드려요ㅎㅎㅎ

2022-09-16 02:58 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
> +            throw new NoPermissionException("외부 연동 카테고리에는 일정을 변경할 수 없습니다.");
```suggestion
            throw new NoPermissionException("외부 연동 카테고리의 일정은 변경할 수 없습니다.");
```

2022-09-16 03:16 UTC, hyeonic requested changes
안녕하세요 리버! 매트입니다 😃

생각보다 변경점이 많아 로직을 이해하는데 조금 시간이 걸렸네요 ㅎㅎ 궁금한 부분 코멘트 남겨두었습니다! 확인해주시고 답변 남겨주시면 감사하겠습니다 🙇‍♂️ 

고생하셨습니다!

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
>      }
오우 로직이 굉장히 간단해 졌네요! 

```java
List<Category> externalCategories = categoryRepository
        .findByMemberIdAndCategoryType(memberId, CategoryType.GOOGLE);
```

여기서 `Google`관련 캘린더를 가져온 뒤,

```java
externalCategoryDetailRepository
        .validateExistByExternalIdAndCategoryIn(request.getExternalId(), externalCategories);
```

이미 존재하는지 확인하는 로직으로 개선되었다고 이해해도 괜찮을까요??

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +    public CategoriesResponse findPublicByName(final String name, final Pageable pageable) {
이런 메서드는 네이밍이 정말 애매하네요 🥲

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
>      }
추후에 나의 카테고리 조회는 `paging` 기능이 제거 되어도 괜찮을 것 같아요!

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
> +    Slice<Category> findByNameContainingAndMemberId(final String name, final Long memberId, final Pageable pageable);
`WHERE` 순서가 id 부터 인데 위와 같이 메서드 명을 변경하신 이유가 있을까요??

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
> +    PUBLIC, PERSONAL, GOOGLE;
이름이 변경되었네요! 해당 내용은 프론트 측과 합의가 된 내용인가요??

2022-09-16 03:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
>      }
메서드 분리의 기준이 애매모호 하네요...

```java
    public void validateDeletePossible(final Long memberId) {
        if (category.isExternal()) {
            throw new NoPermissionException("외부 연동 카테고리에는 일정을 변경할 수 없습니다.");
        }
        if (!category.isCreatorId(memberId)) {
            throw new NoPermissionException();
        }
    }
```

위와 같이 작성해도 크게 문제가 없어보이는데 분리하신 이유가 있을까요??

2022-09-16 04:40 UTC, devHudi requested changes
코드가 점점 깔끔해지는 것 같아서 너무 좋네요!
몇가지 수정하면 좋아보이는 것들을 코멘트 달았으니 참고 부탁드려요!

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        Category category = request.toEntity(member);
`toEntity` 좋네용

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +                .validateExistByExternalIdAndCategoryIn(request.getExternalId(), externalCategories);
@summerlunaa Repository를 도메인을 관리하는 일급 컬렉션으로 바라본다면, Repository에서 유효성 검증하는 것은 괜찮다고 생각해요!

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +                .validateExistByExternalIdAndCategoryIn(request.getExternalId(), externalCategories);
그런데 이 로직은 CategoryRepository에서 꺼낸 List<Category> 를 ExternalCategoryDetailRepository에게 전달해서 유효성을 검증하는 점에서 조금 어색하네요!

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        return new CategoryResponse(category);
서비스에 `getXXX()` 이 없어지니 참 보기 좋군요

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +            throw new InvalidCategoryException("내 일정 카테고리는 삭제할 수 없습니다.");
저도 궁금합니다!

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/domain/Category.java
> +        this.categoryType = CategoryType.PUBLIC;
`PUBLIC` 괜찮군요 👍👍

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/dto/response/CategoriesResponse.java
> +    private List<CategoryResponse> toDtos(final List<Category> categories) {
저도 Dto 대신 Response 가 더 좋은 것 같습니다.

2022-09-16 04:40 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/exception/ExistExternalCategoryException.java
> +}
Exist 대신 Duplicate 을 사용하면 더 예외의 의미를 잘 전달할 수 있을 것 같아요.

2022-09-16 08:08 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
> +    PUBLIC, PERSONAL, GOOGLE;
메서드를 작성하다가 PUBLIC이 좋지않을까 해서 변경해보았어요! 
그런데 파랑의피드백을 들으니 Normal이 적절할것 같군요! 수정하였어요~

2022-09-16 08:15 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +                .validateExistByExternalIdAndCategoryIn(request.getExternalId(), externalCategories);
repository에 validate를 하는 기준을 리팩터링을 하면서 다음과 같이 생각해봐서 공유해요~

1. `Domain`이 너무 많은 로직을 들게 되는경우
2. `Domain` 객체 그래프 탐색이 필요하지 않은 경우
3. 비지니스로직에서 예외검증 -> 로직의 흐름이 적절하다고 느껴지는 경우
``` java
@Transactional
    public void update(final Long id, final Long memberId, final SubscriptionUpdateRequest request) {
        subscriptionRepository.validateExistsByIdAndMemberId(id, memberId); => 예외검증
        Subscription subscription = subscriptionRepository.getById(id); => 메인 비지니스 로직
        subscription.change(request.getColor(), request.isChecked());
    }
```
아래와 같이 하면 비지니스로직이 반드시 실행되야 하는 구조가 될수 있을거 같아요~
``` java
@Transactional
    public void update(final Long id, final Long memberId, final SubscriptionUpdateRequest request) {
        Subscription subscription = subscriptionRepository.getById(id); => 메인 비지니스 로직
        subscription.validateUpdatePossible(id);  => 예외 검증
        subscription.change(request.getColor(), request.isChecked());
    }
```

2022-09-16 08:16 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +                .validateExistByExternalIdAndCategoryIn(request.getExternalId(), externalCategories);
수정이 필요하면 다시한번 말씀해주세요!

2022-09-16 08:17 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +            throw new InvalidCategoryException("내 일정 카테고리는 삭제할 수 없습니다.");
`Category`가 PUBLIC 메서드로 isPersonal()을 이미 가지고 있어서
재활용하는 쪽으로 구성해보았어요~

2022-09-16 08:20 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/dto/response/CategoriesResponse.java
> +    private List<CategoryResponse> toDtos(final List<Category> categories) {
수정하였습니다!

2022-09-16 08:20 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/domain/Schedule.java
> +            throw new NoPermissionException("외부 연동 카테고리에는 일정을 변경할 수 없습니다.");
수정하였어요!

2022-09-16 08:20 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
>      }
맞습니다~~

2022-09-16 08:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +    public CategoriesResponse findPublicByName(final String name, final Pageable pageable) {
이부분은 몇번 고민해봤는데 어렵네요..😔

2022-09-16 08:21 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
>      }
좋습니다!!

2022-09-16 08:23 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryRepository.java
> +    Slice<Category> findByNameContainingAndMemberId(final String name, final Long memberId, final Pageable pageable);
헉 이부분은 생각못했네요! 덕분에 찾았네요 매트😊

2022-09-16 08:23 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
> +    PUBLIC, PERSONAL, GOOGLE;
다시 수정하였어요~

2022-09-16 08:28 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/exception/ExistExternalCategoryException.java
> +}
이부분은 기존의 로직에서 예외객체명이 ExistXXX인 경우가 있어서 이렇게 통일을 해보았어요!
Service 레이어 리팩터링이 완료되면 그때 다시한번 커스텀예외 객체명을 리팩터링하는것도 좋을것 같아요!

2022-09-16 08:33 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/category/dto/request/CategoryCreateRequest.java
> +        return new Category(name, member, CategoryType.valueOf(categoryType.toUpperCase()));
생각 못하고 있었네요!! 수정하엿어요~

2022-09-16 08:38 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/exception/ExistExternalCategoryException.java
> +}
아하 그런이유였군요 👍

2022-09-16 08:38 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/category/domain/CategoryType.java
> +    PUBLIC, PERSONAL, GOOGLE;
오.. 다시 수정됐군요

2022-09-16 10:24 UTC, devHudi approved these changes
리버 덕분에 구조가 훨씬 보기 좋아졌네요 Approve 드립니다 😄

2022-09-16 12:57 UTC, hyeonic approved these changes
고생하셨습니다! 덕분에 빠르게 service 계층 리팩토링이 진행되고 있네요 ㅎㅎ

2022-09-17 07:20 UTC, summerlunaa approved these changes
리뷰 반영 확인했습니다! 리버 수고했서용ㅎㅎ

2022-09-17 07:21 UTC, merged