[refactor] 내부 스케줄과 외부 스케줄 관련 로직을 리팩토링한다.
woowacourse-teams/2022-dallog pull request #591
Opened 2022-09-16 03:57 UTC by summerlunaa

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- CalendarService, MemberScheduleResponse, IntegrationSchedule, IntegrationScheduleComparator 등 내부-외부 스케줄 관련 코드들을 리팩토링 하였습니다.

Closes #564

2022-09-16 04:26 UTC, hyeonic requested changes
안녕하세요 파랑! 매트입니다 😃

복잡한 부분이었을 텐데 깔끔하게 개선된 부분이 많네요! 다만 조금 아쉬운 부분이 있어서 간단히 코멘트 남겼습니다! 확인해주시고 고민하신 뒤 반영해주세요. 고생하셨습니다 👍

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
> -    private String tokenType;
다 어디 갔어 🥲

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/dao/IntegrationScheduleDao.java
>          }
생각해보니 `Repository`에서 반환하는 `List`도 `mutable`한 것 같네요! `new ArrayList<>()` 부분이 더 자연스러운 것 같아요 😃

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/IntegrationScheduleComparator.java
> -        return SAME;
로직이 단순 해졌네요 👍

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/Period.java
> +    }
디미터 법칙을 고려해보면 좋을 것 같아요!

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponse.java
> +                integrationSchedule.getCategoryType().name());
이 부분도 위와 동일합니다!

2022-09-16 04:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
> +                .findAny()
`findAny()`와 `findFirst()`는 어떠한 차이가 있을까요??

2022-09-16 04:26 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
리플렉션 장신 코파랑.. 💙

2022-09-16 04:26 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
아니면 아래와 같은 형식은 어떤가요??

```java
public static Category generateCategory(final Long id, final String name, final Member creator, final ContentType contentType) {
    Category category = new Cateory(name, creator, contentType);
    try {
        Field idField = Category.class.getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(category, id);
        return category;
    } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new IllegalArgumentException(e.getMessage());
    }
}
```

2022-09-16 04:26 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/subscription/domain/SubscriptionsTest.java
> +class SubscriptionsTest {
꼼꼼한 테스트 👍

2022-09-16 05:00 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
> -    private String tokenType;
그는 갔습니다...

2022-09-16 05:18 UTC, devHudi requested changes
코퍼랭 어려운 작업이셨을텐데 너무 고생 많으셨습니다! 
코드가 너무 깔끔해졌네요!
몇가지 고민거리를 코멘트에 달아두었습니다!

2022-09-16 05:18 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
>      }
`Subscriptions` 처럼 `ExternalCategoryDetails`를 만드는 것은 어떨까요?

2022-09-16 05:18 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/IntegrationScheduleComparator.java
> +        return cmp;
파랑은 천재

2022-09-16 05:18 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
오호 신기해요 이제 id를 갖는 픽스쳐를 만들 수 있다..

2022-09-16 08:47 UTC, gudonghee2000 approved these changes
안녕하세요 파랑~ 
작성해주신  코드 잘보았어요!!
많은 메서드들이 삭제되고 이동되었군요😊😊

그리고 생각하지 못한 부분들도 배울수 있게되어서 좋았습니다!
대부분의 코멘트는 팀원분들이 주셔서
바로 approve하였습니다!

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
> +        this.value = value;
value에 `accessToken`만 받아오는걸까요??

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
> +    private final SubscriptionRepository subscriptionRepository;
`SubscriptionService`에 대한 의존성이 제거되었군요!

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
> -    }
오오 방대한 로직들이 제거되었군요!!

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/IntegrationScheduleComparator.java
> +        if (cmp == SAME_CONDITION) {
헉! 이렇게 로직을 완전 깔끔히 만들수있군요!
파랑은 신이야
parang is GOD

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
> +    }
일급 컬렉션의 활용!!👍👍

2022-09-16 08:47 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
오오 리플렉션을 활용해서 id를 가지는 객체를 만들수 있군요!
전체적인 테스트 코드들에도 적용하면 너무 좋을것같네요😊

2022-09-16 10:24 UTC, devHudi commented
@gudonghee2000 CI 실패는 rebase 한번 해보면 해결될거예요

2022-09-17 07:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
오 좋네요~ 수정해보겠습니다ㅎㅎㅎ

2022-09-17 07:30 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
앗 근데 저렇게 하면 기존의 Category fixture를 활용할 수 없고 모든 필드를 또 하나하나 넣어줘야해서 귀찮네요🥲

2022-09-17 07:31 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/integrationschedule/domain/Period.java
> +    }
한 줄에 점 하나!

2022-09-17 07:32 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponse.java
> +                integrationSchedule.getCategoryType().name());
![image](https://user-images.githubusercontent.com/77425729/190845918-aa9d22fb-c29d-4fcd-a238-9ba78cb52fbe.png)
흠 근데 이렇게 하니 못생겨서.. 이 부분은 일단 수정하지 않을게요!

2022-09-17 08:55 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
> +                .findAny()
[Java 8 Stream findFirst() vs. findAny()](https://www.baeldung.com/java-stream-findfirst-vs-findany/) good 덕분에 알아갑닏.

2022-09-17 08:55 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
> +        return value;
사용하지 않는 필드들이라 삭제했습니다.

2022-09-17 08:57 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
> +        return subscriptions.stream()
class 자체가 Subscription인데 굳이 `OfSubscription`을 넣어줘야 할까요?

2022-09-17 09:00 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/dto/response/OAuthAccessTokenResponse.java
> +        this.value = value;
넵

2022-09-17 09:03 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/composition/application/CalendarService.java
>      }
현재 로직에서는 `ExternalCategoryDetails`을 만들어도 `isEmpty` 외에 어떤 로직이 들어갈 수 있을지 잘 모르겠네요🥲

2022-09-17 11:01 UTC, gudonghee2000 approved these changes
안녕하세요 파랑! 추가적으로 수정해주신 부분과 의견달아주신 부분 모두 확인하였습니다~
종일 관련해서 -1분 로직을 롤백해주신 부분도 확인하였어요!

달아주신 댓글에 조금의 의견만 남겨보았습니다😊
파랑이 리팩터링 진행해주신 부분덕분에 많은 코드를 줄이고 가독성이 높아졋군요!👍👍
정말 고생하셨습니다.
바로 approve하였습니다~

2022-09-17 11:28 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponse.java
> +                integrationSchedule.getCategoryType().name());
시적 허용(?)으로 두시져

2022-09-17 11:29 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscriptions.java
> +                .findAny()
3줄 요약 해주시져

2022-09-17 11:31 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
뭔가 id 없는 category를 만들고 `setId()`로 넣는 과정이 조금은 번잡하게 느껴지네요 🥲 `setter`란 키워드도 반갑지가 않고..ㅎ 편하신 방향으로 반영 하시져!

2022-09-17 11:36 UTC, hyeonic approved these changes
안녕하세요 파랑, 매트입니다 😃

간단히 코멘트 남겨 두었습니다. 크게 수정할 부분은 아니니 바로 Approve 하겠습니다! 리팩토링 작업하시느라 고생하셨슴다 👍

2022-09-17 11:36 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
> +    }
간단하지만 예외 관련 테스트라도 작성하는 편이 어떨까요??

2022-09-17 12:35 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/common/fixtures/CategoryFixtures.java
> +    }
넵 사용하기엔 지금 상태가 편한 것 같아요! 우선 이렇게 가겠습니다ㅎㅎ

2022-09-17 12:36 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/category/domain/ExternalCategoryDetailRepository.java
> +    }
아마따 깜빡쓰 추가하겠슴니다

2022-09-18 04:41 UTC, devHudi approved these changes
파랑~ 리뷰에 코멘트 달아주신 부분 모두 확인했습니다. Approve 드려요.
즐거운 주말 보내세요~!

2022-09-18 04:42 UTC, merged