[feat] 쿼리 분석 중 application 계층의 메서드에 누락된 테스트를 추가한다.
woowacourse-teams/2022-dallog pull request #597
Opened 2022-09-16 13:02 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

쿼리 분석 중 application 계층의 메서드에 누락된 테스트를 추가한다.

## 스크린샷

## 주의사항

Closes #596

2022-09-16 13:11 UTC, devHudi commented
prefix를 `[test]` 로 설정하는 것이 좋겠네요!

2022-09-16 13:14 UTC, devHudi requested changes
역시 맽. 꼼꼼하군요.
약간의 실수가 있는 것 같아서 이거만 고쳐주세요!

2022-09-16 13:14 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
> +
순서 변경 이유가 무엇일까요?

2022-09-16 13:14 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
> +        System.out.println("========================");
```suggestion
        // when
        subscriptionService.delete(response.getId(), 후디_id);
```

제거해야할 것 같습니다!

2022-09-16 13:14 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
> +        subscriptionService.save(후디_id, BE_일정.getId());
개행을 해주면 가독성이 개선될 것 같아요.

2022-09-16 13:32 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
> +
* save
 * findById
 * findByMemberId
 * ...

memberId는 FK고 Id는 PK라 중요도에 따라 조정하였습니다~

2022-09-17 05:02 UTC, devHudi approved these changes
수정해주신 것 확인했습니다 매트! 좋은 주말 보내세요!

2022-09-17 07:13 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 작성해주신 테스트코드와 이동해주신 메서드 잘보았어요😊
find 메서드의 순서에 대해서는 생각하지 못했엇네요ㅎㅎ
또한 추가 해주신 테스트 코드도 잘보았어요!
바로 approve 하겠습니다! 고생하셨습니다~

2022-09-17 07:13 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
> +
`FK`와 `PK` 따라 순서를 정리하는건 생각못했었네요!
저도 추가적인 리팩터링을 하면서 적용해보겟습니다😊

2022-09-17 09:18 UTC, summerlunaa approved these changes
누락된 테스트 추가!! good. 수고하셨어요ㅎㅎ

2022-09-18 14:58 UTC, merged