[feat] Date Time Picker 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #603
Opened 2022-09-18 05:17 UTC by jhy979

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- [x] Select 컴포넌트 구현
- [x] 일정 유효성 검사 커스텀훅에서 Date와 Time을 분리하여 판단
- [x] 일정 추가 모달 Picker 기능 구현
- [x] 일정 수정 모달 Picker 기능 구현 
## 스크린샷
![image](https://user-images.githubusercontent.com/32920566/190886876-385ddae2-1f26-4568-9f33-fa1c94d30ff7.png)

![image](https://user-images.githubusercontent.com/32920566/190886871-eb882c3a-2ef4-426c-a900-ad52c2271913.png)

## 주의사항
- Select 컴포넌트가 Fieldset 컴포넌트처럼 커스텀한 cssProp이 없습니다. (고정된 스타일링) -> 추후 수정 예정

Closes #567

2022-09-18 13:30 UTC, daaaayeah requested changes
9️⃣〰 좋은 주말 보내고 계시나요~!
주말에 PR을 올려주시다니 대단합니다

이것도 나인이 하고 싶다고 하셨던 태스크였던 것 같은데 끝나니 어떠신가요 🙃
힘들어하시는 걸 옆에서 보기도 했지만... 역시나 해내실 줄 알았어요 👏👏👏👏

너무너무 고생하셨습니다
리뷰 몇 개 달았으니 확인 부탁드려요!

2022-09-18 13:30 UTC, daaaayeah commented on frontend/src/hooks/useValidateSchedule.ts
> +  }, [startDate, startTime]);
종료 시간이 바뀔 때에는 아직 아무 일도 일어나지 않는 거 맞나요~!

2022-09-18 22:52 UTC, jhy979 commented on frontend/src/components/@common/Select/Select.styles.ts
> +`;
오 그것도 좋겠네요. 전역 스타일을 많이 이용하면 코드 재사용성이 좋아질 것 같아요.

2022-09-18 23:05 UTC, jhy979 commented on frontend/src/components/@common/Select/Select.styles.ts
> +  box-sizing: contain;
엇 잘못 한 것 같아요... 삭제하겠습니다 ㅠㅠ

2022-09-18 23:07 UTC, jhy979 commented on frontend/src/components/@common/Select/Select.styles.ts
> +  display: ${!isSelectOpen && 'none'};
그렇겠네요! 수정하겠습니다✨

4dd993869ca6bb25577704d420c0eac80285cc0e

2022-09-18 23:10 UTC, jhy979 commented on frontend/src/components/@common/Select/Select.tsx
> +        <div css={optionLayoutStyle(theme, isSelectOpen)} ref={ref}>
absoulte로 주변 요소들과의 상호작용을 무너트려서 

select를 클릭하여 옵션들이 나와도 요소들이 밀려서 박스 바깥으로 나가거나 하는 일을 방지해줍니다.

만약 이 속성을 없앤다면 이렇게 됩니다.
![image](https://user-images.githubusercontent.com/32920566/190932177-49be0893-041f-4b95-a3d3-49593a0307fc.png)

2022-09-18 23:12 UTC, jhy979 commented on frontend/src/constants/date.ts
> +  );
그런가요..?ㅋㅋ 좀 지저분한데 감사합니다

2022-09-18 23:12 UTC, jhy979 commented on frontend/src/utils/date.ts
> +  if (dateInfo === undefined) {
아래랑 같이 수정할게요!

2022-09-18 23:15 UTC, jhy979 commented on frontend/src/utils/date.ts
> +  if (nowMinute > '30') {
아 맞네요! early return으로 처리가 되었는데!!

2022-09-18 23:26 UTC, jhy979 commented on frontend/src/utils/date.ts
> +    .split(':');
아 바로 위에 함수가 있었네요!

2022-09-18 23:27 UTC, jhy979 commented on frontend/src/utils/date.ts
> +  getStartTime,
음.. 저도 그런 생각이 갑자기 드네요. `ScheduleAddModal`의 도메인 로직이 더 맞겠죠...?

이건 뭐 다시 쓰일 유틸함수는 아니니까요! 옮기겠습니다 ㅎㅎ

2022-09-18 23:33 UTC, jhy979 commented on frontend/src/constants/date.ts
> +  );
`padStart` 관련 유틸함수를 예전에 만들어놨었네요. 이 부분까지 적용하겠습니다. 

8ad9b1e3446c33679942ab91cf15d9bf80f695ec

2022-09-18 23:33 UTC, jhy979 commented on frontend/src/utils/date.ts
> +    .split(':');
date 관련 리팩토링 전부 합쳐서 하나의 커밋으로 처리했습니다🔨🔨

12487d0ab3f21ddd75d3789d77b7a1bd472d95e6

2022-09-18 23:36 UTC, jhy979 commented on frontend/src/components/@common/Select/Select.tsx
> +                  name="option-picker"
`input`이 여러번 반복해서 나오게되는데요!

name값을 모두 동일하게 주면 해당 name값에 대해서 하나의 input value값을 가질 수 있어서

input type radio인 경우에 하나의 값을 가지기 위해서 사용됩니다.

2022-09-18 23:37 UTC, jhy979 commented on frontend/src/hooks/useValidateSchedule.ts
> +  }, [startDate, startTime]);
네 맞습니다. 종료 시간 validation은 아직 하지 않았습니다.

2022-09-19 04:17 UTC, daaaayeah commented on frontend/src/constants/date.ts
> +  );
오 저도 놓쳤네요! 좋아요~! 🫠

2022-09-19 04:30 UTC, daaaayeah approved these changes

2022-09-19 04:30 UTC, daaaayeah commented on frontend/src/utils/date.ts
> +  getStartTime,
그쵸 util인 만큼 추후에 네이밍을 좀 더 범용적으로 만드는 것도 좋겠네요~!

2022-09-19 04:34 UTC, merged