[feat] 유저 본인 정보 조회 기능을 구현한다.
woowacourse-teams/2022-dallog pull request #62
Opened 2022-07-16 00:57 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

유저 본인 정보 조회를 위한 기능을 구현한다.

## 주의사항

현재 소셜 로그인 관련 기능과 테스트가 merge 되지 않아 후에 부족한 테스트 보충하여 반영할 예정입니다.

Closes #33

2022-07-17 09:08 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 만들어주신 유저 본인정보 조회 기능 잘보았어요! 
ArgumentReslover를 통해 조회기능을 완성하셨군요👍👍👍
코드를 보면서 ArgumentReslover를 통한 토큰 사용을 한번 더 공부하게되었어요😊   

몇가지 메서드의 파라미터에 final 키워드가 누락된 부분이있어서 이부분만 확인한번
부탁드려요!
바로 approve 하겠습니다!

2022-07-17 09:08 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/auth/support/AuthenticationPrincipalArgumentResolver.java
> +                                  NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
`supportesParameter()`와 `resolveArgument()`의 파라미터에 final 키워드가 추가되면 좋을거같아요!

2022-07-17 09:08 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/auth/support/AuthorizationExtractor.java
> +        if (!authorizationHeader.toLowerCase().startsWith(BEARER_TYPE.toLowerCase())) {
메서드 파라미터에 final 키워드가 추가되야할것같아요!

2022-07-17 09:20 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/auth/support/AuthorizationExtractor.java
> +        if (!authorizationHeader.toLowerCase().startsWith(BEARER_TYPE.toLowerCase())) {
아무생각 없이 복붙 하다보니.. 바로 반영하겠습니다 🥲

2022-07-17 16:23 UTC, devHudi requested changes
매트!!! 리뷰가 늦어서 매우 죄송합니다! 🥲
`MemberResponse` DTO의 `socialType` 필드 유무에 대해서는 논의가 필요할 것 같아서 코멘트 남겨뒀습니다!

2022-07-17 16:23 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/member/dto/MemberResponse.java
> +    private SocialType socialType;
외부에서 `socialType` 을 어떻게 활용할 수 있을까요? 확신은 없지만 사용자가 인증한 OAuth 제공자를 노출해버리면 보안 측면에서 좋지 않을 것 같아요! 🤔

2022-07-17 16:23 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/member/controller/MemberController.java
> +    public ResponseEntity<CommonResponse<MemberResponse>> findMe(@AuthenticationPrincipal LoginMember loginMember) {
제 생각과 똑같이 URI를 설계하셨네요! 지난 미션때 보니 은근 자기 자신 정보를 불러오는 API의 URI 디자인이 모두 다르더라구요.

2022-07-18 08:33 UTC, devHudi submitted a review, later dismissed
LGTM 👍👍👍

2022-07-18 11:36 UTC, summerlunaa submitted a review, later dismissed
리뷰 늦어서 죄송합니다🥲 궁금한 부분들 코멘트 남겼어요 확인부탁드립니다! 크게 수정할 부분은 없을 것 같아서 우선 approve는 했어요ㅎㅎ.

2022-07-18 11:36 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/auth/exception/InvalidTokenFormatException.java
> +    }
하나의 도메인에 하나의 커스텀 예외를 만들기로 했던 것 같은데, `InvalidTokenException`이 있는데 `InvalidTokenFormatException`을 따로 만드신 이유가 있을까요?

2022-07-18 11:36 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/auth/support/AuthenticationPrincipalArgumentResolver.java
> +        return new LoginMember(id);
Interceptor를 사용하지 않고 ArgumentResolver로 토근 검증부터 인자 커스텀까지 전부 진행한 이유가 있을까요?

2022-07-18 11:36 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
> +            assertThat(memberResponse.getProfileImageUrl()).isEqualTo("Fake Profile Image Url");
이렇게 검사하니까 이 유저의 정보가 어디 저장되어 있는지 잘 모르겠어서 한참 찾았네요🥲 `StubOAuthClient`에서 가져오는 것 맞나여? 설명 plz..

2022-07-18 11:36 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
> +    };
TypeRef가 뭐죵?..

2022-07-18 11:58 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/auth/support/AuthenticationPrincipalArgumentResolver.java
> +        return new LoginMember(id);
현재 인증이 필요한 로직 대부분에서 본인에 대한 id 값을 필요로 하기 때문에 굳이 나눌 필요가 없다고 판단했어요! 언급 해주신 것 처럼 추가적으로 interceptor가 필요한 시점에 분리하는 것도 좋을 것 같습니다.

2022-07-18 12:02 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
> +    };
아까 설명 드리려 했는데 간단히 요약하면 현재 저희가 `CommonResponse`를 `제네릭`을 활용하여 작성했는데 그 때문에 `as(CommonResponse.class)`로 작성할 경우 `타입 추론`에 제한이 생겨버립니다. 그 때문에 RestAssured에서는 `TypeRef`를 통해 이것을 해결해주고 있어요! 아마 저희가 이제 테스트를 작성해야 할 때 위와 같은 형식으로 활용해야 할 것 같아요. 이건 오프라인으로 다시 한번 공유 드리겠습니다.

2022-07-18 12:03 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
> +            assertThat(memberResponse.getProfileImageUrl()).isEqualTo("Fake Profile Image Url");
이건 아직 Fixture에 대한 작업이 진행되지 않아 임시로 작성한 로직 입니다... 말씀하신 것 처럼 StubOAuthClient의 반환 값이 맞습니다. 이건 제가 따로 Fixture로 분리한 뒤 재요청 하겠습니다.

2022-07-18 13:27 UTC, devHudi approved these changes
시간관계상 Approve 합니다!! `MemberResponse` 의 `socialType` 은 그대로 유지되는건가요??

2022-07-18 13:33 UTC, summerlunaa approved these changes
리뷰 반영 확인했습니다. 수고하셨습니다!

2022-07-18 13:33 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/MemberAcceptanceTest.java
> +            assertThat(memberResponse.getProfileImageUrl()).isEqualTo(OAuthMemberFixtures.PROFILE_IMAGE_URI);
good 이게 더 낫네요

2022-07-18 14:31 UTC, merged