[refactor] 상위 서비스 로직을 개선한다.
woowacourse-teams/2022-dallog pull request #630
Opened 2022-09-20 15:37 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
-  [x] 🌈 알록달록한가요?

## 작업 내용

드디어 composition의 모든 서비스를 제거 하였습니다... 다만 워낙에 일정 조율 로직이 복잡하고 많은 쿼리와 네트워크 통신을 유발해서 우리 서비스에서 정상적으로 동작할 수 있을지 조금 걱정이 되네요. 테스트 코드 까지 꼼꼼하게 짜 보려 했는데 외부 리소스 관련 Stub 때문에 테스트가 매우 부실한 상태입니다. 이 점 인지해주시고, 우선적으로 코드 스타일 부터 확인해주시면 감사하겠습니다.

테스트는 추후 이야기 나눠보고 보충할 예정이고, 아직 쿼리 분석은 못했습니다. 시간이 좀 더 소요될 것 같아서 내일 오전 중으로 진행해야 할 것 같네요. 

## 스크린샷

## 주의사항

Closes #{이슈 번호}

2022-09-20 15:46 UTC, hyeonic reviewed
간단히 메서드에 의도 적어두었습니다. 참고해주시면 감사하겠습니다.

일정 조율의 경우 너무 많은 경우의 수를 가지기 때문에 홀로 테스트하는데 많은 어려움이 있었습니다. 저희끼리 좀 더 다양한 시나리오를 구성한 뒤 함께 테스트 코드를 작성해보는 시간을 가져보는 건 어떨까요?? 의견 남겨 주시면 감사하겠습니다!

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/AvailablePeriodsFinder.java
> +    }
가능한 구간을 조회하기 위한 메서드입니다.

```java
AvailablePeriodMaterial material = scheduleService.findInMembersByCategoryIdAndDateRange(categoryId, request);
```

해당 부분에서 트랜잭션이 마무리 되고, 이후에는 트랜잭션 외부에서 진행됨을 인지해주세요!

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/AvailablePeriodsFinder.java
> +    }
외부 access token 조회를 위한 refresh token 별 외부 캘린더 id를 기반으로 외부 캘린더 리스트를 가져온 뒤 합체합니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/AvailablePeriodsFinder.java
> +    }
토큰을 조회하고 실제 외부 서버에게 조회된 일정 리스트를 합체하여 반환합니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/AvailablePeriodsFinder.java
> +    }
실제 외부 서버에게 일정 리스트를 조회하는 부분입니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +    }
특정 카테고리에 대한 내부 일정 리스트와 외부 캘린더 일정 조회를 위한 정보를 dto로 만들어 반환합니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +    }
구독 정보에서 내부 카테고리 리스트 정보를 조회하여 일정 리스트를 반환합니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +    }
refresh token 별 외부 캘린더 조회를 위한 메타 데이터를 그룹핑합니다.

간단한 예시로 제가 구글 개인 일정 및 우테코 일정을 구글에서 등록한 뒤 구독 했다고 가정합니다. 제 refresh token 하나 당 두 개의 외부 캘린더 id를 기반으로 모두 조회해야 하기 때문에 그룹핑을 활용 했습니다.

2022-09-20 15:46 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/AvailablePeriodMaterial.java
> +}
앞서 언급한 것 처럼 가능한 일정 구간 조회를 위한 정보를 담은 dto입니다. 이렇게 추가적인 dto를 생성한 이유는 트랜잭션 구간 내에서 최대한 많은 DB 정보를 조회한 뒤 이를 기반으로 외부 리소스에 관련된 처리를 진행하기 위함입니다.

2022-09-22 06:54 UTC, devHudi requested changes
안녕... 조율.. 😭
아직 조율 기능을 덜 보내준 곳이 있어서 코멘트 달았습니다!

2022-09-22 06:54 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/AvailablePeriodMaterial.java
> +}
일정 조율 기능이 제거되어도 이 클래스는 사용되나요? 현재는 사용하고 있는 곳이 없는 것 같아요!

2022-09-22 07:28 UTC, devHudi approved these changes
LGTM!!

2022-09-22 09:09 UTC, summerlunaa approved these changes
유리야... 잘가... 행복했다😥

2022-09-22 10:21 UTC, gudonghee2000 approved these changes
매트 안녕하세요! 작성 해주신 코드 잘보았습니다~
조유리가 사라지면서 많은 코드들이 사라졌군요..!
코드가 많이 사라져서 좋으면서도 조유리와 이별해서 아쉽네요😔

바로 approve하겠습니다!

2022-09-22 10:22 UTC, merged