소셜 로그인 모달 컴포넌트를 구현한다.
woowacourse-teams/2022-dallog pull request #64
Opened 2022-07-16 08:22 UTC by daaaayeah

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- [x] 시작 페이지 컴포넌트 구현
- [x] 로그인 모달 컴포넌트 구현
- [x] 구글 로그인 연동 및 기능 구현
- [x] access token 저장 (local storage)

## 스크린샷

![소셜-로그인](https://user-images.githubusercontent.com/52729559/179346872-9361e875-bec4-4c29-a5a3-991f60376192.gif)

## 주의사항

- 시작 페이지 임시 경로: `/start`
- 달력 페이지 임시 경로: `/auth`

Closes #38

2022-07-16 09:35 UTC, jhy979 requested changes
티거 로그인 관련 구현하신 부분들 확인했고 리뷰 남겼습니다.

고생하셨습니다👍👍 

크게 고칠 부분은 없는 것 같네요.

코드 작성하시면서 정말 많은 고민이 있으셨을 것 같아요. (특히 openLoginModal을 props로 넘기는 부분, ...)

다만 전역 상태를 도입하지 않으셨는데 이러면 새로고침을 했을 때 로그인 정보가 유지되지 않을 것 같은데 맞나요?

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/components/NavBar/NavBar.tsx
> +      <Button cssProp={loginButton} onClick={openLoginModal}>
NavBar 로그인 버튼에 모달 open을 주입하기 위해 StartPage => PageLayout => NavBar로 넘어오고 있네요.

효율적인 구조라고 생각이 들지는 않은데 저도 이렇게 구현했을 것 같네요...

또, Navbar에는 openLoginModal이라는 props를 가질수 있다고 하지만 

PageLayout 컴포넌트는 재사용이 많이 되는 컴포넌트인데 openLoginModal이라는 props를 가질수도, 안 가질수도 있다 표현하는게 조금 어색한 것 같아요.

저라면 NavBar를 그냥 PageLayout에서 빼내고 

App.tsx의 router 바깥에 두어 화면에 NavBar가 계속 보이게 해줄 것 같은데 어떻게 생각하시나요? (단 NavBar의 높이만큼 PageLayout 컴포넌트에서 margin-top같은 속성을 지정해줘야 될것 같아요.)

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/components/NavBar/NavBar.tsx
> +function NavBar({ openLoginModal }: NavBarProps) {
handleClickLoginButton이 정한 네이밍이였는데

이렇게 props로 받으면 네이밍을 지키기 쉽지 않겠네요. 이 부분은 어쩔 수 없을 것 같네요

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/components/NavBar/NavBar.tsx
> +      <Button cssProp={loginButton} onClick={openLoginModal}>
아.. PageLayout에서 Navbar를 분리해도 문제점이 있을 것 같네요.

왜 티거가 LoginModal을 어디서 구현해야하는지 고민하신지 알 것 같네요. 

StartPage에 넣는다면 지금이 최선이 될 것 같습니다.]

그냥 넘어가셔도 될 것 같아요. (나중에 좀 더 나은 설계를 이야기 해보죠!)

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/api/login.ts
> +  tokenEndpoint: '/token',
endpoint도 많아진다면 이 부분도 객체로 지정할 수도 있겠네요. (지금은 굳이)

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/api/login.ts
> +  baseUrl: 'http://09d2-218-39-176-142.ngrok.io/api/auth/google',
나중에 숨겨야겠네요

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/api/login.ts
> +  auth: async () => {
메서드에 post라는 prefix가 붙으면 좋지 않을까요?

API 요청하는 함수라는 느낌이 들지 않는 것 같아요,

2022-07-16 09:35 UTC, jhy979 commented on frontend/src/constants/index.ts
> +  CALENDAR_PAGE: '/auth',
인증이 되어있다는 상태를 의미하는건가요? calendar page에 auth가 붙는다고 생각하니 조금 어색한 것 같아요.

2022-07-16 09:47 UTC, jhy979 commented on frontend/src/api/login.ts
> +  baseUrl: 'http://09d2-218-39-176-142.ngrok.io/api/auth/google',
디스코드에서 이미 이야기를 나누셨군요~

2022-07-16 17:33 UTC, daaaayeah commented on frontend/src/components/LoginModal/LoginModal.styles.ts
> +  color: ${colors.BLACK}8a;
오 이렇게 하면 적용이 안된다고 생각하시는 걸까요?
어떤 것 때문에 그렇게 생각하시는 걸까요 😮

맨 뒤 두 글자 때문이라면, 페어 프로그래밍할 때 이렇게 작성하기로 이야기 나눴던 기억이 있어요~!

```css
/* components/@common/ModalPortal/ModalPortal.styles.ts:13 */

background: ${isOpen ? `${colors.BLACK}bb` : 'transparent'};
```

2022-07-16 17:39 UTC, daaaayeah commented on frontend/src/components/@common/Button/Button.tsx
> +  cssProp?: SerializedStyles | (({ colors, flex }: Theme) => SerializedStyles);
정확합니다 인자를 받는 경우에는 `Theme`만을 인자로 받을 수 있어요!
다른 props도 인자로 사용될 수 있다는 것에 저도 동의합니다
다만 당장은 그렇게 사용하는 경우가 없으니 추후에 사용할 때 정의하는 것도 좋다고 생각해요 ☺️

2022-07-16 17:43 UTC, daaaayeah commented on frontend/src/components/NavBar/NavBar.tsx
> +      <Button cssProp={loginButton} onClick={openLoginModal}>
악 맞습니다 저도 현재로선 최선이라고 생각하고 PR 드렸지만 충분히 개선할 수 있는 코드라고 생각해요 🥲
리팩토링할 부분이 이 부분 말고도 있어서 리팩토링을 다음 태스크로 잡고 가면 좋을 것 같습니다~!

> 나중에 좀 더 나은 설계를 이야기 해보죠!

좋아요 🚀

2022-07-16 17:45 UTC, daaaayeah commented on frontend/src/api/login.ts
> +  baseUrl: 'http://09d2-218-39-176-142.ngrok.io/api/auth/google',
앗 죄송합니다 디스코드 대화 내용이 공유되지 않았네요 😇
다음부터는 바로바로 공유드리겠습니다~!

2022-07-16 17:52 UTC, daaaayeah commented on frontend/src/constants/index.ts
> +  CALENDAR_PAGE: '/auth',
이건 백엔드에서 redirect 할 때 사용되는 path인데요~!
저도 나인과 똑같이 생각해서 우선은 임시 경로라고 해두었습니다
내일 백엔드 크루들과 이야기해 보고 수정하면 좋을 것 같아요 🙂

(`StartPage` 관련해서 설계가 바뀐다면 바뀔 수 있는 부분이라고도 생각합니다)

2022-07-16 17:59 UTC, daaaayeah commented on frontend/src/api/login.ts
> +  auth: async () => {
와 이 부분 네이밍도 엄청나게 많은 고민을 거쳤는데요...!
code를 post해서 access token을 받는 요청이라 네이밍이 쉽지 않았습니다

> API 요청하는 함수라는 느낌이 들지 않는 것 같아요,

api 객체 안에 있는 함수라 괜찮다며 합리화를 좀... 했네요 😇

> 메서드에 post라는 prefix가 붙으면 좋지 않을까요?

`postAuth`도 고민했던 보기 중에 하나였는데 auth를 post한다는 느낌이 들더라고요 🥲
그래도 어떤 요청인지를 명시하는 게 좀 더 명확하게 읽힐까요~?

2022-07-16 18:02 UTC, daaaayeah commented on frontend/src/components/NavBar/NavBar.tsx
> +function NavBar({ openLoginModal }: NavBarProps) {
넵 `useModal` 훅을 사용하는 곳에서는 어쩔 수 없을 것 같습니다

```ts
/* components/@common/ModalPortal/ModalPortal.tsx:22 */

<div css={dimmer(theme, isOpen)} onClick={closeModal}>
```

2022-07-16 18:12 UTC, daaaayeah commented
> 다만 전역 상태를 도입하지 않으셨는데 이러면 새로고침을 했을 때 로그인 정보가 유지되지 않을 것 같은데 맞나요?

이것도 경로 정리가 되고 나서 도입하면 더 좋을 것 같다고 생각해서 우선은 하지 않았습니다!

2022-07-16 18:24 UTC, daaaayeah commented on frontend/src/components/@common/Button/Button.tsx
> +  cssProp?: SerializedStyles | (({ colors, flex }: Theme) => SerializedStyles);
> 다만 당장은 그렇게 사용하는 경우가 없으니 추후에 사용할 때 정의하는 것도 좋다고 생각해요 ☺️

헉 다시 보니 이미 그렇게 사용하는 부분이 있었네요 🤭
아래 코드 작성하실 때 타입을 지정하지 않아도 괜찮던가요?!

```ts
/* components/ScheduleAddModal/ScheduleAddModal.tsx:101 */

<Button cssProp={allDayButton(theme, isAllDay)} onClick={handleClickAllDayButton}>
```

2022-07-17 08:13 UTC, jhy979 commented on frontend/src/components/@common/Button/Button.tsx
> +  cssProp?: SerializedStyles | (({ colors, flex }: Theme) => SerializedStyles);
스타일에서 `allDayButton`을 정의할 때 isAllDay를 boolean으로 처리했었어요

2022-07-17 08:15 UTC, jhy979 commented on frontend/src/components/LoginModal/LoginModal.styles.ts
> +  color: ${colors.BLACK}8a;
아 네 저는 `8a`가 문자열로 인식이 안 될 것 같아서 말씀 드렸던 거예요

```ts
-   color: ${colors.BLACK}8a;
+   color: `${colors.BLACK}8a`;
```
아래처럼 작성해야 적용되는게 아닌가 궁금했습니다!

2022-07-17 08:17 UTC, jhy979 commented on frontend/src/components/LoginModal/LoginModal.styles.ts
> +  color: ${colors.BLACK}8a;
아 순간 착각했네요

맨 뒤 두글자가 아니라 문법적으로 실제로 저 색이 적용이 되는지 궁금했었는데 잘못 생각했네요

2022-07-17 08:19 UTC, jhy979 commented on frontend/src/api/login.ts
> +  baseUrl: 'http://09d2-218-39-176-142.ngrok.io/api/auth/google',
아뇨아뇨 제가 못본건데요 ㅎㅎ;;

2022-07-17 08:22 UTC, jhy979 commented on frontend/src/api/login.ts
> +  auth: async () => {
이 부분은 postAuth가 조금 어색하긴하네요. (네이밍 컨벤션을 지키기위해 본질을 해치는 경우가 될 거 같네요)

그럼 이 부분만 예외로 auth로 하고 대부분의 요청들은 `request method`가 prefix로 붙는걸로 하시죠!

2022-07-17 08:23 UTC, jhy979 commented on frontend/src/constants/index.ts
> +  CALENDAR_PAGE: '/auth',
아 그렇군요 티거가 PR 남기실때 auth가 임시경로라고 말씀하셔서

왜 임시경로인가 궁금했는데 그런 이슈가 있었꾼요~!

2022-07-17 08:25 UTC, jhy979 requested changes
`(({ colors, flex }: Theme) => SerializedStyles);`

cssProp에 대해서 한 번만 더 하면 될 것 같아요. 

저한테는 아직 이 PR에 대한 코드가 없어서 확인을 못해봤는데 종일 버튼쪽에서 에러가 발생하지 않았나요?

2022-07-17 14:40 UTC, daaaayeah commented on frontend/src/api/login.ts
> +  auth: async () => {
좋습니다 더 나은 이름이 생각난다면 공유하겠습니다!

2022-07-17 15:26 UTC, daaaayeah commented on frontend/src/components/@common/Button/Button.tsx
> +  cssProp?: SerializedStyles | (({ colors, flex }: Theme) => SerializedStyles);
나인 덕분에 다시 찬찬히 확인했는데 우리가 (특히 제가) css를 적용하는 방식이 일관되지 않았었네요!
cssProp은 필요한 값을 인자에 담아 넘겨주는 방식으로 작성하는 것으로 수정했습니다
[refactor: css 적용 방식 변경](https://github.com/woowacourse-teams/2022-dallog/pull/64/commits/6f54b255bbb334621efa2fbb0da6fc726db1bf7c)

2022-07-17 15:27 UTC, daaaayeah commented
> 저한테는 아직 이 PR에 대한 코드가 없어서 확인을 못해봤는데 종일 버튼쪽에서 에러가 발생하지 않았나요?

언급해 주신 부분에서 별다른 에러는 발생하지 않았었습니다!

2022-07-17 22:51 UTC, jhy979 commented on frontend/src/components/@common/Button/Button.tsx
> +  cssProp?: SerializedStyles | (({ colors, flex }: Theme) => SerializedStyles);
아 저도 놓친 부분이 많네요!

2022-07-17 22:52 UTC, jhy979 approved these changes
머지 승인하겠습니다 고생하셨어요~!

2022-07-18 04:15 UTC, merged