[refactor] 자신의 일정을 조회하는 기능을 개선한다.
woowacourse-teams/2022-dallog pull request #657
Opened 2022-09-22 08:32 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

불필요하게 잡고 있던 트랜잭션 시간을 최소화하기 위해 개선하였습니다.

```java
@Service
public class SubscribingSchedulesFinder {
    ...
    public MemberScheduleResponses findMySubscribingSchedules(final Long memberId, final DateRangeRequest request) {
        // Transaction 시작
        FindSchedulesMaterial material = scheduleService.findInternalByMemberIdAndDateRange(memberId, request);
        // Transaction 끝

        List<IntegrationSchedule> schedules = material.getSchedules();

        String refreshToken = material.getRefreshToken();
        String accessToken = toAccessToken(refreshToken);

        List<IntegrationSchedule> externalSchedules = toExternalSchedules(request, material, accessToken);
        schedules.addAll(externalSchedules);

        return new MemberScheduleResponses(material.getSubscriptions(), new TypedSchedules(schedules));
    }
    ...
}
```

## 스크린샷

## 주의사항

Closes #652

2022-09-22 09:23 UTC, summerlunaa requested changes
네이밍 관련해서 코멘트 조금 남겼어요! 같이 고민해볼까요?🤔

2022-09-22 09:23 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
> +    public MemberScheduleResponses findMySubscribingSchedules(final Long memberId, final DateRangeRequest request) {
이렇게 `SubscribingSchedulesFinder`를 만들었으니 Response 이름도 `SubscribingScheduleResponses`로 통일하면 어떻까요? `TypedSchedule`, `IntegrationSchedule`, `MemberSchedule` 등 여러 이름이 사용되니 헷갈리는 것 같아요🥲
아니면 `TypedScheduleResponses` 등도 괜찮을 것 같구요.

2022-09-22 09:23 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/FindSchedulesMaterial.java
> +public class FindSchedulesMaterial {
`MaterialToFindSchedule`, `MaterialForFindingSchedule` 등으로 바꾸면 어떨까요?
객체 이름이 `Find`라는 동사로 시작하니까 조금 어색한 것 같아요

2022-09-23 03:30 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 작성해주신 코드 잘보았어요!
subscribingScheduleFinder에 있던 로직들을 ScheduleService로 옮기면서 
subscribingScheduleFinder가 더욱 추상화되고 트랜잭션 분리가 더 깔끔해진것 같아요!!👍👍

지금 schedule 패키지 하위에 여러 도메인들 네이밍이 가지각색인데
이부분은 테스크로 잡고 진행해도 좋을것 같아요!

바로 approve하도록하겠습니다! 고생하셨습니다~

2022-09-23 03:30 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +
`FindSchedulesMaterial`에게 일정 조회를 위한 데이터들이 한번에 들어가는군요!!👍👍

2022-09-23 03:30 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
> +    public MemberScheduleResponses findMySubscribingSchedules(final Long memberId, final DateRangeRequest request) {
맞아요 저희가 아직 Schedule 관련한 여러 객체들이 네이밍이 통일되지 않아서 변경할 필요가 있을것 같아요.
이번에 전부 바꾸기 힘들것 같아서 파랑이 말씀해주신부분을 적용하고 
네이밍에 대해서도 테스크를 진행해도 좋을것 같아요!

2022-09-23 03:30 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
> +                accessToken, externalCategory.getId(), externalId, startDateTime, endDateTime);
트랜잭션 분리👍👍

2022-09-28 06:55 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/SubscribingSchedulesFinder.java
> +    public MemberScheduleResponses findMySubscribingSchedules(final Long memberId, final DateRangeRequest request) {
좋습니다! 통일하고 다시 요청하겠습니다.

2022-09-28 06:56 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/FindSchedulesMaterial.java
> +public class FindSchedulesMaterial {
동의합니다! 수정 하겠습니다~

2022-09-28 08:58 UTC, summerlunaa approved these changes
수정 확인했습니다! 수고하셨습니다 :)

2022-09-29 07:57 UTC, merged