[refactor] 토큰 발급시 AccessToken과 RefreshToken을 모두 발급한다.
woowacourse-teams/2022-dallog pull request #679
Opened 2022-09-29 08:28 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- 토큰 발급 요청시, 엑세스 토큰과 리프레시 토큰을 모두 발급 
- InMemoryTokenRepository를 통해 리프레시 토큰 발급

## 주의사항
- 우선은 적은 FileChanged를 유지하기 위해서 JwtTokenProvider를 통해 RefreshToken도 발급하도록 하였습니다.
- 토큰 발급시 RefreshToken을 InMemoryDb로 저장하도록 하였습니다.

Closes #677

2022-09-29 13:03 UTC, devHudi requested changes
안녕하세요, 리버!
수정되어야할 부분이 몇몇 존재해서 리뷰남깁니다. 확인부탁드려요!

2022-09-29 23:31 UTC, hyeonic requested changes
안녕하세요 리버! 매트입니다 😃

후디가 대부분 잘 남겨주셔서 저도 간단히 코멘트 남겼습니다! 확인해주시고 같이 이야기 나눠보면 좋을 것 같네요 ㅎㅎ 고생 하셨습니다 👍

2022-09-29 23:31 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
> +        assertThat(actual.getRefreshToken()).isNotEmpty();
```java
assertAll(() -> {
    assertThat(actual.getAccessToken()).isNotEmpty();
    assertThat(actual.getRefreshToken()).isNotEmpty();
});
```

`assertAll`을 통해 모든 메서드가 검증 되도록 유도하는 것은 어떨까요?

2022-09-29 23:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +    private final static Map<Long, String> TokenRepository = new HashMap<>();
추가적으로` private final static`이 아닌 `private static final`로 수정되어야 할 것 같습니다 😃

2022-09-29 23:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +public class InMemoryTokenRepository {
`InMemoryTokenRepository` 구현 잘 보았습니다! Refresh Token의 경우에도 `만료 시간`을 가지고 있는데요, 해당 부분은 어떤식으로 구현될 예정인가요??

2022-09-29 23:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +        return new TokenResponse(accessToken, refreshToken);
accessToken과 유사하게 생성되고 있네요! refresh token의 경우 payload의 값이 유의미하게 사용되지 않을 것이라 판단하는데, 추가적인 생성 메서드를 통해 access token과 refresh token의 생성 방식을 분리해보는 건 어떨까요??

추가적으로 refresh token을 어떠한 형식과 전략으로 가져갈 것인지 고민해보면 좋을 것 같습니다 😃

2022-09-30 02:09 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +    private TokenResponse createTokenResponse(final Member foundMember) {
변경하였어요!

2022-09-30 02:11 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +    private final static Map<Long, String> TokenRepository = new HashMap<>();
`ConcurrentHashMap` 로 변경하였어요~

2022-09-30 02:12 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +    private final static Map<Long, String> TokenRepository = new HashMap<>();
변경하였습니다!

2022-09-30 02:14 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/auth/application/AuthServiceTest.java
> +        assertThat(actual.getRefreshToken()).isNotEmpty();
수정하였어요~

2022-09-30 02:14 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +public class InMemoryTokenRepository {
이부분은 다음 issue에서 개선할예정입니다.
아직은 학습을 해봐야할 것 같아요!

2022-09-30 06:25 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +    private final static Map<Long, String> TokenRepository = new HashMap<>();
이부분도 수정해보았어요!

2022-09-30 06:55 UTC, devHudi approved these changes
리버, 고생 많으셨습니다!~ 동시성 이슈도 해결되고, DIP, OCP도 만족하는 코드가 되었네요. Approve 하겠습니다!

2022-09-30 06:55 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/InMemoryTokenRepository.java
> +public class InMemoryTokenRepository implements TokenRepository {
👍 스프링의 DI를 적극적으로 활용하여, 요구사항 변경에도 유연하게 대응할 수 있게 개선됐네요

2022-09-30 07:01 UTC, hyeonic approved these changes
안녕하세요 리버! 매트입니다 😃

이전 보다 훨씬 개선된 구조가 되었네요 ㅎㅎ 수정할 부분은 크게 보이지 않는데 간단히 확인해보면 좋은 포인트 남겨 두었습니다. 다음 태스크 진행할 때 참고해서 같이 진행해주세요~ 고생하셨습니다 👍

2022-09-30 07:01 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/common/config/TokenConfig.java
> +    }
추가적으로 Stub을 진행하지 않아서 불필요한 코드라 판단되네요!

2022-09-30 07:17 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/common/config/TokenConfig.java
> +    }
제거하였습니다!

2022-09-30 07:36 UTC, merged