[feat] 카테고리 역할 수정 API를 개발한다.
woowacourse-teams/2022-dallog pull request #688
Opened 2022-09-30 11:03 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- 카테고리를 생성한 시점에 해당 유저와 카테고리에 대해 ADMIN 역할을 자동으로 생성합니다.
- 구독자의 역할을 변경하는 API를 구현합니다. 이 API는 ADMIN 유저만 실행할 수 있습니다.
- 관리자 유저의 역할을 변경하는 API를 구현합니다. 이 API는 ADMIN 유저만 실행할 수 있습니다.
- 자신이 관리자 유저인 경우, 자신의 역할을 NONE으로 변경하는 API를 구현합니다.
- ADMIN 이 자기자신을 ADMIN이 아닌 역할로 변경할 때, 자기자신이 유일한 ADMIN 인 경우 권한을 변경할 수 없습니다.

## 스크린샷

## 주의사항

#678

2022-10-02 02:31 UTC, hyeonic approved these changes
안녕하세요 후디! 매트입니다 😃

프로덕션 코드와 테스트를 보며 굉장히 많은 고민을 했다는 것이 느껴지네요! 크게 수정할 부분은 없는 것 같네요. 몇 가지 의논하고 싶은 부분이 있는데 먼저 제 의견을 말씀드리겠습니다.

1. 카테고리 권한과 관련된 로직은 크게보면 category 패키지 안에 있어야 하는 로직이 아닌가? 생각이 문득 들었네요. 이 부분에 대해서 후디는 어떻게 생각하시나요?
2. 만약 하나의 카테고리에 두 명의 ADMIN이 존재할 경우, 서로의 권한을 동시에 내리거나 제거하면 어떻게 동작하나요?? 

남은 주말 잘 보내시고 찬찬히 확인해주십쇼! 고생하셨습니다 😃

2022-10-02 02:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
SoleAdmin이라는게 유일한 admin이라는 의미 인가요??

2022-10-02 02:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleType.java
> +    ADMIN(EnumSet.of(RENAME_CATEGORY, DELETE_CATEGORY, ADD_SCHEDULE, MODIFY_SCHEDULE, DELETE_SCHEDULE, MANAGE_ROLE)),
`EnumSet` 👍

일반적인 HashSet과 내부적으로 어떻게 다른지 알 수 있을까요??

2022-10-02 02:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/dto/request/CategoryRoleUpdateRequest.java
> +    }
사소하지만 `private`으로 제한해도 좋을 것 같네요!

2022-10-02 02:31 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
`MANAGE_ROLE`만 가지고 있으면 카테고리에 대한 관리 권한을 가지고 있다고 이해해도 괜찮을까요??

2022-10-02 02:31 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
> +        Member 구독자 = memberRepository.save(후디());
변수명이 굉장히 직관적이네요 ㅋㅋㅋ

2022-10-02 05:09 UTC, summerlunaa requested changes
카테고리 역할 수정 API 잘 보았습니다! 저번 PR은 제가 리뷰를 못했더라구요ㅠㅠ 저번 PR까지 확인하고 왔습니다!

추가적으로 
r: 1. 이제 내가 만든 카테고리라도 유일한 관리자가 아니라면 구독을 삭제할 수 있도록 해야할 것 같고,
a: 2. 관리자도 구독 해제할 수 있게 하기로 한 거 아니었는지 궁금합니다.

저번에 얘기했던 RCA 룰을 사용해서 리뷰해보았습니다.
```
r: 꼭 반영해 주세요 (Request changes)
c: 웬만하면 반영해 주세요 (Comment)
a: 그냥 사소한 의견입니다 (Approve)
```

2022-10-02 05:09 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
> +    }
a: 한 번에 여러명의 역할을 변경할 수는 없는 건가요?

2022-10-02 05:09 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
> +        Member 구독자 = memberRepository.save(후디());
ㅋㅋㅋㅋㅋㅋ

2022-10-03 06:03 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
맞아요!

2022-10-03 06:44 UTC, devHudi commented
@hyeonic 

1. 카테고리 권한과 관련된 로직은 크게보면 category 패키지 안에 있어야 하는 로직이 아닌가? 생각이 문득 들었네요. 이 부분에 대해서 후디는 어떻게 생각하시나요?

👉 저도 매트와 동일하게 고민한 지점입니다. Category와 밀접하게 관련되어있는데, 물리적으로 패키지를 분리하는 것이 맞을까? 라는 생각이 들었어요. 그런데 `CategoryRole` 은 `Category` 뿐 아니라 `Member` 와 도 동일한 수준으로 관련되어 있다고 생각합니다. **'카테고리' 역할**이지만, **'유저의' 카테고리 역할** 이기 때문이에요. 비슷한 예로 `Subscription` 이 있어요. `Subscription` 또한 관점에 따라 `Category` 에 종속적인 개념일수도 있지만, 마찬가지로 동일한 수준으로 `Member` 와도 관련이 있습니다. 현재 `Subscription` 은 별도의 패키지에 위치해있습니다. 비슷한 관점으로 `CategoryRole` 도 패키지를 분리했어요.

2. 만약 하나의 카테고리에 두 명의 ADMIN이 존재할 경우, 서로의 권한을 동시에 내리거나 제거하면 어떻게 동작하나요??

👉 오... 고민을 좀 해봐야할 것 같은데, 일단 기본적으로 MySQL이 REPEATABLE READ를 기본 격리 수준으로 가지고 있기 때문에 추측하건데, 동시성 이슈가 크게 발생하지 않을 것 같아요. 매트의 의견은 어떤가요?

2022-10-03 06:48 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleType.java
> +    ADMIN(EnumSet.of(RENAME_CATEGORY, DELETE_CATEGORY, ADD_SCHEDULE, MODIFY_SCHEDULE, DELETE_SCHEDULE, MANAGE_ROLE)),
https://www.baeldung.com/java-enumset

에 나와있는 것 같은데,,, 비트벡터? 😨 공부가 더 필요하겠네요

2022-10-03 06:49 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/dto/request/CategoryRoleUpdateRequest.java
> +    }
오 이런

2022-10-03 06:49 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
네이밍을 조금 헷갈리게 지었군요!.. 타인의 ROLE 을 MANAGE 한다는 의미에서 MANAGE_ROLE 이라고 이름 붙였습니다! 더 좋은 이름이 있을까요?

2022-10-03 06:49 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
> +        Member 구독자 = memberRepository.save(후디());
ㅋㅋㅋㅋㅋㅋㅋㅋ

2022-10-03 06:51 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/domain/CategoryRoleType.java
>      NONE(Set.of());
`EnumSet`이 빈 상태로 생성되는걸 허락하질 않네요 ㅠㅡㅠ

2022-10-03 06:51 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/presentation/CategoryController.java
> +    }
당장은 그렇습니다! 요구사항이 추가되면, 리스트로 전달받아 한번에 변경할 수 있도록 만들어야할 것 같습니다.

2022-10-03 06:52 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    private void validateSoleAdmin(final Long loginMemberId, final Long categoryId) {
반영했습니다! 앞으로 메소드 추출을 좀 더 꼼꼼히 해야겠군요 🙃

2022-10-03 07:11 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
CHANGE_ROLE 어떤가유

2022-10-03 07:13 UTC, summerlunaa approved these changes
변경사항 확인했습니다! 수고하셨어요ㅎㅎ👍

2022-10-03 07:19 UTC, merged