[refactor] RefreshToken의 만료시간을 2주로 변경한다.
woowacourse-teams/2022-dallog pull request #689
Opened 2022-10-01 11:31 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- RefreshToken의 만료시간을 2주로 변경하고 JWT로 암호화한다.

Closes #686

2022-10-02 03:34 UTC, hyeonic requested changes
안녕하세요 리버! 매트입니다 😃

적절히 잘 추가해주셨네요! 이제 어디서 저장하고 관리해야 할지에 대해서만 정리하면 될 것 같네요! 다만 아직 서브모듈이 private repository에는 반영이 안되어 있는 것 처럼 보여요! 저도 다시 한번 확인 해볼테니 추가적으로 점검해보면 좋을 것 같아요. 고생하셨습니다 🙇‍♂️

2022-10-02 04:31 UTC, summerlunaa requested changes
리버! 저번에 말했던 RCA 룰을 사용해서 리뷰를 남겨보았습니다ㅎㅎ
저번 PR은 제가 리뷰를 못했더라구요ㅠㅠ 저번 PR까지 확인하고 왔습니다!

```
r: 꼭 반영해 주세요 (Request changes)
c: 웬만하면 반영해 주세요 (Comment)
a: 그냥 사소한 의견입니다 (Approve)
```

2022-10-03 07:58 UTC, devHudi requested changes
RefreshToken과 AccessToken의 생성 로직을 분리하고, 각각 다른 유효기간을 설정했네요! 몇가지 수정하면 좋아보일 부분이 있어 코멘트 남겼습니다.

2022-10-03 07:58 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/application/JwtTokenProvider.java
> +        Date validity = new Date(now.getTime() + accessTokenValidityInMilliseconds);
`createRefreshToken()` 에서 동일한 로직이 반복되네요!

2022-10-03 07:58 UTC, devHudi commented on backend/src/main/resources/application-test.yml
> +        expire-length: 1210000000
요건 그냥 잘 몰라서 그런건데, yml 도 자바처럼 `_` 로 숫자 가독성을 좋게 만들 수 있나요?

2022-10-04 05:37 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/JwtTokenProvider.java
> +                .compact();
중복 로직을 메서드로 추출해보았어요!!

2022-10-04 05:48 UTC, gudonghee2000 commented on backend/src/main/resources/application-test.yml
> +        expire-length: 1210000000
주석을 통해 일과 시간에 대해 명시해보았어요!
accessToken은 1일 refreshToken은 14일로 설정하였어요😊

2022-10-04 05:55 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/auth/application/JwtTokenProviderTest.java
> +    void validateToken_메서드는_만료된_엑세스_토큰을_전달하면_예외를_던진다() {
오오! 메서드명을 명시하는것보다 직관적이군요!
수정해보았어요~

2022-10-04 05:58 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/JwtTokenProvider.java
> +        Date validity = new Date(now.getTime() + accessTokenValidityInMilliseconds);
수정해보았어요!!

2022-10-04 06:18 UTC, gudonghee2000 commented on backend/src/main/resources/application-test.yml
> +        expire-length: 1210000000
언더바를 추가해보았어요!
테스트 코드상으로는 잘돌아가는것 같은데.. 
검색해도 `_` 관련 문법은 안나와서 혹시 걱정이 조금 되긴하네요😔

2022-10-04 06:30 UTC, devHudi approved these changes
Approve 드릴게요! `application.yml` 같은 경우 `_` 를 넣으면 안될 것 같아서 이 부분만 수정해주시면 될 것 같습니다!

2022-10-04 06:31 UTC, hyeonic approved these changes
안녕하세요 리버! 서브모듈도 잘 적용 되었네요! 간단히 코멘트 남겼으니 확인해주세요! 간단한 로직이라 Approve 남깁니다 고생하셨습니다!

2022-10-04 06:31 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/auth/application/StubTokenProvider.java
> +    }
해당 부분 아래 createRefreshToken과 중복된 로직인데 개선해보면 더욱 좋을 것 같아요!

2022-10-04 06:44 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/auth/application/StubTokenProvider.java
> +    }
오오.. 생각 못하고있었네요!
`StubTokenProvider`에 대해서 중복로직을 제거해보았어요!!

2022-10-04 11:03 UTC, summerlunaa approved these changes
리버 수고하셨어요ㅎㅎㅎㅎ 코멘트 하나 달았는데 이것만 수정해주심 될 것 같아요!! 베리굳~~

2022-10-04 11:03 UTC, summerlunaa commented on backend/src/main/resources/application-test.yml
> +        expire-length: 3600000 #1시간
r: 1일인데 1시간으로 되어있네요 ;_; 그리고 다른 yml 파일에도 같이 주석 적어주면 좋을 것 같습니다! 이미 쓰셨다면 최고 ㅎㅎ 👍

2022-10-05 02:32 UTC, gudonghee2000 commented on backend/src/main/resources/application-test.yml
> +        expire-length: 3600000 #1시간
테스트 야물 파일은 1시간이 맞아요!😊
다른 config 파일들은 1일과 14일로 주석을 처리하였습니다!

2022-10-05 02:33 UTC, merged