[feat] 단건 카테고리의 스케줄을 월별로 조회한다.
woowacourse-teams/2022-dallog pull request #691
Opened 2022-10-03 04:04 UTC by hyeonic

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

단건 카테고리의 스케줄을 월별로 조회한다.

## 스크린샷

## 주의사항

Closes #671

2022-10-03 04:11 UTC, devHudi requested changes
안녕하세요, 매트! 개천절인데도 열심히군요 👍
고민해보면 좋을 부분에 코멘트 달아두었습니다!

2022-10-03 04:11 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        return scheduleRepository.getByCategoriesAndBetween(List.of(category), startDateTime, endDateTime);
오버로딩된 `toIntegrationSchedules()` 메소드가 각각 다른 위치에 존재해서 조금 헷갈리네요! 둘을 붙여놓는 것은 어떨까요?

2022-10-03 04:11 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> +
원래는 멤버의 월별 스케줄을 보여줄 때에만 사용되던 DTO라 그런지 이름이 `MemberScheduleResponses` 네요! 지금은 멤버의 스케줄이 아니더라도 보여줄 수 있으니 조금 더 범용적인 이름이 필요할 것 같아요.

2022-10-03 04:11 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        Color color = Color.pick(colorPicker.pickNumber());
카테고리 일정을 조회할 때 마다 랜덤으로 색상이 보여지는 것 일까요?

2022-10-03 04:32 UTC, summerlunaa requested changes
단건 카테고리 스케줄 월별 조회! 확인했습니다 👍
몇 부분 리뷰 남겼으니 확인부탁드려요~

```
r: 꼭 반영해 주세요 (Request changes)
c: 웬만하면 반영해 주세요 (Comment)
a: 그냥 사소한 의견입니다 (Approve)
```

2022-10-03 04:32 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        Color color = Color.pick(colorPicker.pickNumber());
a: default color를 사용하는 게 좋을지 매번 랜덤으로 보여주는 게 좋을지 모르겠네요🤔

2022-10-03 04:32 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> +
r: 후디 의견에 동의합니다!

2022-10-03 04:32 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> +
r: 위 메서드와 로직이 완전히 겹치네요! 둘 중 하나에서 다른 하나를 호출하는 것으로 변경하면 중복을 줄일 수 있을 것 같아요.

2022-10-03 11:03 UTC, gudonghee2000 requested changes
안녕하세요 매트! 작성해주신 코드 잘보았습니다🙂
이전 PR들에 대해 리뷰를 드렸어야 했는데..😔

작성해주신 기능들과 꼼꼼한 테스트 코드들 모두 확인하였어요!
특히, ControllerTest를 작성하기 번거로우셨을 텐데 꼼꼼하게 작성해주신 모습이 정말 인상깊었습니다😊

다른분들과 공통되는 의견에 대해서 리뷰를 남겨보았습니다!

2022-10-03 11:03 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/schedule/application/ScheduleServiceTest.java
> +    }
꼼꼼하게 검증 해주셨군요!!👍👍

2022-10-03 12:06 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        Color color = Color.pick(colorPicker.pickNumber());
default color 정보를 어디서 가져오는게 좋을까요?? 저희가 카테고리 저장할 때 따로 color 정보를 지정하지 않아서요. 아니면 그냥 특정 color를 고정하여 보여주는 식으로 가야 할까요??

2022-10-03 12:07 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> +
네 기존 dto 이름을 좀 더 범용적으로 사용하도록 개선해볼게요!

2022-10-03 12:07 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/MemberScheduleResponses.java
> +
위 메서드는 사실 필요가 없어보이네요. 중복 제거하는 쪽으로 개선해보겠습니다!

2022-10-04 04:16 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        Color color = Color.pick(colorPicker.pickNumber());
무슨 색상이 좋을까요??

2022-10-04 04:41 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 
추가로 수정해주신 부분들 모두 확인하였어요!!

정말 고생하셨습니다❗❗
approve하였습니다~

2022-10-04 04:44 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/application/ScheduleService.java
> +        Color color = Color.pick(colorPicker.pickNumber());
프론트랑 상의해보면 좋을 것 가타유

2022-10-04 04:48 UTC, summerlunaa requested changes

2022-10-04 04:48 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/schedule/dto/response/IntegrationScheduleResponses.java
> +    }
이렇게 하면 좋을 것 같아요 :)
```suggestion
        return getColoredScheduleResponses(scheduleType, subscriptions.findColor(schedule), typedSchedules);
    }
```

2022-10-04 05:37 UTC, summerlunaa approved these changes
앗 중복 로직에 대한 부분 합칠 수 없다는 설명 이해했습니다! approve 합니다 :)

2022-10-04 06:14 UTC, devHudi approved these changes
Approve 드립니다 매트!

2022-10-04 06:15 UTC, merged