schedules의 시작/종료 일시의 db에서의 타입을 timestamp에서 datetime으로 변경한다.
woowacourse-teams/2022-dallog pull request #697
Opened 2022-10-04 04:30 UTC by summerlunaa

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- schedules의 start, end date time의 타입을 timestamp에서 datetime으로 변경한다.
- category_roles create table schema 추가

## 주의사항

- merge 시 db migration과 yml 파일 변경을 함께 해주어야 합니다!!

Closes #680

2022-10-04 05:33 UTC, devHudi requested changes

2022-10-04 05:33 UTC, devHudi commented on backend/src/main/resources/db/prod/schema.sql
>    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
(구두로 나눈 내용) `start_date_time` 과 `end_date_time` 이 `datetime` 으로 변경된다면, 다른 테이블의 `created_at` 과 `updated_at` 도 `datetime` 으로 변경하면 어떨까요?

2022-10-04 06:44 UTC, summerlunaa commented on backend/src/main/resources/db/prod/schema.sql
>    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
그렇네요 이왕이면 created_at과 updated_at도 datetime으로 변경해주면 서버 타임에 따라 시간을 헷갈일 일이 줄어들 것 같아요. 바꾸는 김에 함께 변경하도록 하겠습니다.

2022-10-04 23:21 UTC, hyeonic approved these changes

2022-10-04 23:21 UTC, hyeonic commented on backend/src/main/resources/db/prod/schema.sql
> +  updated_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
datetime(6)이 의미하는게 무엇인가요?? 또한 위 형식에 맞춰서 대문자로 통일해도 좋을 것 같네요!

2022-10-05 03:39 UTC, summerlunaa commented on backend/src/main/resources/db/prod/schema.sql
> +  updated_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
괄호 안의 숫자는 소수점 자리수입니다. 기본이 datetime(6)인데 created_at, updated_at의 경우 세세할 수록 좋을 것 같아서 이렇게 두었어요.

2022-10-05 03:48 UTC, gudonghee2000 approved these changes
안녕하세요 파랑! 
변경해주신 스키마의 시간관련 데이터 타입 모두확인하였어요!👍👍

괄호안에 숫자는 소수점 자리 처리를 위해서 이군요!
바로 APPROVE하였습니다! 정말 고생하셨습니다~

따로 두가지 질문사항 남겨보았어요!
1. timestamp에서 datetime으로 변경한 이유가 timestamp가 2038년까지만 사용가능한 이유이외에도 더있는걸까요??

2. created_at에서 소수점 자리를 지정해주신 이유가 어떤걸까요??

2022-10-05 23:30 UTC, hyeonic commented on backend/src/main/resources/db/prod/schema.sql
> +  updated_at datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
날짜 형식에서 소수점이 필요한 부분이 명확하게 이해가 되지 않네요 🥲 저희가 필요한 것은 년월일시분초 정도 아닌가요?? 밀리초 단위 까지 저장할 것을 의도하신 건가요??

2022-10-06 07:28 UTC, devHudi approved these changes
리뷰가 늦었네요 ㅠㅠ approve 드리겠습니다!

2022-10-07 12:09 UTC, merged