[feat] 카테고리 ADMIN 역할을 포기하더라도 자신이 생성한 카테고리라면 구독 해제가 안되는 문제를 해결한다.
woowacourse-teams/2022-dallog pull request #713
Opened 2022-10-05 06:22 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- 카테고리 ADMIN 역할을 포기하더라도 자신이 생성한 카테고리라면 구독 해제가 안되는 문제를 해결한다.
- PERSONAL, GOOGLE 타입의 카테고리는 역할을 포기할 수 없도록 만든다.

## 스크린샷

## 주의사항

Closes #711

2022-10-05 06:45 UTC, hyeonic requested changes
안녕하세여 후디

간단히 객체 내부로 옮길 수 있는 로직 찾아보았습니다. 찬찬히 살펴보시고 반영해주십쇼

2022-10-05 06:45 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
>      }
category 내부로 로직을 이동하는건 어떨까요?

2022-10-05 06:45 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
> +            throw new NoPermissionException("타인의 구독 정보에 접근할 수 없습니다.");
이거도 member 쪽으로 위임가능할 것 같네요!

2022-10-05 06:45 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
>      }
오 그렇네요! 반영하겠습니다.

2022-10-05 06:47 UTC, hyeonic commented
추가적으로 현재 category와 category role 패키지가 강하게 의존하고 있어요! 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/59357153/193997823-360cc70e-002a-4efa-90d1-e28274e5ad76.png">

관련해서 로직을 옮기던 패키지를 단뱡향으로 의존하는 방향에 대해서도 고려해보면 좋을 것 같네요 😃

2022-10-05 08:33 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/subscription/domain/Subscription.java
> +            throw new NoPermissionException("타인의 구독 정보에 접근할 수 없습니다.");
헉 멤버쪽에 `hasSameId()` 가 있었네요! 변경했습니다!

2022-10-06 03:47 UTC, gudonghee2000 approved these changes
안녕하세요 매트! 작성해주신 기능 잘보았어요!!
로직도 깔끔하고 테스트코드도 꼼곰하게 작성해주셔서 변경사항이 보이지 않네요!

바로 approve 하였습니다!

2022-10-06 03:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/subscription/application/SubscriptionService.java
> -    private void deleteSubscription(final Long id, final Long memberId, final Subscription subscription) {
불필요한 로직이 제거되었군요!👍👍

2022-10-06 03:47 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/global/error/ControllerAdvice.java
> +            NotAbleToChangeRoleException.class
더욱 명확한 네이밍이군요!👍👍

2022-10-06 03:47 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleServiceTest.java
> +    void 외부_카테고리에_대한_회원의_역할을_변경할_경우_예외가_발생한다() {
꼼꼼한 테스트 코드군요!!

2022-10-06 03:47 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/subscription/application/SubscriptionServiceTest.java
> -
불필요한 테스트코드가 삭제되었군요!

2022-10-06 05:27 UTC, summerlunaa approved these changes
확인했습니다! 앞에서 매트가 리뷰 잘 해주신 것 같네요 ㅎㅎ 굳굳

2022-10-06 07:16 UTC, hyeonic approved these changes
LGTM 👍

2022-10-06 07:20 UTC, merged