[refactor] AuthService의 전체 메서드를 리팩터링한다.
woowacourse-teams/2022-dallog pull request #724
Opened 2022-10-06 07:29 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- AuthService의 메서드 간소화
- Dallog의 Token관련 로직을 `DallogTokenManager`로 분리

Closes #712

2022-10-06 07:39 UTC, devHudi requested changes
안녕하세요, 리버! `AuthService` 의 코드가 길어 별도의 빈을 만들어 분리하셨군요. 
개인적인 생각으로는 빈을 만들어 단순히 로직을 옮기는 것 보다 적절한 책임을 수행하는 도메인 객체를 만들어 개선해봄이 어떨까 하는 생각입니다. 개인적인 의견이니 꼭 반영해주지 않으셔도 괜찮을 것 같아요.

그 외로 사소하게 수정해보면 좋을 부분에 코멘트 달았습니다. 확인 부탁드릴게요!

2022-10-06 07:39 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +        Long memberId = Long.valueOf(tokenProvider.getPayload(outRefreshToken));
`outRefreshToken` 이 무엇일까요?

2022-10-06 07:39 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +public class DallogTokenManager implements TokenManager {
`DallogTokenManager` 를 분리한 이유가 무엇인가요?

2022-10-06 07:39 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +public class DallogTokenManager implements TokenManager {
클린코드에 따르면 Processor, Manager, Super 와 같은 모호한 네이밍을 지양하라고 적혀있는데요, 조금 더 명확한 이름으로 변경해보면 좋을 것 같아요.

2022-10-06 07:39 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/DallogToken.java
> +    }
액세스 토큰과 리프레시 토큰 쌍을 관리하는 도메인 객체가 생겼네요 👍

2022-10-06 08:12 UTC, hyeonic approved these changes
안녕하세요 리버! 매트입니다 😃

빈으로 분리하신 것 잘 봤습니다! 후디가 남긴 것 처럼 일반적인 객체를 활용하면 더욱 좋겠지만 아무래도 필드로 활용하다보니 여기까지 오게 된 것 같네요! 저도 로직 상 크게 문제될 부분 없으면 좀 더 고민하시고 편안 방향으로 진행하시져! 고생하셧슴다 🙇‍♂️

2022-10-06 08:12 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/DallogToken.java
> +public class DallogToken {
직관적이긴 한데, 좀 더 범용적인 이름은 어떤가요?? Auth라던가,, Auth라던가,, Auth,,

더 좋은 이름은 아직 떠오르지가 않네요 ㅜㅠ

2022-10-06 08:12 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/presentation/MemberControllerTest.java
> +    }
다시 돌아왔네요 ᄏﾻ

2022-10-07 08:40 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +        Long memberId = Long.valueOf(tokenProvider.getPayload(outRefreshToken));
현재는 `outRefreshToken`를 `refreshToken`으로 변경하고

메서드의 지역변수를 `refreshToken` 에서 `refreshTokenForRenew`로 변경하였어요~ 
더 적절한 네이밍이 있을거 같은데 떠오르지 않네요😔
(사실 이거 변경하겠다고 로직을 바꾸다가 전부 롤백해버린 슬픈경험을 했네요...)

2022-10-07 08:46 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +public class DallogTokenManager implements TokenManager {
기존에는 `AuthService`에서 `TokenProvider`와 `TokenRepository`의 의존성을 가지고 있었어요!
그러다 보니 `AuthService`의 로직이 꽤많이 비대했었는데요!
그래서 `Dallog 토큰`과 관련한 기능들을 `DallogTokenManager`분리 하는게 좋겠다고 생각이 들어서 
분리해보았어요!

2022-10-07 08:50 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/application/DallogTokenManager.java
> +public class DallogTokenManager implements TokenManager {
네이밍을 `TokenCreator`로 변경해보았는데요!
현재는 `TokenCreator` 토큰 생성, 토큰 갱신, 페이로드 추출 3가지 일을하고 있는데
적절한 네이밍이 잘 떠오르지 않네요😔

2022-10-07 08:52 UTC, gudonghee2000 commented on backend/src/main/java/com/allog/dallog/domain/auth/domain/DallogToken.java
> +public class DallogToken {
`Auth`가 더 적절해보여 변경해보았어요!
Dallog라던가.. Dallog 라던가.. Dallog

2022-10-09 12:18 UTC, devHudi approved these changes
주말에도 버닝이군요 리버!! 늦게 확인해서 죄송해요ㅠ Approve 드리겠습니다!

2022-10-09 12:29 UTC, merged