[feat] 데이터베이스 다중화를 적용한다.
woowacourse-teams/2022-dallog pull request #808
Opened 2022-10-15 15:32 UTC by devHudi

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

데이터베이스 레플리케이션을 적용하였습니다.

### 인프라

- Dev용 Source/Replica 데이터베이스 인스턴스 구축
- Prod용 Source/Replica 데이터베이스 인스턴스 구축

## 스크린샷

## 주의사항

Closes #714

2022-10-15 15:33 UTC, devHudi commented
레플리케이션에 대한 내용은 제 블로그 포스팅 https://hudi.blog/database-replication-with-springboot-and-mysql/ 을 참고해주세요!

2022-10-16 02:14 UTC, hyeonic requested changes
안녕하세요 후디! 드디어 삽질하던 다중화가 진행되고 있네요. 어제 트러블 슈팅 하던 OSIV 설정이나 데이터소스 관련 설정이 아직 적용이 안된 것 같은데 확인 한 번 부탁드려요 😃

고생하셨습니다 🙇‍♂️

2022-10-16 02:14 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +    @Qualifier(SOURCE_SERVER)
`@Qualifier`는 유지하는 방향으로 가는 건가요?!

2022-10-16 02:14 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +@Profile({"prod", "dev"})
dev도 레플리케이션이 적용되는건가요? 아님 어제 이야기 나눈 것 처럼 동일한 데이터소스 정보를 기입할 예정인가요?

2022-10-16 02:14 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +                return "replica";
키 값은 빈 생성할 때도 사용되서 상수로 관리해도 괜찮을 것 같네요! 아니면 `SOURCE_SERVER`나 'REPLICA_SERVER'를 활용하는 방법도 좋구요 😃

2022-10-17 05:30 UTC, gudonghee2000 approved these changes
안녕하세요 후디! 작성해주신 DB 레플리케이션 적용 코드 잘보았어요!!

블로그에 정리해주신 글을 통해 로직에 대해서 자세하게 이해할수 있었어요😊😊
OSIV 문제가 있었군요!!

매트가 대부분 피드백 남겨주셔서 댓글만 조금 달아보았어요!

바로 APPROVE 하겠습니다! 
정말 고생하셨습니다~

2022-10-17 06:57 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +                return "replica";
기존에 생성된 상수를 활용했습니다!

2022-10-17 06:57 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +@Profile({"prod", "dev"})
`dev` 도 `prod` 와 동일하게 레플리케이션 환경을 설정해두었습니다.

2022-10-17 06:57 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +    @Qualifier(SOURCE_SERVER)
넵 큰 문제 없을 것 같아 유지할 생각입니다!

2022-10-17 07:17 UTC, summerlunaa approved these changes
후 DB 다중화 중간에 트러블 슈팅 한다고 고생하셨습니다!! 코드랑 블로그까지 모두 확인했어요. 수고하셨습니다~

2022-10-17 07:17 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/global/config/DataSourceConfiguration.java
> +        return new LazyConnectionDataSourceProxy(determinedDataSource);
[LazyConnectionDataSourceProxy 알아보기](https://sup2is.github.io/2021/07/08/lazy-connection-datasource-proxy.html)
처음 알았네요!

2022-10-17 12:01 UTC, hyeonic approved these changes

2022-10-20 02:10 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceKey.java
> +    REPLICA_2(KeyName.REPLICA_2_NAME, true);
`AbstractRoutingDataSource` 에서 string 대신 enum 을 key로 사용하는것이 좋아보여서 따로 enum 클래스를 만들었습니다.

2022-10-20 02:44 UTC, hyeonic approved these changes
안녕하세요 후디! 레플리카 삽질하느라 고생하셨습니다 😃

간단히 코멘트 남겼으니 확인해주세요! 고생하셨습니다 🙇‍♂️

2022-10-20 02:44 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/replication/CircularReplicaKeyList.java
> +}
`CircularReplicaKeyList`처럼 자료구조의 이름을 명시하는 것 보다 `CircularReplicaKeys` 같은 이름은 어떤가요?

2022-10-20 02:44 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/replication/CircularReplicaKeyList.java
> +}
`cursor` 필드를 살펴보면 완벽하게 격리되지 않아 아래와 같은 상황이 생길 수도 있을 것 같아요.

```
1
1
0
0
0
0
1
0
1
...
```

이 부분은 크게 신경 쓰지 않아도 된다고 판단하여 위 같이 작성하신 건가요?

2022-10-20 02:44 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceConfiguration.java
> +        HashMap<Object, Object> dataSourceMap = new HashMap<>();
사소하지만 참조 객체가 구현 객체를 명시하고 있네요! 또한 런타임 시점에 추가적으로 Map의 엘리먼트를 추가할 일이 없다면 `Map.of()`를 활용하는 것도 좋을 것 같아요 😃

간단한 부분이라 그냥 참고만 해주세요.

2022-10-20 02:44 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceConfiguration.java
> +    }
해당 메서드의 위치를 `sourceDataSource()`, `replica1DataSource()`, `replica2DataSource()` 보다 위에 위치시키는 건 어떨까요??

2022-10-20 02:44 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceKey.java
> +    }
이왕 `slave` 없애는 김에 `isReplica`로 수정하는 것도 좋을 것 같네요!

2022-10-20 03:30 UTC, devHudi commented
@hyeonic 

> CircularReplicaKeyList처럼 자료구조의 이름을 명시하는 것 보다 CircularReplicaKeys 같은 이름은 어떤가요?

`CircularReplicaKeys` 로 변경했습니다. 기본적인건데 ㅎㅎ;;

2022-10-20 03:42 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceConfiguration.java
> +        HashMap<Object, Object> dataSourceMap = new HashMap<>();
Map.of 를 사용하여 개선했습니다.

2022-10-20 03:42 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceConfiguration.java
> +    }
좋아요!

2022-10-20 06:49 UTC, gudonghee2000 approved these changes
안녕하세요 후디! 작성해주신 로직 잘보았어요!!
몇가지 조그마한 의견만남겨보았습니다~

정말 고생하셧습니다!👍👍

2022-10-20 07:20 UTC, summerlunaa approved these changes
DB를 Enum으로 관리하는 게 불편해보이긴 하네요🥲
하지만 지금으로선 replica db가 추가될 일이 없어 괜찮을 것 같아요! approve 합니다.
성능 측정하신다고 고생하셨어요🥳

2022-10-20 07:20 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/global/config/replication/DataSourceConfiguration.java
> +    @ConfigurationProperties(prefix = "spring.datasource.source")
https://sgc109.github.io/2020/07/07/spring-boot-configuration-properties/
ConfigurationProperties를 이렇게도 쓸 수 있군요! properties를 받아와서 자동으로 DataSource 만들 때 넣어주나 보네요. 신기합니다.

2022-10-20 07:20 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/global/config/replication/RoutingDataSource.java
> +        return SOURCE;
사용할 DataSource를 정해주는 군요. good!

2022-10-20 07:53 UTC, devHudi commented on backend/src/main/java/com/allog/dallog/global/config/replication/RoutingDataSource.java
> +    @Override
메서드에 이 코드를 두게 되면 항상 `RandomReplicaKeys` 의 인스턴스가 생성되므로 필드로 두었습니다.

2022-10-20 07:57 UTC, merged