[perf] 불필요한 렌더링을 최소화한다.
woowacourse-teams/2022-dallog pull request #893
Opened 2022-10-27 03:15 UTC by daaaayeah

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

커밋 확인 부탁드립니다 🍅

## 주의사항

달력에서의 불필요한 리렌더링을 줄이려고 했습니다
아직 코드 측면에서는 보완할 부분이 남았다고 생각해요 😇

Closes #635

2022-10-27 19:54 UTC, jhy979 requested changes
티거!!! 엄청나게 고생하셨을 것 같아요.

덕분에 리렌더링을 많이 줄일 수 있었을 것 같아요.

코멘트 남겼는데 확인 부탁드려요~👏👏

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/NavBar/NavBar.tsx
> +        {accessToken && <SideBarButton />}
오 사이드바 버튼도 아예 분리하셨네요? 리렌더링이 덜 발생하겠군요👍

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.tsx
> +  schedulesWithPriority,
리렌더링 방지를 위해서 빼다보니 props가 굉장히 많아졌어요.

`currentMonth, calendarWithPriority, schedulesWithPriority, ...`
한 번만 계산하기 위해서 위해서 부모에서 내려주는 느낌인것 같아요.

> props 파트가 복잡하다보니 사용이 어렵다는 생각이 드는데요, `domain/schedule.ts`로 이러한 내용들이 들어감 + recoil 적극 활용 으로 복잡성을 줄일 수 있지 않을까요?

`  hoveringId`

hoveringId가 현재 `hoveringId === schedule.id` 이런식으로 현재 호버링이 되어있는지 스타일에서만 사용되고 있는 것 같아요.

지금처럼 hoveringId를 넘겨주면 hoveringId가 바뀔때마다 모든 Datecell 컴포넌트가 리렌더링 발생할 것 같아요.

만약 hoveringId를 isHovering으로 바꿔준다면 `true,false`값을 가지게 되고 이를 memoization 기법을 활용한다면 props가 변하지 않을때 리렌더링을 조금 더 줄일 수 있지 않을까 싶어요? (근데 뇌피셜이라 마즐지 모르겠네요)

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.tsx
> +          </div>
> 일단 skip

이 부분도 나중에 longTerms / allDays, fewHours 타입을 지정해서 뺄 수 있을 것 같네요.

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.tsx
> +      {dateTime === moreScheduleDateTime && (
> 뇌피셜🤦‍♂️

`Datecell` 컴포넌트로 분리해서
 `moreScheduleDateTime` 과 `dateTime` 을 비교해야하는 로직이 이제는 필요없지 않을까요?

어짜피 DateCell마다 정해진 dateTime이 있어서 그 값이 늘 `moreScheduleDateTime`과 같을 것 같은데 맞을까여

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +              />
컴포넌트 분리는 편안😙

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/ScheduleAddButton/ScheduleAddButton.styles.ts
> +  opacity: 0.8;
기본적으로 약간 투명하게 만드셨군요~

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/domains/schedule.ts
> +  const calendarWithPriority = calendar.reduce((acc: Record<string, boolean[]>, cur) => {
하핳 부끄럽네요🤦‍♂️

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.tsx
> +  const handleMouseEnterSchedule = (scheduleId: string) => {
이게 맞죠😝

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.styles.ts
> +  display: ${priority && priority >= maxScheduleCount ? 'none' : 'block'};
스타일도 네이밍 수정 굿

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.styles.ts
> +  background: ${typeof colorCode === 'string' ? colorCode : colors.ORANGE_500};
`colorCode`가 string과 boolean을 받을 수 있는 것은 조금 의아하네요.

`readOnly` 속성을 이용하여 ORANGE 색상을주는것이 더 좋지 않을까요?

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.tsx
> +              readonly || schedule.colorCode
급 드는 의문인데 인자 순서의 기준이 무엇인가요?

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +                toggleScheduleAddModalOpen={toggleScheduleAddModalOpen}
props 순서를 변경하셨는데 순서 기준이 어떻게 되나요?

2022-10-27 19:54 UTC, jhy979 commented on frontend/src/components/DateCell/DateCell.styles.ts
> +  background: ${typeof colorCode === 'string' ? colorCode : colors.ORANGE_500};
```ts
...
css={itemWithBackgroundStyle(theme, readonly || el.schedule.colorCode)}
...
```

사용하는 파트를 보면 괜찮아 보이는데 막상 스타일 코드를 보니 의아하네여

그냥 의견이라서 이건 반영안하셔도 좋아요✋

2022-10-28 05:21 UTC, daaaayeah commented on frontend/.prettierrc.json
> +    "@/domains",
넵 이야기 나눴던 것처럼 중복되는 로직 중 커스텀 훅 또는 유틸 함수로 분리하지 못하는 것들을 넣는 디렉토리입니다 🙃
도메인 로직을 모두 넣는 것으로 확대할 수도 있을 것 같고요~!

2022-10-28 05:22 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.tsx
> +  toggleScheduleAddModalOpen,
동의합니다 이벤트 핸들러로서 확장성 있는 네이밍으로 변경했어요!

[refactor: 날짜 셀 컴포넌트의 클릭 이벤트 핸들러 prop명 변경](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/0571d31c09c298d15fbe1f336602fac5eb88fe13)

2022-10-28 05:24 UTC, daaaayeah commented on frontend/src/pages/CalendarPage/CalendarPage.styles.ts
> +  width: ${isEndDate ? '97%' : '100%'};
[style: long term 일정의 width 변경](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/4bb20582fe4a0de6fb8096ee6a23043debef30e2) 😅

2022-10-28 05:25 UTC, daaaayeah commented on frontend/src/components/NavBar/NavBar.tsx
> +        {accessToken && <SideBarButton />}
넵 계속 번쩍여서 신경 쓰였어요 🤢

2022-10-28 08:23 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.tsx
> +      {dateTime === moreScheduleDateTime && (
오 맞아요~! 신경 쓰지 못했는데 짚어 주셔서 고마워요 🥺

2022-10-31 07:47 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.styles.ts
> +  background: ${typeof colorCode === 'string' ? colorCode : colors.ORANGE_500};
> colorCode가 string과 boolean을 받을 수 있는 것은 조금 의아하네요.

wow 동의합니다 boolean 값이 colorCode가 될 수 있단 건 누구도 예측하지 못할 것 같아요!

카테고리 페이지의 schedule도 불필요하게 colorCode를 가지고 있네요 🥲
인자를 하나 더 늘리는 건 이미... 많아서... 코드 가독성 측면에서 더 좋지 않을 것 같아요.. 🤯
카테고리 페이지에서는 빈 문자열을 넘기고 스타일 코드에서 처리하도록 수정하였습니다

[refactor: 일정 색상 타입 변경](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/53659ed0e20f0fc143b0c68476df3cdc135d98b4)

2022-10-31 07:51 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.tsx
> +              readonly || schedule.colorCode
읽기 편하도록 스타일 코드 내부에서 사용하는 순서대로 정렬하였습니다
colorCode는 readonly 인 경우 신경 쓰지 않는 값이라 맨 뒤로 배치했어요 😮

2022-10-31 07:55 UTC, daaaayeah commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +                toggleScheduleAddModalOpen={toggleScheduleAddModalOpen}
이 두 개는 readonly가 아닌 경우에만 필요한 props예요 🙃
그래서 DateCell 컴포넌트 내부에서 이 props를 뒤에 배치하였습니다

전체적으로 필수 props -> optional props 순서를 따르고, 그 안에서는 사용되는 순서에 따라 정렬하였습니다

2022-11-01 05:32 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.tsx
> +  schedulesWithPriority,
> 리렌더링 방지를 위해서 빼다보니 props가 굉장히 많아졌어요.

🤢

> `currentMonth, calendarWithPriority, schedulesWithPriority, ...`
한 번만 계산하기 위해서 위해서 부모에서 내려주는 느낌인것 같아요.

넵 맞습니다
바뀌면 자식 컴포넌트의 리렌더링이 필요하기 때문에 한 번만 계산하는 게 좋다고 생각했어요~!

> props 파트가 복잡하다보니 사용이 어렵다는 생각이 드는데요, domain/schedule.ts로 이러한 내용들이 들어감 + recoil 적극 활용 으로 복잡성을 줄일 수 있지 않을까요?

`currentMonth, calendarWithPriority, schedulesWithPriority, ...`에 대해서도 recoil을 활용하는 게 더 나을까요?!
domain 폴더에는 `getSchedulePriority` 안에 들어있습니다 🙃

> hoveringId가 현재 hoveringId === schedule.id 이런식으로 현재 호버링이 되어있는지 스타일에서만 사용되고 있는 것 같아요.
>
> 지금처럼 hoveringId를 넘겨주면 hoveringId가 바뀔때마다 모든 Datecell 컴포넌트가 리렌더링 발생할 것 같아요.
> 
> 만약 hoveringId를 isHovering으로 바꿔준다면 true,false값을 가지게 되고 이를 memoization 기법을 활용한다면 props가 변하지 않을때 리렌더링을 조금 더 줄일 수 있지 않을까 싶어요? (근데 뇌피셜이라 마즐지 모르겠네요)

호호 이건 얘기를 많이 나눴죠
말씀해 주신 `isHovering`으로는 더 나은 개선법을 찾지 못해서 일정을 컴포넌트로 분리하는 것으로 리렌더링을 줄여봤습니다!

[refactor: 달력 셀에서 일정 컴포넌트 분리](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/0ab513cb514acf211881b4576fac02737cba8864)

2022-11-01 05:32 UTC, daaaayeah commented on frontend/src/components/DateCell/DateCell.tsx
> +          </div>
no skip 좋아요 ☺️

[refactor: 달력 셀에서 일정 컴포넌트 분리](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/0ab513cb514acf211881b4576fac02737cba8864)

2022-11-01 11:41 UTC, daaaayeah commented
wow 모아두고 보니 PR 하나에 코드 변경이... 너무하네요 🤢
그래도 이슈 나누지 않기로 했으니 이 PR에서 끝내버리겠습니다
추가된 커밋만 확인해 주시면 될 것 같아요~!
나인 최고 🌈

[refactor: 달력 페이지에서 달력 컴포넌트 분리](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/86c128d61345be2cd5469c729c0c3403d8fe2e11)
[refactor: 카테고리 페이지에 달력 컴포넌트 사용](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/1283ce9d977980119ac9efa26236a5105894d5d6)
[style: 카테고리 관리 컴포넌트의 align 변경](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/a461713aa50e2c0958144c075c2eb1df893a3c36)
[perf: 카테고리 관리 컴포넌트의 불필요한 리렌더링 방지](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/41b574cb802831cbf748af4ce90c755b958d8507)

2022-11-01 20:11 UTC, jhy979 requested changes

2022-11-01 20:11 UTC, jhy979 commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
스피너를 띄울때에는 `          {category?.id !== 0 && ` 이렇게 하셨는데

`category && !category.id` 부분도 `!category?.id` 이렇게 할 수 있나요?

2022-11-01 20:11 UTC, jhy979 commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +  readonly = false,
기본값  챙기는 거 좋네요👍

2022-11-01 20:11 UTC, jhy979 commented on frontend/src/hooks/useCalendar.ts
>  export default useCalendar;
`useCalendar` 커스텀훅이 조금 거대해졌지만, 캘린더를 위한 로직들이 전부 들어 있어서 개인적으로 더 좋아진 것 같아요. 예전에는 어떤 부분이 useCalendar에 담겨있을지 몰랐는데 현재는 달력과 관련된 로직이면 useCalendar를 떠올릴 것 같네요👍👍

2022-11-01 20:11 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
이 처리를 하나의 return 에서 하지말고

위에서 early return을 걸어주는건 어떠신가요?

`if(isLoading || data === undefined) return <CalendarFallback ...>`

2022-11-01 20:11 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
혹시 일정 추가 모달때문에 그러신건지..?

2022-11-01 20:13 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
혹시 일정 추가 모달이나 PageLayout같은 스타일 속성을 공통으로 이용하고 있어서 그러신걸까요?

2022-11-01 20:17 UTC, jhy979 commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
추가적으로 궁금한 것이 `category.id` 를 받아야하나요?

`category name`만 옵셔널로 받는다면 undefined냐 존재하냐로 활용할 수 있을 것 같다는 생각이 들어요.

어떻게 생각하시나요😀?

2022-11-02 01:26 UTC, daaaayeah commented on frontend/src/@types/schedule.ts
> +  | typeof SCHEDULE.RESPONSE_TYPE.FEW_HOURS;
[refactor: 일정 응답 키 타입 간소화](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/f3a73a765b963de78e09dfff11a71ea90b3a8597)

요 커밋에 반영되어 있답니다 🙃
나인이 잘 만들어 주셔서 쓰임새 있게 활용할 수 있겠어요~!

2022-11-02 04:24 UTC, daaaayeah commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
> category && !category.id 부분도 !category?.id 이렇게 할 수 있나요?

category가 undefined인 경우에는 사용할 수 없습니다
`!undefined?.id` 값이 `true`예요 🥲

2022-11-02 04:28 UTC, daaaayeah commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
> 추가적으로 궁금한 것이 category.id 를 받아야하나요?
>
> category name만 옵셔널로 받는다면 undefined냐 존재하냐로 활용할 수 있을 것 같다는 생각이 들어요.
>
> 어떻게 생각하시나요😀?

아하 단순히 category.id가 필요하지 않은 값이라서가 아니라 `undefined냐 존재하냐로 활용` 때문에 말씀하신 건가요?!
category name으로 넘겨도 아래 세 가지 경우에 대한 처리가 필요할 것 같습니다

1. category name이 `undefined`인 경우 (달력 페이지)
2. category name이 `''`인 경우 (카테고리 페이지, 카테고리 미선택)
3. category name이 `undefined`도 `''`도 아닌 경우 (카테고리 페이지, 카테고리 선택)

2022-11-02 04:31 UTC, daaaayeah commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
> 혹시 일정 추가 모달이나 PageLayout같은 스타일 속성을 공통으로 이용하고 있어서 그러신걸까요?

넵 다른 컴포넌트에서 했던 것처럼 반복되는 로직을 굳이 두 번 작성하려고 하지 않았어요!

> 저는 개인적으로 return문을 따로 작성하는것이 더 분리가 되어 명확하다고 느끼는데

이렇게 하면 코드량은 늘어나도 더 명확하게 이해할 수 있을 거라는 생각도 드네요!
이 부분은 복잡하지 않아서 지금 그대로도 괜찮다고 생각합니다

2022-11-02 04:33 UTC, jhy979 commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
이렇게 3가지 분기처리를 category만으로 파악하는게 컴포넌트를 실제로 활용하는 부분에서 힘들지 않나요?
차라리 props를 하나 더 받아서 처리하는건 어떤가요?

```ts
type = "categoryCalendarLoading" | "calendarLoading" | "categoryBeforeSelect"
```

2022-11-02 05:48 UTC, daaaayeah commented on frontend/src/components/Calendar/Calendar.fallback.tsx
> +          {category?.id !== 0 && (
야호 같이 개선 완료~!
역할 분리도 제대로 됐고 코드도 좀 더 명확하게 읽을 수 있게 됐네요 ✨

[refactor: 달력 fallback 컴포넌트에서 카테고리 미선택 분리](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/e111a3c7ff0a37f2201bd5122abdfeffe8c3798e)

2022-11-02 05:49 UTC, daaaayeah commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
이 부분도 함께 개선 완료 🌈

[refactor: 달력 fallback 컴포넌트에서 카테고리 미선택 분리](https://github.com/woowacourse-teams/2022-dallog/pull/893/commits/e111a3c7ff0a37f2201bd5122abdfeffe8c3798e)

2022-11-02 05:49 UTC, jhy979 commented on frontend/src/pages/CalendarPage/CalendarPage.tsx
> +        )}
나이스...!

2022-11-02 05:50 UTC, jhy979 approved these changes
정말 정말 정말 고생하셨어여 티거...😀✨✨✨✨✨✨✨👏👏👏😀😀😀✋✋✋👍👍👍😊😝😝🌈🌈🌈✌✌✌😃😃😃😋😋😋😜😜😜

2022-11-02 05:56 UTC, merged