Feature/902 remove dependency member
woowacourse-teams/2022-dallog pull request #903
Opened 2022-11-05 18:06 UTC by summerlunaa

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- MemberService의 findSubscriber 메서드를 categoryRole 쪽으로 이동
- AuthService에서 멤버 가입 시 이벤트를 발행하는 것으로 다른 도메인에 대한 의존성 제거

## 주의사항

[Could not autowire. No beans of type found. error 해결](https://shlee0882.tistory.com/288)
`AuthServiceTest`에서 `events` 필드에 자동주입할 수 없다는 error가 발생합니다. 하지만 실제로는 잘 동작합니다...
이유는 위 링크와 같다는데 굳이 인텔리제이 에러 때문에 componentscan을 붙여줘야하나 싶어서 무시했습니다. 의견 주세여.

Closes #902

2022-11-06 06:04 UTC, hyeonic approved these changes
이것저것 고민을 많이 하셨네요 👍 고생하셨어요 파랑

이벤트는 의존성을 끊어내는 부분에서 굉장히 좋은 기술이지만 아직 동작 구조를 명확하게 이해하지 못해서 한눈에 파악하기 쉽지 않네요 🥲

팀원이 모여 전체적인 도메인과 의존성에 대해 한 번 그려보는 것도 좋을 것 같아요. 아무래도 짧은 일정 동안 서비스를 완성 시키기 위해 감수한 부분이 슬슬 눈에 띄기 시작하네요! 고생하셨습니다 🙇‍♂️

2022-11-10 01:24 UTC, devHudi requested changes
안녕하세요 패렁~ 제 개인적인 의견 몇가지 적어보았습니다. 수정 하신다고 하니 RC로 일단 남길게요!

2022-11-10 01:26 UTC, hyeonic commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +        eventPublisher.publishEvent(new MemberSavedEvent(savedMember.getId()));
도메인 내에서 이벤트를 발행하는 것은 엔티티(도메인) 객체가 너무 Spring Data에 종속적인 것은 아닌가 우려되네요!

2022-11-10 03:42 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/auth/application/AuthService.java
> +        eventPublisher.publishEvent(new MemberSavedEvent(savedMember.getId()));
java에서 제공하는 애노테이션 중 `@PostPersist`를 적용하면 해당 객체가 영속된 직후에 특정 메서드를 실행할 수 있습니다.
이를 이용해서 도메인 이벤트를 발행하려 했는데요, 이 경우 테스트에서 레포지포리를 이용해 회원을 생성하면 자동으로 카테고리, 구독, 역할이 생성되어 테스트가 어렵네요 🥲
엔티티가 `AbstractAggregateRoot`를 상속받아 사용하니 spring data에 종속되는 문제도 있구요.
우선은 서비스에서 publisher를 통해 이벤트를 발행하도록 하였습니다.

2022-11-10 03:42 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        createCategoryRoleAsAdminToCreator(member, category);
해당 메소드 아래로 수정했습니다.

2022-11-10 03:42 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/category/application/CategoryService.java
> +        createCategoryRoleAsAdminToCreator(member, category);
넵 맞습니다ㅎㅎ 우선적으로 Member, Auth만 분리했습니다.

2022-11-10 03:44 UTC, summerlunaa commented on backend/src/main/java/com/allog/dallog/domain/categoryrole/application/CategoryRoleService.java
> +    }
`Subscription`으로 옮기는 걸 고려해볼 수 있겠네요! 도메인 간의 의존성도 그렇고 전체적인 점검이 필요해보입니다.

2022-11-10 03:58 UTC, devHudi approved these changes

2022-11-10 03:58 UTC, gudonghee2000 approved these changes
안녕하세요 파랑! 다른분들이 피드백해주셔서 바로 approve하겟습니다!
이벤트방식을 실제로 보는건 처음인데 코드의 많은 의존성이 제거되는게 신기하고 많이배웠어요
고생하셧습니다~

2022-11-10 05:02 UTC, merged