[refactor] CategoryService의 테스트 메서드 조건절에 문장형 테스트를 적용한다.
woowacourse-teams/2022-dallog pull request #909
Opened 2022-11-08 09:29 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용

- categoryService 테스트의 조건절에 문장형 테스트 적용

아래의 코드는 테스트 메서드의 `given`절에 문장형 테스트를 적용한 예시입니다.
```java

 @DisplayName("권한이 ADMIN이 아닌 카테고리를 삭제하려 하면 예외를 발생한다.")
    @Test
    void 권한이_ADMIN이_아닌_카테고리를_삭제하려_하면_예외를_발생한다() {
        // given
        네오.회원_가입을_한다(네오_이메일, 네오_이름, 네오_프로필_URL)
                .카테고리를_등록한다(취업_카테고리_이름, NORMAL);

        제이슨.회원_가입을_한다(MEMBER_이메일, MEMBER_이름, MEMBER_프로필_URL)
                .카테고리를_구독한다(네오.카테고리());

        // when & then
        assertThatThrownBy(() -> categoryService.delete(제이슨.계정().getId(), 네오.카테고리().getId()))
                .isInstanceOf(NoCategoryAuthorityException.class);
    }
```

Closes #908

2022-11-10 01:37 UTC, devHudi requested changes
안녕하세요 리버~ CategoryService 의 테스트 가독성을 메소드 체이닝 (빌더패턴?..)을 사용하여 개선해주셨군요! 저는 결과물이 너무 맘에 드는 것 같아요. 몇 가지 수정해보면 좋을 부분에 코멘트 남겨두었으니 확인 부탁드립니다!

2022-11-10 01:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/common/Constants.java
> +}
말씀해주신 상수 픽스쳐군요! 나중에 규모가 커지면 도메인별로 분리할 수 있을 것 같아요~!

2022-11-10 01:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/presentation/ControllerTest.java
> +})
이 부분은 #907 여기랑 중복되는 부분인가요? 머지할 때 rebase 신경써서 해주시면 될 것 같습니다 !

2022-11-10 01:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
저희는 실제로 `User` 라는 도메인 용어를 사용하지 않고 있어서 이 내부 클래스는 이름이 조금 바뀌면 좋을 것 같아요! `MemberBuilder` 라던가 `MemberFixture` 같은 Member라는 단어를 사용하는게 좋아보입니다!

2022-11-10 01:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        }
```suggestion
        private Member 회원() {
            return member;
        }
```

마찬가지로 도메인 용어를 사용하는게 좋아보여요!

2022-11-10 01:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +                .카테고리를_구독한다(네오.카테고리());
가독성이 진짜 확실히 좋아졌네요! 저는 이 방식 적극적으로 사용할 것 같아요! 맘에 드네요 😄

2022-11-10 07:12 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
`BusinessBuilder`라는 네이밍으로 변경해보았어요!

2022-11-10 07:13 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        }
`회원()` 메서드 명으로 변경해보았어요!

2022-11-10 09:31 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
`Business` 라는 네이밍을 사용하신 이유는 무엇인가요??

2022-11-10 09:33 UTC, devHudi approved these changes
LGTM! Approve 드립니다!

2022-11-10 10:09 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("관리권한이 ADMIN인 카테고리 목록을 조회한다.")
`CategoryRepository`의 메서드중 `@Lock` 애노테이션이붙어있는 메서드를 사용하는 로직으로 인해 @Transaction이 적용되었습니다!
자세한 내용은 후디의 세미나를 기다리고있습니다!

2022-11-10 10:37 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("관리권한이 ADMIN인 카테고리 목록을 조회한다.")
언제할까용

2022-11-10 10:52 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("관리권한이 ADMIN인 카테고리 목록을 조회한다.")
내일 해주시나여

2022-11-10 11:32 UTC, hyeonic approved these changes
테스트가 훨씬 잘 읽히는 것 같네요! 고생하셨습니다 😃 간단히 리뷰 남겼으니 확인해주세요!

2022-11-10 11:32 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +                .카테고리를_구독한다(네오.카테고리());
동의합니다!

2022-11-10 11:33 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
저두 궁금하네요 🤔

2022-11-10 13:22 UTC, summerlunaa requested changes
와우 리버의 노력이 너무 잘 보이는 PR이군요... 테스트가 훨씬 읽기 좋아진 것 같아요!!
이 PR이 앞으로의 test code 리팩토링의 방향을 정해줄 것 같아서 단어 하나하나 꼼꼼히 보았습니다. 한 번 봐주시고 의견 남겨주세요!!

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    private BusinessBuilder 제이슨;
r: 저희 이름을 쓰는 건 어떨까요?

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +            assertThat(개인_카테고리.isPersonal()).isTrue();
then에서 검증하는 값의 네이밍을 `actual`로 통일하는 것은 어떨까요?
네이밍 고민하는 시간도 줄이고 검증하는 값이라는 것을 명확히 보여줄 수 있을 것 같아요.

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 카테고리를_등록한다() {
c: 이참에 중복되는 Display 애노테이션 확 제거해벌일까요?👀

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리를_등록한다() {
c: `PERSONAL`, `ADMIN` 같은 코드 레벨의 용어를 사용하면 변경에 취약할 것 같아요. 전체적인 비즈니스 이름을 테스트하는 만큼 조금 더 추상적인 도메인 용어를 사용하는 것은 어떨까요?
`PERSONAL`은 `개인`으로, `ADMIN`은 `어드민`, `최고 관리자` 등으로 변경할 수 있을 것 같아요.

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("카테고리를 등록할 떄 이름이 공백이거나 길이가 20을 초과하면 예외를 발생한다.")
r: `예외가 발생한다`로 통일할까요?

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("외부 카테고리를 등록한다.")
a: 등록한다 VS 생성한다
여러분의 선택은?

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +                .카테고리를_구독한다(네오.카테고리());
동의합니다!

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 검색어가_제목에_있는_카테고리를_가져온다() {
```suggestion
    void 제목에_검색어가_포함된_카테고리를_가져온다() {
```
c: 어떤가요?

2022-11-10 13:22 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리는_삭제할_수_없다() {
r: `예외가 발생한다`로 통일하는 건 어떨까요?

2022-11-10 13:36 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
음 Business 로직을 일부 만든다는 의미에서 작성을 해보았어요.
적절한 네이밍이 떠오르지 않네요.. 
우선 `GivenBuilder`라는 네이밍이 떠오르는데 
더 좋은 네이밍이 있을까요??

2022-11-10 13:45 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
`CategoryServiceTest`에서 @BeforeEach 구문을 사용하다보니 
`ServiceTest` 에서는 @AfterEach 구문을 사용하도록 하였어요!

그런데, 인수테스트에서는 @BeforeEach로 DB truncate를 진행하게 되면
인수테스트 이후  -> 서비스 테스트가 실행되는 경우에서 
인수테스트에서 저장된 DB 데이터로 인해 테스트 격리가 정상적으로 이루어지지 않는 오류를 만났습니다!

그래서 `AcceptanceTest`에서 @AfterEach를 사용하도록 구성하였어요.

이 부분을 인지하고 있어서 이후에 `CategoryServiceTest` 에 있는 `innerClass`인 `BusinessBuidler`(현재는 네이밍을 변경해보았어요)를 이후 커밋에서 외부로 분리하게되면 다시 @BeforeEach로 변경할 예정입니다!

2022-11-10 13:45 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/common/annotation/ServiceTest.java
>      }
위와 같은 이유로 변경하였어요!

2022-11-10 13:51 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    private BusinessBuilder 제이슨;
저희 프론트 크루 분들의 이름으로 변경해보았어요!

2022-11-10 17:33 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +        private Schedule schedule;
FixtureBuilder ?? 🤔

2022-11-11 11:43 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +            assertThat(개인_카테고리.isPersonal()).isTrue();
수정해보았어요!

2022-11-11 11:44 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 카테고리를_등록한다() {
모두 제거해보았어요!

2022-11-11 11:47 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리를_등록한다() {
수정 해보았어요!

2022-11-11 12:06 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    @DisplayName("카테고리를 등록할 떄 이름이 공백이거나 길이가 20을 초과하면 예외를 발생한다.")
수정해보았어요!

2022-11-11 12:07 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 검색어가_제목에_있는_카테고리를_가져온다() {
저도 더 잘읽힌다고 생각이 들어요! 수정해보았어요!

2022-11-11 12:11 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리는_삭제할_수_없다() {
해당 메서드는 삭제에 대한 예외검증 테스트가 아닌 삭제 후 조회를 통해 정상 삭제되었는지 검증하는 테스트여서
수정을 진행하지 않았어요!

2022-11-11 14:24 UTC, hyeonic approved these changes

2022-11-11 14:24 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +            assertThat(개인_카테고리.isPersonal()).isTrue();
`actual` 통일 동의합니다!

2022-11-11 14:41 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리는_삭제할_수_없다() {
삭제 시 예외를 발생하는 테스트 맞는 것 같은데 한 번 더 확인 부탁드립니다!

2022-11-11 14:42 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 검색어가_제목에_있는_카테고리를_가져온다() {
혹시 `포함된` 이라는 단어를 반영하지 않은 이유가 있을까요!? 제목에 검색어가 `있는`이라는 문장이 조금 어색하게 느껴져요 ㅠ_ㅠ

2022-11-11 14:55 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
현재 @BeforeEach구문에 'givenBuilder' 생성 로직이 담겨있는데요!
이부분을 테스트메서드 내부로 옮기는 부분을 짚어주긴것일까요?!

2022-11-11 14:57 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void 검색어가_제목에_있는_카테고리를_가져온다() {
헉 제가 리뷰를 보는 과정에서 놓쳤네요..
수정 하도록하겟습니다! 감사합니다~

2022-11-11 14:57 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리는_삭제할_수_없다() {
다시 확인하고 반영하겠습니다!

2022-11-11 15:05 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
으음 저도@beforeEach에 넣어주는것이 괜찮다는 생각이예요!
가독성부분과 class의 필드로 지정되어있는 부분이여서
builder까지는 괜찮지 않을까 싶은데요!

아니면 팩터리 메서드를 활용해서 

테스트메서드에 넣어준다면 가독성도 잡고 beforeEach구문도 제거할스있을거라는 생각도 들어요!
다들 정적팩터리메서드 다 사용아떤신가요??

2022-11-11 15:05 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
맞아요! 파랑 말 처럼 정하는 방향도 방법이 될 수 있지만 리버가 문장형 테스트를 만든 후 이 부분은 충분히 감수할 수 있다고 생각됩니다. 다들 `BeforeEach`를 바라보는 입장이 다른 것 같아요. 저는 `테스트 환경을 세팅`하는 데 사용하는 것이 적합하다 생각해요. 하지만 아래와 같은 코드는 각각의 테스트의 초기 데이터를 세팅하기 위한 부분인데 이것을 테스트 환경이라고 바라봐야 할까요?

```java
   @BeforeEach
    void setUp() {
        나인 = new GivenBuilder();
        티거 = new GivenBuilder();
    }
```

2022-11-11 15:13 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
애초에 `@BeforeEach`가 테스트 환경만 설정해야 하는 건지, 테스트 데이터도 세팅해도 되는지를 바라보는 관점 차이일 것 같네요 🤔 사실 저는 둘 다 큰 상관 없긴 합니다만, 이정도 데이터 세팅은 괜찮다고 생각해요 :)

2022-11-11 15:51 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
`@BeforeEach` 구문의 역할을 `테스트 환경 세팅`에서 사용 할 지 `테스트 환경 세팅과 데이터 세팅`으로 볼지에 따라 달라질것 같아요!

현재는 `GivenBuilder`의 가독성 때문에 `@BeforeEach` 구문을 사용하고 있다고 생각해요.

그렇다면, `@BeforeEach`를 제거하고 가독성을 높힌다면 괜찮지 않을까 생각하는데요.
정적 팩터리 메서드의 장점 중 하나인 `생성자에 네이밍을 준다`는 점에 착안하여서 
```java
class CategoryServiceTest extends ServiceTest {
	@Test
    	void 카테고리를_생성한다() {
       		 // given
        		나인().회원_가입을_한다(티거_이메일, 티거_이름, 티거_프로필_URL);

       		 // when
        		CategoryResponse actual = categoryService.save(나인.회원().getId(), 취업_카테고리_생성_요청);

        		// then
        		assertThat(actual.getName()).isEqualTo(취업_카테고리_이름);
    	}

	private final class GivenBuilder {

		private static GivenBuilder 나인() {
			return new GivenBuilder();	
		}

               private GivenBuilder 회원_가입을_한다(){
                      ...
                }
	}
} 
```

위와 같이 구성해보는것은 어떨까요??

2022-11-11 16:00 UTC, hyeonic commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
[이부분은](https://github.com/woowacourse-teams/2022-dallog/pull/909#discussion_r1020306911) 제가 착각했네요. 리버가 개선으로 남겨주신 부분 확인 했는데, 전 좋은 것 같아요!

2022-11-11 16:14 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/domain/category/application/CategoryServiceTest.java
> +    void PERSONAL_카테고리는_삭제할_수_없다() {
이 부분은 삭제 후에 `findById()`로 정상 삭제되었는지 확인하는 로직 이예요.
```java
@Test
    void 권한이_최고_관리자인_카테고리를_삭제한다() {
        // given
        나인.회원_가입을_한다(티거_이메일, 티거_이름, 티거_프로필_URL)
                .카테고리를_생성한다(취업_카테고리_이름, NORMAL);

        // when
        categoryService.delete(나인.회원().getId(), 나인.카테고리().getId());

        //then
        assertThatThrownBy(() -> categoryRepository.getById(나인.카테고리().getId()))
                .isInstanceOf(NoSuchCategoryException.class);
    }
```
위와 같아요.
삭제 기능이 정상 작동에 대한 테스트입니다!

2022-11-11 16:26 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/acceptance/AcceptanceTest.java
>      }
저도 좋습니다!

2022-11-12 06:28 UTC, summerlunaa approved these changes
변경사항 확인했습니다!! 진짜 수고했어요👊

2022-11-12 07:01 UTC, merged