[refactor] CategoryRole, ExternalCalendar, Member 도메인에 대한 통합테스트에 문장형 테스트를 적용한다.
woowacourse-teams/2022-dallog pull request #915
Opened 2022-11-14 05:19 UTC by gudonghee2000

- [x] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [x] 💯 테스트는 잘 통과했나요?
- [x] 🏗️ 빌드는 성공했나요?
- [x] 🧹 불필요한 코드는 제거했나요?
- [x] 💭 이슈는 등록했나요?
- [x] 🏷️ 라벨은 등록했나요?
- [x] 💻 git rebase를 사용했나요?
- [x] 🌈 알록달록한가요?

## 작업 내용
- CategoryRole에 대한 통합테스트에 문장형 테스트 적용
- ExternalCalendar에 대한 통합테스트에 문장형 테스트 적용
- Member에 대한 통합테스트에 문장형 테스트 적용 

Closes #912

2022-11-14 05:39 UTC, summerlunaa approved these changes
리버 수고하셨습니다! 테스트가 깔끔해졌네요 💯 
몇몇 메소드 네이밍만 조금 수정해보았어요 어떤가요!?

2022-11-14 05:39 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +        private GivenBuilder 내_카테고리_관리_권한을_부여한다(final Member otherMember) {
```suggestion
        private GivenBuilder 내_카테고리에_관리자_권한을_부여한다(final Member otherMember) {
```

2022-11-14 05:39 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +    void 카테고리_관리권한이_관리자인_회원이_다른_관리자의_권한을_변경한다() {
```suggestion
    void 카테고리_권한이_관리자인_회원이_다른_관리자의_권한을_변경한다() {
```
r: 카테고리 관리권한 -> 카테고리 권한으로 통일하는 건 어떨까요?

2022-11-14 05:39 UTC, summerlunaa commented on backend/src/test/java/com/allog/dallog/category/application/ExternalCategoryDetailServiceTest.java
> +    void 월별_일정_조회를_하면_회원의_외부_서비스_카테고리_전체를_조회한다() {
```suggestion
    void 월별_일정을_조회하면_회원의_외부_카테고리_전체를_조회한다() {
```

2022-11-14 08:15 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +        private GivenBuilder 내_카테고리_관리_권한을_부여한다(final Member otherMember) {
`내_카테고리에_대한_관리_권한을_부여한다`로 변경해보았어요!

2022-11-14 08:15 UTC, devHudi requested changes
안녕하세요 리버! 수정하면 좋을것 같은 부분에 하나 코멘트 남겼습니다!

2022-11-14 08:15 UTC, devHudi commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +    }
`나인()` 을 호출하는데, 티거 이메일을 넣을 일은 없는 것 같아요. 그렇다면 애초에 회원가입까지 하고 반환해버리면 어떨까요?

2022-11-14 08:18 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +    void 카테고리_관리권한이_관리자인_회원이_다른_관리자의_권한을_변경한다() {
수정해보았어요!

2022-11-14 08:18 UTC, hyeonic approved these changes
굳! 굉장히 귀찮을 부분이었을 텐데 이전보다 확실히 잘 읽히네요 😃 고생하셨습니다!

2022-11-14 08:44 UTC, gudonghee2000 commented on backend/src/test/java/com/allog/dallog/categoryrole/application/CategoryRoleServiceTest.java
> +    }
`Given`절을 통해 비지니스로직을 표현하려고하였어요!
`Member` 객체를 생성하는 로직이 메서드에 들어가게되면 이 부분에 혼동의 여지가있어 회원가입을 추가하지 않고 구현해보았어요!

2022-11-14 08:51 UTC, devHudi approved these changes
빌더 클래스를 나중에 분리해주신 다음에 회원 생성 로직을 함께 포함 부탁드려요! Approve 드립니다!

2022-11-15 00:47 UTC, summerlunaa approved these changes
수정 확인했습니다! approve 할게요 >_<

2022-11-15 01:04 UTC, merged